function buildCareLocale(copy) {
  return {
    navLabel: copy.navLabel,
    metaTitle: copy.metaTitle,
    metaDescription: copy.metaDescription,
    footerLine: copy.footerLine,
    prototypeNote: copy.prototypeNote,
    hero: {
      eyebrow: copy.eyebrow,
      title: copy.heroTitle,
      lead: copy.heroIntro,
      primary: copy.ctaPrimary,
      secondary: copy.ctaPrint,
      note: copy.heroReassurance,
      supportLine: copy.supportLine,
    },
    passport: copy.passport,
    assuranceLabel: copy.assuranceLabel,
    assurances: copy.assurances,
    journey: {
      eyebrow: copy.journeyEyebrow,
      title: copy.journeyTitle,
      intro: copy.journeyIntro,
      steps: copy.journeySteps,
    },
    firstWeek: {
      eyebrow: copy.firstWeekEyebrow,
      title: copy.firstWeekTitle,
      intro: copy.firstWeekIntro,
      personalAdvice: copy.personalAdvice,
      cards: [copy.normal, copy.call, copy.emergency],
      channelNote: copy.channelNote,
    },
    promise: copy.promise,
    certainty: copy.certainty,
    handout: {
      eyebrow: copy.handoutEyebrow,
      title: copy.handoutTitle,
      intro: copy.handoutIntro,
      printLabel: copy.ctaPrint,
      documentTitle: copy.handoutDocumentTitle,
      fields: copy.handoutFields,
      priority: copy.handoutPriority,
      groups: [copy.normal, copy.call, copy.emergency].map((group) => ({
        label: group.label,
        title: group.title,
        items: group.items,
      })),
      contactTitle: copy.contactTitle,
      contactClinic: copy.contactClinic,
      contactEmergency: copy.contactEmergency,
      confirmation: copy.confirmation,
      signatures: copy.signatures,
    },
    closing: copy.closing,
  }
}

const nl = buildCareLocale({
  navLabel: 'Nazorg & zekerheid',
  metaTitle: 'Nazorg & de eerste 7 dagen | Batumi Dental Clinic',
  metaDescription: 'Lees hoe Batumi Dental Clinic u voorbereidt, begeleidt en snel beoordeelt wanneer herstel anders verloopt dan verwacht.',
  footerLine: 'Goede zorg eindigt niet bij de behandelstoel.',
  prototypeNote: 'Conceptprototype · Noodnummer, bereikbaarheid, garantievoorwaarden en eventuele verzekeringspartner moeten vóór publicatie schriftelijk worden geverifieerd.',
  eyebrow: 'Nazorg · complicatiezorg · duidelijke afspraken',
  heroTitle: 'Goed voorbereid, ook na uw behandeling.',
  heroIntro: 'Wij zijn ons ervan bewust: tandheelkundige zorg vraagt om duidelijke uitleg en een bereikbaar team. Of u nu in Batumi woont of uit Europa komt, vóór de behandeling bespreken we wat u kunt verwachten, wanneer u belt en wat de kliniek doet als het herstel anders verloopt.',
  heroReassurance: 'Niet om u ongerust te maken, maar om u geïnformeerd, voorbereid en ondersteund te laten voelen.',
  supportLine: 'Wij zijn er voor jou!',
  ctaPrimary: 'Bespreek uw behandelplan',
  ctaPrint: 'Print de eerste 7 dagen',
  passport: {
    ariaLabel: 'Zorgpas voor de eerste zeven dagen',
    label: 'Uw zorgpas',
    title: 'De eerste 7 dagen',
    text: 'Persoonlijke instructies, een geverifieerde contactroute en een controle vóór vertrek.',
    stamp: 'Besproken',
  },
  assuranceLabel: 'Wat u vóór de behandeling ontvangt',
  assurances: [
    ['Vooraf besproken', 'Herstel, risico’s en keuzes in gewone taal.'],
    ['Bereikbaar team', 'Een geverifieerde belroute voor dringende vragen.'],
    ['Controle gepland', 'Waar passend: een laatste check vóór uw vlucht.'],
  ],
  journeyEyebrow: 'Zorg vóór, tijdens en na',
  journeyTitle: 'Zo helpt de kliniek alles goed te laten verlopen.',
  journeyIntro: 'Goede nazorg begint niet wanneer er iets misgaat. Ze begint bij voorbereiding, duidelijke instructies en genoeg tijd voor controle.',
  journeySteps: [
    { when: 'Vóór de behandeling', title: 'Samen voorbereiden', text: 'Uw tandarts bespreekt de ingreep, persoonlijke risico’s, verwacht herstel, medicatie, mondhygiëne, eten en reizen. U kunt vragen stellen vóór u toestemming geeft.' },
    { when: 'Op papier én mondeling', title: 'Alles duidelijk mee', text: 'U krijgt een persoonlijke éénpagina-gids “De eerste 7 dagen”, met instructies, waarschuwingssignalen, contactroute en controledatum.' },
    { when: 'Tijdens de eerste week', title: 'Eerst klinisch beoordelen', text: 'Onverwachte klachten worden door een tandarts getrieerd. Een noodzakelijke urgente beoordeling of stabilisatie wordt niet vertraagd doordat kosten nog worden besproken.' },
    { when: 'Vóór uw terugreis', title: 'Laatste controle', text: 'Waar dat medisch zinvol is, controleren we herstel, tijdelijke voorzieningen, beet, medicatie en vervolgstappen voordat u vliegt.' },
    { when: 'Na thuiskomst', title: 'Uw dossier reist mee', text: 'U krijgt relevante behandelgegevens, beelden en implantaat- of materiaalgegevens, zodat uw eigen tandarts goed geïnformeerd kan meekijken.' },
  ],
  firstWeekEyebrow: 'Rustig weten wat u doet',
  firstWeekTitle: 'De eerste 7 dagen in drie duidelijke niveaus.',
  firstWeekIntro: 'De meeste genezing verloopt normaal. Met deze indeling weet u wat vaak past bij herstel, wanneer u de kliniek belt en wanneer u direct spoedhulp inschakelt.',
  personalAdvice: 'Uw persoonlijke ontslaginstructie gaat altijd vóór algemene informatie op deze pagina.',
  normal: {
    tone: 'normal', label: 'Volg uw instructies', title: 'Wat vaak bij herstel past',
    intro: 'Afhankelijk van de ingreep kunnen de eerste dagen voorkomen:',
    items: ['Milde tot matige, beheersbare pijn of gevoeligheid', 'Beperkte zwelling of een blauwe plek', 'Een kleine hoeveelheid nabloeding of wondvocht', 'Tijdelijke gevoeligheid bij eten, drinken of aanraking'],
    action: 'Het verloop hoort beheersbaar te zijn en geleidelijk te verbeteren.',
  },
  call: {
    tone: 'call', label: 'Bel de kliniek dezelfde dag', title: 'Laat ons snel meekijken',
    intro: 'Neem eerder contact op wanneer iets afwijkt of u zich onzeker voelt:',
    items: ['Pijn die na 48–72 uur duidelijk toeneemt of niet beheersbaar is', 'Aanhoudende of toenemende zwelling, koorts of rillingen', 'Pus, een vieze smaak of geur samen met verslechtering', 'Gevoelloosheid of tinteling die niet verbetert', 'Een los implantaat, los onderdeel of een gebroken tijdelijke voorziening'],
    action: 'Een tandarts bepaalt telefonisch hoe urgent een onderzoek is.',
  },
  emergency: {
    tone: 'emergency', label: 'Bel in Georgië direct 112', title: 'Medische spoed wacht niet',
    intro: 'Schakel meteen lokale spoedhulp in bij:',
    items: ['Moeite met ademhalen of slikken', 'Snel uitbreidende zwelling van gezicht, mond of hals', 'Ernstig ziek worden, flauwvallen of verwardheid', 'Een bloeding die ondanks stevige druk volgens instructie niet stopt'],
    action: 'Bel eerst 112. Informeer de kliniek zodra dat veilig kan.',
  },
  channelNote: 'De kliniek geeft vóór behandeling een geverifieerd telefoonnummer en back-uproute. WhatsApp is alleen ondersteunend en nooit het eerste noodkanaal; medische beelden horen in de beveiligde upload.',
  promise: {
    eyebrow: 'Onze afspraak met u',
    title: 'Een probleem wordt besproken én beoordeeld.',
    quote: 'Ontstaat binnen zeven kalenderdagen na uw behandeling een onverwacht probleem dat mogelijk met de ingreep samenhangt? Een tandarts beoordeelt de urgentie. Noodzakelijke stabiliserende zorg wordt niet vertraagd door een betalingsgesprek. Corrigerende behandeling die onder onze schriftelijke verantwoordelijkheid valt, voeren wij zonder extra kliniekkosten uit.',
    scope: 'Externe ziekenhuis-, tandarts-, apotheek-, laboratorium-, reis- en verblijfskosten zijn niet automatisch inbegrepen, tenzij dit vooraf uitdrukkelijk schriftelijk is afgesproken.',
  },
  certainty: {
    eyebrow: 'Garantie en verzekering',
    title: 'Drie dingen die u niet door elkaar hoeft te halen.',
    intro: 'De oorspronkelijke behandeling, de verantwoordelijkheid van de kliniek en een eventuele externe verzekering zijn drie verschillende afspraken.',
    items: [
      { label: 'Uw behandeling', title: 'De oorspronkelijke zorg is zelfbetaald', text: 'De patiënt betaalt de afgesproken behandeling. Deze pagina belooft geen terugbetaling van die oorspronkelijke rekening.' },
      { label: 'Schriftelijke kliniekvoorwaarden', title: 'Kliniekgarantie is geen verzekering', text: 'De kliniek beoordeelt klachten en herstelt wat volgens de schriftelijke complicatie- en garantievoorwaarden rechtstreeks onder haar verantwoordelijkheid valt.' },
      { label: 'Alleen via een bevoegde verzekeraar', title: 'Complicatieverzekering kan alleen apart', text: 'Pas met een echte polis via een erkende verzekeraar kunnen nauwkeurig omschreven externe kosten gedekt zijn. Looptijd, landen, limieten, bewijs en uitsluitingen staan dan in die polis.' },
    ],
    note: 'Dit prototype biedt of belooft momenteel geen afzonderlijke complicatieverzekering. Een product mag pas worden genoemd nadat verzekeraar, polis en grensoverschrijdende verkoop schriftelijk zijn geverifieerd.',
  },
  handoutEyebrow: 'Meenemen en bespreken',
  handoutTitle: 'Uw persoonlijke éénpagina-gids.',
  handoutIntro: 'De kliniek vult dit blad per behandeling in, legt het uit in een taal die u begrijpt en laat ontvangst en begrip bevestigen.',
  handoutDocumentTitle: 'De eerste 7 dagen na mijn behandeling',
  handoutFields: ['Naam patiënt', 'Behandeling en behandeld gebied', 'Datum en tijd behandeling', 'Geplande controle'],
  handoutPriority: 'Mijn persoonlijke instructies van de tandarts gaan altijd vóór deze algemene samenvatting.',
  contactTitle: 'Mijn contactroute',
  contactClinic: 'Geverifieerd klinieknummer en back-up: door de kliniek in te vullen vóór behandeling.',
  contactEmergency: 'Medisch noodgeval in Georgië: bel 112.',
  confirmation: 'Mijn handtekening bevestigt alleen dat ik dit document heb ontvangen, dat het mondeling is uitgelegd en dat ik vragen kon stellen. Dit is geen afstand van patiëntenrechten.',
  signatures: ['Patiënt · handtekening en datum', 'Behandelaar · handtekening en datum'],
  closing: { eyebrow: 'Eerst duidelijkheid', title: 'Bespreek nazorg vóór u uw reis boekt.', text: 'Vraag welke controles in uw behandelplanning passen, welke voorwaarden gelden en welk nummer u tijdens uw verblijf gebruikt.', cta: 'Plan een persoonlijk gesprek' },
})

const en = buildCareLocale({
  navLabel: 'Aftercare & assurance',
  metaTitle: 'Aftercare & the first 7 days | Batumi Dental Clinic',
  metaDescription: 'See how Batumi Dental Clinic prepares, supports and promptly assesses patients when recovery differs from what was expected.',
  footerLine: 'Good care continues after the treatment chair.',
  prototypeNote: 'Concept prototype · Emergency contact availability, warranty terms and any insurance partner must be verified in writing before publication.',
  eyebrow: 'Aftercare · complication care · clear agreements',
  heroTitle: 'Prepared care, before and after treatment.',
  heroIntro: 'We understand that dental care requires clear information and an accessible team. Whether you live in Batumi or travel from Europe, before treatment we explain what to expect, when to call and what the clinic can do if recovery differs from the plan.',
  heroReassurance: 'Not to cause concern, but to help you feel informed, prepared and supported.',
  supportLine: 'We are here for you!',
  ctaPrimary: 'Discuss your treatment plan',
  ctaPrint: 'Print the first 7 days',
  passport: { ariaLabel: 'Care passport for the first seven days', label: 'Your care passport', title: 'The first 7 days', text: 'Personal instructions, a verified contact route and a review before departure.', stamp: 'Explained' },
  assuranceLabel: 'What you receive before treatment',
  assurances: [['Explained in advance', 'Recovery, risks and choices in plain language.'], ['Accessible team', 'A verified telephone route for urgent concerns.'], ['Review planned', 'When appropriate: a final check before your flight.']],
  journeyEyebrow: 'Care before, during and after',
  journeyTitle: 'How the clinic helps your recovery go smoothly.',
  journeyIntro: 'Good aftercare does not begin when something goes wrong. It starts with preparation, clear instructions and enough time for review.',
  journeySteps: [
    { when: 'Before treatment', title: 'Prepare together', text: 'Your dentist explains the procedure, personal risks, expected recovery, medication, oral hygiene, eating and travel. You can ask questions before giving consent.' },
    { when: 'In writing and verbally', title: 'Take clear guidance with you', text: 'You receive a personal one-page “First 7 Days” guide with instructions, warning signs, your contact route and review date.' },
    { when: 'During the first week', title: 'Clinical assessment comes first', text: 'A dentist triages unexpected concerns. Necessary urgent assessment or stabilising care is not delayed while costs are still being clarified.' },
    { when: 'Before travelling home', title: 'Final review', text: 'When clinically appropriate, we review healing, temporary work, bite, medication and next steps before you fly.' },
    { when: 'After you return home', title: 'Your records travel with you', text: 'You receive relevant treatment information, images and implant or material details so your local dentist can make an informed assessment.' },
  ],
  firstWeekEyebrow: 'Know what to do, calmly', firstWeekTitle: 'The first 7 days in three clear levels.',
  firstWeekIntro: 'Most recovery follows the expected course. This guide shows what can fit normal healing, when to call the clinic and when to seek emergency help immediately.',
  personalAdvice: 'Your procedure-specific discharge instructions always take priority over the general information on this page.',
  normal: { tone: 'normal', label: 'Follow your instructions', title: 'What can fit normal healing', intro: 'Depending on the procedure, the first days may include:', items: ['Mild to moderate, manageable discomfort or tenderness', 'Limited swelling or bruising', 'A small amount of bleeding or wound seepage', 'Temporary sensitivity when eating, drinking or touching the area'], action: 'Symptoms should remain manageable and generally improve over time.' },
  call: { tone: 'call', label: 'Call the clinic the same day', title: 'Let us assess it promptly', intro: 'Contact us early whenever the course differs or you feel uncertain:', items: ['Pain that clearly increases after 48–72 hours or cannot be controlled', 'Persistent or increasing swelling, fever or chills', 'Pus, a bad taste or smell together with worsening symptoms', 'Numbness or tingling that is not improving', 'A loose implant or component, or broken temporary work'], action: 'A dentist decides by telephone how urgently you need to be examined.' },
  emergency: { tone: 'emergency', label: 'In Georgia, call 112 now', title: 'Medical emergencies cannot wait', intro: 'Seek local emergency help immediately for:', items: ['Difficulty breathing or swallowing', 'Rapidly spreading swelling of the face, mouth or neck', 'Severe illness, fainting or confusion', 'Bleeding that does not stop after firm pressure as instructed'], action: 'Call 112 first. Inform the clinic as soon as it is safe.' },
  channelNote: 'Before treatment, the clinic provides a verified telephone number and back-up route. WhatsApp is supportive only and never the first emergency channel; medical images belong in the secure upload.',
  promise: { eyebrow: 'Our agreement with you', title: 'A concern is discussed and clinically assessed.', quote: 'If an unexpected problem that may relate to the procedure arises within seven calendar days, a dentist assesses the urgency. Necessary stabilising care is not delayed by a payment discussion. Corrective treatment that falls under our written responsibility is provided without additional clinic fees.', scope: 'External hospital, dentist, pharmacy, laboratory, travel and accommodation costs are not automatically included unless expressly agreed in writing beforehand.' },
  certainty: {
    eyebrow: 'Warranty and insurance', title: 'Three things you do not need to confuse.',
    intro: 'The original treatment, the clinic’s responsibility and any separate external insurance are three different agreements.',
    items: [
      { label: 'Your treatment', title: 'The original care is self-paid', text: 'The patient pays for the agreed treatment. This page does not promise reimbursement of that original bill.' },
      { label: 'Written clinic terms', title: 'A clinic warranty is not insurance', text: 'The clinic assesses concerns and corrects what falls directly under its responsibility according to the written complication-care and warranty terms.' },
      { label: 'Only through an authorised insurer', title: 'Complication insurance must be separate', text: 'Only a real policy from a licensed insurer can cover precisely defined external costs. Its duration, countries, limits, evidence and exclusions must be stated in that policy.' },
    ],
    note: 'This prototype does not currently offer or promise separate complication insurance. A product may be named only after the insurer, policy and cross-border distribution route have been verified in writing.',
  },
  handoutEyebrow: 'Take it with you', handoutTitle: 'Your personal one-page guide.',
  handoutIntro: 'The clinic completes this document for your procedure, explains it in a language you understand and records receipt and understanding.',
  handoutDocumentTitle: 'The first 7 days after my treatment',
  handoutFields: ['Patient name', 'Procedure and treated area', 'Treatment date and time', 'Planned review'],
  handoutPriority: 'My dentist’s personal instructions always take priority over this general summary.',
  contactTitle: 'My contact route', contactClinic: 'Verified clinic number and back-up: to be completed by the clinic before treatment.', contactEmergency: 'Medical emergency in Georgia: call 112.',
  confirmation: 'My signature only confirms that I received this document, it was explained verbally and I could ask questions. It is not a waiver of patient rights.',
  signatures: ['Patient · signature and date', 'Clinician · signature and date'],
  closing: { eyebrow: 'Clarity first', title: 'Discuss aftercare before booking your trip.', text: 'Ask which reviews fit your treatment plan, which written terms apply and which telephone number you will use during your stay.', cta: 'Book a personal consultation' },
})

const de = buildCareLocale({
  navLabel: 'Nachsorge & Sicherheit',
  metaTitle: 'Nachsorge & die ersten 7 Tage | Batumi Dental Clinic',
  metaDescription: 'Erfahren Sie, wie Batumi Dental Clinic Sie vorbereitet, begleitet und Beschwerden zeitnah beurteilt.',
  footerLine: 'Gute Betreuung endet nicht am Behandlungsstuhl.',
  prototypeNote: 'Konzeptprototyp · Notfallnummer, Erreichbarkeit, Garantiebedingungen und ein möglicher Versicherungspartner müssen vor Veröffentlichung schriftlich geprüft werden.',
  eyebrow: 'Nachsorge · Komplikationsversorgung · klare Vereinbarungen',
  heroTitle: 'Gut vorbereitet – auch nach Ihrer Behandlung.',
  heroIntro: 'Wir sind uns bewusst: Zahnmedizin verlangt verständliche Informationen und ein erreichbares Team. Ob Sie in Batumi leben oder aus Europa anreisen – vor der Behandlung erklären wir, was Sie erwarten können, wann Sie anrufen und was die Klinik tun kann, wenn die Heilung anders verläuft.',
  heroReassurance: 'Nicht um Sie zu beunruhigen, sondern damit Sie sich informiert, vorbereitet und gut begleitet fühlen.',
  supportLine: 'Wir sind für Sie da!',
  ctaPrimary: 'Behandlungsplan besprechen', ctaPrint: 'Die ersten 7 Tage drucken',
  passport: { ariaLabel: 'Nachsorgepass für die ersten sieben Tage', label: 'Ihr Nachsorgepass', title: 'Die ersten 7 Tage', text: 'Persönliche Anweisungen, ein verifizierter Kontaktweg und eine Kontrolle vor der Abreise.', stamp: 'Besprochen' },
  assuranceLabel: 'Was Sie vor der Behandlung erhalten',
  assurances: [['Vorab erklärt', 'Heilung, Risiken und Möglichkeiten in klarer Sprache.'], ['Erreichbares Team', 'Ein verifizierter Telefonweg für dringende Anliegen.'], ['Kontrolle geplant', 'Wenn sinnvoll: eine letzte Kontrolle vor dem Flug.']],
  journeyEyebrow: 'Betreuung davor, währenddessen und danach',
  journeyTitle: 'So hilft die Klinik, dass Ihre Heilung gut verläuft.',
  journeyIntro: 'Gute Nachsorge beginnt nicht erst, wenn etwas schiefläuft. Sie beginnt mit Vorbereitung, verständlichen Anweisungen und ausreichend Zeit für Kontrollen.',
  journeySteps: [
    { when: 'Vor der Behandlung', title: 'Gemeinsam vorbereiten', text: 'Ihr Zahnarzt erläutert Eingriff, persönliche Risiken, Heilungsverlauf, Medikamente, Mundhygiene, Ernährung und Reisen. Vor Ihrer Einwilligung bleibt Zeit für Fragen.' },
    { when: 'Schriftlich und mündlich', title: 'Klare Hinweise mitnehmen', text: 'Sie erhalten Ihren persönlichen Einseiter „Die ersten 7 Tage“ mit Anweisungen, Warnzeichen, Kontaktweg und Kontrolltermin.' },
    { when: 'In der ersten Woche', title: 'Die klinische Beurteilung zählt zuerst', text: 'Ein Zahnarzt triagiert unerwartete Beschwerden. Eine notwendige dringende Untersuchung oder Stabilisierung wird nicht durch eine noch offene Kostenklärung verzögert.' },
    { when: 'Vor der Heimreise', title: 'Abschlusskontrolle', text: 'Wenn medizinisch sinnvoll, prüfen wir Heilung, Provisorien, Biss, Medikamente und die nächsten Schritte vor Ihrem Flug.' },
    { when: 'Nach Ihrer Rückkehr', title: 'Ihr Dossier reist mit', text: 'Sie erhalten relevante Behandlungsdaten, Bilder sowie Implantat- oder Materialangaben, damit Ihr Zahnarzt vor Ort informiert beurteilen kann.' },
  ],
  firstWeekEyebrow: 'Ruhig wissen, was zu tun ist', firstWeekTitle: 'Die ersten 7 Tage in drei klaren Stufen.',
  firstWeekIntro: 'Die meisten Heilungsverläufe sind unauffällig. Diese Einteilung zeigt, was dazugehören kann, wann Sie die Klinik anrufen und wann Sie sofort den Rettungsdienst brauchen.',
  personalAdvice: 'Ihre persönlichen, eingriffsspezifischen Entlassungsanweisungen haben immer Vorrang vor den allgemeinen Informationen dieser Seite.',
  normal: { tone: 'normal', label: 'Anweisungen befolgen', title: 'Was zur Heilung gehören kann', intro: 'Je nach Eingriff können in den ersten Tagen auftreten:', items: ['Leichte bis mäßige, beherrschbare Schmerzen oder Empfindlichkeit', 'Begrenzte Schwellung oder Bluterguss', 'Eine geringe Nachblutung oder Wundsekretion', 'Vorübergehende Empfindlichkeit beim Essen, Trinken oder Berühren'], action: 'Die Beschwerden sollten beherrschbar bleiben und sich allmählich bessern.' },
  call: { tone: 'call', label: 'Noch am selben Tag anrufen', title: 'Lassen Sie uns zeitnah prüfen', intro: 'Melden Sie sich früh, wenn der Verlauf abweicht oder Sie unsicher sind:', items: ['Schmerzen, die nach 48–72 Stunden deutlich zunehmen oder nicht kontrollierbar sind', 'Anhaltende oder zunehmende Schwellung, Fieber oder Schüttelfrost', 'Eiter, schlechter Geschmack oder Geruch zusammen mit einer Verschlechterung', 'Taubheit oder Kribbeln, das sich nicht bessert', 'Ein lockeres Implantat oder Bauteil oder eine gebrochene provisorische Versorgung'], action: 'Ein Zahnarzt entscheidet telefonisch, wie dringend Sie untersucht werden müssen.' },
  emergency: { tone: 'emergency', label: 'In Georgien sofort 112 wählen', title: 'Ein medizinischer Notfall wartet nicht', intro: 'Holen Sie sofort lokale Notfallhilfe bei:', items: ['Atem- oder Schluckbeschwerden', 'Schnell ausbreitender Schwellung von Gesicht, Mund oder Hals', 'Schwerem Krankheitsgefühl, Ohnmacht oder Verwirrtheit', 'Blutung, die trotz festem Druck nach Anweisung nicht aufhört'], action: 'Rufen Sie zuerst 112 an. Informieren Sie die Klinik, sobald es sicher ist.' },
  channelNote: 'Vor der Behandlung gibt die Klinik eine verifizierte Telefonnummer und einen Ersatzkontakt. WhatsApp dient nur unterstützend und ist nie der erste Notfallkanal; medizinische Bilder gehören in den sicheren Upload.',
  promise: { eyebrow: 'Unsere Vereinbarung mit Ihnen', title: 'Ein Anliegen wird besprochen und klinisch beurteilt.', quote: 'Tritt innerhalb von sieben Kalendertagen ein unerwartetes Problem auf, das mit dem Eingriff zusammenhängen könnte, beurteilt ein Zahnarzt die Dringlichkeit. Notwendige stabilisierende Versorgung wird nicht durch ein Zahlungsgespräch verzögert. Korrekturbehandlungen in unserer schriftlichen Verantwortung erfolgen ohne zusätzliche Klinikgebühr.', scope: 'Externe Krankenhaus-, Zahnarzt-, Apotheken-, Labor-, Reise- und Unterkunftskosten sind nicht automatisch enthalten, sofern dies nicht vorher ausdrücklich schriftlich vereinbart wurde.' },
  certainty: {
    eyebrow: 'Garantie und Versicherung', title: 'Drei Dinge, die Sie nicht verwechseln müssen.',
    intro: 'Die ursprüngliche Behandlung, die Verantwortung der Klinik und eine mögliche externe Versicherung sind drei unterschiedliche Vereinbarungen.',
    items: [
      { label: 'Ihre Behandlung', title: 'Die ursprüngliche Versorgung ist Selbstzahlerleistung', text: 'Der Patient bezahlt die vereinbarte Behandlung. Diese Seite verspricht keine Erstattung dieser ursprünglichen Rechnung.' },
      { label: 'Schriftliche Klinikbedingungen', title: 'Eine Klinikgarantie ist keine Versicherung', text: 'Die Klinik beurteilt Beschwerden und korrigiert, was nach den schriftlichen Komplikations- und Garantiebedingungen direkt in ihre Verantwortung fällt.' },
      { label: 'Nur über einen zugelassenen Versicherer', title: 'Komplikationsversicherung ist ein separates Produkt', text: 'Nur eine echte Police eines zugelassenen Versicherers kann genau definierte externe Kosten decken. Laufzeit, Länder, Grenzen, Nachweise und Ausschlüsse müssen dort stehen.' },
    ],
    note: 'Dieses Konzept bietet oder verspricht derzeit keine separate Komplikationsversicherung. Ein Produkt darf erst genannt werden, wenn Versicherer, Police und grenzüberschreitender Vertrieb schriftlich geprüft sind.',
  },
  handoutEyebrow: 'Mitnehmen und besprechen', handoutTitle: 'Ihr persönlicher Einseiter.',
  handoutIntro: 'Die Klinik ergänzt dieses Blatt für Ihren Eingriff, erklärt es in einer verständlichen Sprache und bestätigt Erhalt und Verständnis.',
  handoutDocumentTitle: 'Die ersten 7 Tage nach meiner Behandlung',
  handoutFields: ['Name des Patienten', 'Eingriff und behandelter Bereich', 'Datum und Uhrzeit', 'Geplante Kontrolle'],
  handoutPriority: 'Die persönlichen Anweisungen meines Zahnarztes haben immer Vorrang vor dieser allgemeinen Zusammenfassung.',
  contactTitle: 'Mein Kontaktweg', contactClinic: 'Verifizierte Kliniknummer und Ersatzkontakt: vor der Behandlung von der Klinik einzutragen.', contactEmergency: 'Medizinischer Notfall in Georgien: 112 wählen.',
  confirmation: 'Meine Unterschrift bestätigt nur, dass ich dieses Dokument erhalten habe, es mündlich erklärt wurde und ich Fragen stellen konnte. Sie ist kein Verzicht auf Patientenrechte.',
  signatures: ['Patient · Unterschrift und Datum', 'Behandler · Unterschrift und Datum'],
  closing: { eyebrow: 'Klarheit zuerst', title: 'Besprechen Sie die Nachsorge, bevor Sie Ihre Reise buchen.', text: 'Fragen Sie, welche Kontrollen zu Ihrem Behandlungsplan passen, welche Bedingungen gelten und welche Telefonnummer Sie während Ihres Aufenthalts nutzen.', cta: 'Persönliche Beratung vereinbaren' },
})

const fr = buildCareLocale({
  navLabel: 'Suivi & sérénité',
  metaTitle: 'Suivi & les 7 premiers jours | Batumi Dental Clinic',
  metaDescription: 'Découvrez comment Batumi Dental Clinic vous prépare, vous accompagne et évalue rapidement toute évolution inattendue.',
  footerLine: 'Un bon suivi continue après le fauteuil de soins.',
  prototypeNote: 'Prototype conceptuel · Le numéro d’urgence, la disponibilité, les garanties et tout partenaire assureur doivent être vérifiés par écrit avant publication.',
  eyebrow: 'Suivi · complications · engagements clairs',
  heroTitle: 'Bien accompagné, avant et après vos soins.',
  heroIntro: 'Nous en sommes conscients : les soins dentaires exigent des explications claires et une équipe joignable. Que vous habitiez à Batoumi ou veniez d’Europe, nous expliquons avant le traitement ce qui est attendu, quand appeler et ce que la clinique peut faire si la guérison évolue autrement.',
  heroReassurance: 'Non pour vous inquiéter, mais pour que vous vous sentiez informé, préparé et accompagné.',
  supportLine: 'Nous sommes là pour vous !',
  ctaPrimary: 'Discuter de mon plan de soins', ctaPrint: 'Imprimer les 7 premiers jours',
  passport: { ariaLabel: 'Passeport de suivi pour les sept premiers jours', label: 'Votre passeport de suivi', title: 'Les 7 premiers jours', text: 'Des consignes personnelles, un contact vérifié et un contrôle avant le départ.', stamp: 'Expliqué' },
  assuranceLabel: 'Ce que vous recevez avant le traitement',
  assurances: [['Expliqué à l’avance', 'Guérison, risques et choix en langage clair.'], ['Équipe joignable', 'Un parcours téléphonique vérifié pour les demandes urgentes.'], ['Contrôle prévu', 'Lorsque cela convient : un dernier contrôle avant le vol.']],
  journeyEyebrow: 'Avant, pendant et après', journeyTitle: 'Comment la clinique favorise une récupération sereine.',
  journeyIntro: 'Un bon suivi ne commence pas lorsqu’un problème survient. Il commence par la préparation, des consignes claires et du temps pour les contrôles.',
  journeySteps: [
    { when: 'Avant le traitement', title: 'Se préparer ensemble', text: 'Votre dentiste explique l’intervention, les risques personnels, la récupération, les médicaments, l’hygiène, l’alimentation et les déplacements. Vous pouvez poser vos questions avant de consentir.' },
    { when: 'À l’écrit et à l’oral', title: 'Repartir avec des consignes claires', text: 'Vous recevez votre fiche personnelle « Les 7 premiers jours », avec consignes, signes d’alerte, contact et date du contrôle.' },
    { when: 'Pendant la première semaine', title: 'L’évaluation clinique d’abord', text: 'Un dentiste trie toute évolution inattendue. Une évaluation urgente ou une stabilisation nécessaire n’est pas retardée pendant que les coûts sont clarifiés.' },
    { when: 'Avant le retour', title: 'Dernier contrôle', text: 'Lorsque cela est médicalement indiqué, nous vérifions la cicatrisation, les éléments provisoires, l’occlusion, les médicaments et la suite avant votre vol.' },
    { when: 'Après votre retour', title: 'Votre dossier vous accompagne', text: 'Vous recevez les informations, images et références d’implant ou de matériau utiles à l’évaluation de votre dentiste local.' },
  ],
  firstWeekEyebrow: 'Savoir quoi faire, sereinement', firstWeekTitle: 'Les 7 premiers jours en trois niveaux clairs.',
  firstWeekIntro: 'La plupart des récupérations suivent le cours attendu. Ce guide indique ce qui peut être normal, quand appeler la clinique et quand demander immédiatement une aide urgente.',
  personalAdvice: 'Vos consignes personnalisées liées à l’intervention priment toujours sur les informations générales de cette page.',
  normal: { tone: 'normal', label: 'Suivre vos consignes', title: 'Ce qui peut faire partie de la cicatrisation', intro: 'Selon l’intervention, les premiers jours peuvent comporter :', items: ['Douleur ou sensibilité légère à modérée et contrôlable', 'Gonflement limité ou bleu', 'Petit saignement ou léger suintement', 'Sensibilité temporaire en mangeant, en buvant ou au toucher'], action: 'Les symptômes doivent rester contrôlables et généralement diminuer.' },
  call: { tone: 'call', label: 'Appeler la clinique le jour même', title: 'Laissez-nous évaluer rapidement', intro: 'Contactez-nous tôt si l’évolution diffère ou vous inquiète :', items: ['Douleur qui augmente après 48–72 heures ou reste incontrôlable', 'Gonflement persistant ou croissant, fièvre ou frissons', 'Pus, mauvais goût ou odeur avec aggravation', 'Engourdissement ou picotement qui ne s’améliore pas', 'Implant ou élément mobile, ou provisoire cassé'], action: 'Un dentiste détermine par téléphone le degré d’urgence de l’examen.' },
  emergency: { tone: 'emergency', label: 'En Géorgie, appeler le 112', title: 'Une urgence médicale ne peut pas attendre', intro: 'Demandez immédiatement l’aide locale en cas de :', items: ['Difficulté à respirer ou à avaler', 'Gonflement rapide du visage, de la bouche ou du cou', 'Malaise grave, perte de connaissance ou confusion', 'Saignement qui ne s’arrête pas malgré une compression ferme conforme aux consignes'], action: 'Appelez d’abord le 112. Informez la clinique dès que cela est possible sans danger.' },
  channelNote: 'Avant les soins, la clinique fournit un numéro vérifié et une solution de secours. WhatsApp reste un canal d’appoint et jamais le premier canal d’urgence ; les images médicales passent par l’envoi sécurisé.',
  promise: { eyebrow: 'Notre engagement', title: 'Une préoccupation est écoutée et évaluée cliniquement.', quote: 'Si un problème inattendu pouvant être lié à l’intervention survient dans les sept jours calendaires, un dentiste en évalue l’urgence. Les soins de stabilisation nécessaires ne sont pas retardés par une discussion de paiement. Les corrections relevant de notre responsabilité écrite sont réalisées sans frais cliniques supplémentaires.', scope: 'Les frais externes d’hôpital, de dentiste, de pharmacie, de laboratoire, de voyage ou d’hébergement ne sont pas automatiquement inclus, sauf accord écrit préalable exprès.' },
  certainty: {
    eyebrow: 'Garantie et assurance', title: 'Trois notions à ne pas confondre.',
    intro: 'Le traitement initial, la responsabilité de la clinique et une éventuelle assurance externe sont trois accords distincts.',
    items: [
      { label: 'Votre traitement', title: 'Les soins initiaux sont payés par le patient', text: 'Le patient paie le traitement convenu. Cette page ne promet pas le remboursement de cette facture initiale.' },
      { label: 'Conditions écrites de la clinique', title: 'La garantie clinique n’est pas une assurance', text: 'La clinique évalue le problème et corrige ce qui relève directement de sa responsabilité selon ses conditions écrites de complication et de garantie.' },
      { label: 'Uniquement via un assureur agréé', title: 'L’assurance complication doit être distincte', text: 'Seul un véritable contrat d’un assureur agréé peut couvrir des coûts externes précisément définis. Durée, pays, plafonds, preuves et exclusions doivent y figurer.' },
    ],
    note: 'Ce prototype ne propose ni ne promet actuellement d’assurance complication distincte. Un produit ne peut être nommé qu’après vérification écrite de l’assureur, du contrat et de sa distribution transfrontalière.',
  },
  handoutEyebrow: 'À emporter et à expliquer', handoutTitle: 'Votre guide personnel d’une page.',
  handoutIntro: 'La clinique complète cette fiche pour votre intervention, l’explique dans une langue comprise et confirme sa réception et sa compréhension.',
  handoutDocumentTitle: 'Les 7 premiers jours après mon traitement',
  handoutFields: ['Nom du patient', 'Intervention et zone traitée', 'Date et heure du traitement', 'Contrôle prévu'],
  handoutPriority: 'Les consignes personnelles de mon dentiste priment toujours sur ce résumé général.',
  contactTitle: 'Mon parcours de contact', contactClinic: 'Numéro vérifié de la clinique et solution de secours : à compléter avant le traitement.', contactEmergency: 'Urgence médicale en Géorgie : appeler le 112.',
  confirmation: 'Ma signature confirme uniquement que j’ai reçu ce document, qu’il m’a été expliqué oralement et que j’ai pu poser des questions. Elle ne constitue pas une renonciation à mes droits.',
  signatures: ['Patient · signature et date', 'Praticien · signature et date'],
  closing: { eyebrow: 'La clarté d’abord', title: 'Parlez du suivi avant de réserver votre voyage.', text: 'Demandez quels contrôles correspondent à votre plan, quelles conditions s’appliquent et quel numéro utiliser pendant le séjour.', cta: 'Planifier une consultation personnalisée' },
})

const lb = buildCareLocale({
  navLabel: 'Nofleeg & Sécherheet',
  metaTitle: 'Nofleeg & déi éischt 7 Deeg | Batumi Dental Clinic',
  metaDescription: 'Liest, wéi Batumi Dental Clinic Iech virbereet, begleed an onerwaart Beschwerden séier bewäert.',
  footerLine: 'Gutt Fleeg hält nom Behandlungsstull net op.',
  prototypeNote: 'Konzeptprototyp · Noutnummer, Erreechbarkeet, Garantiebedéngungen an e méigleche Versécherungspartner musse virun der Verëffentlechung schrëftlech gepréift ginn.',
  eyebrow: 'Nofleeg · Komplikatiounsfleeg · kloer Ofsproochen',
  heroTitle: 'Gutt virbereet – och no Ärer Behandlung.',
  heroIntro: 'Mir sinn eis bewosst: Zännfleeg verlaangt kloer Informatioun an eng erreechbar Ekipp. Egal ob Dir zu Batumi wunnt oder aus Europa kommt, virun der Behandlung erkläre mir, wat Dir erwaarde kënnt, wéini Dir urufft a wat d’Klinik maache kann, wann d’Heelung anescht verleeft.',
  heroReassurance: 'Net fir Iech Angscht ze maachen, mee fir datt Dir Iech informéiert, virbereet a gutt begleet fillt.',
  supportLine: 'Mir si fir Iech do!',
  ctaPrimary: 'Behandlungsplang beschwätzen', ctaPrint: 'Déi éischt 7 Deeg drécken',
  passport: { ariaLabel: 'Nofleegpass fir déi éischt siwen Deeg', label: 'Ären Nofleegpass', title: 'Déi éischt 7 Deeg', text: 'Perséinlech Uweisungen, e verifizéierte Kontaktwee an eng Kontroll virum Depart.', stamp: 'Erkläert' },
  assuranceLabel: 'Wat Dir virun der Behandlung kritt',
  assurances: [['Am Viraus erkläert', 'Heelung, Risiken a Choixen a klorer Sprooch.'], ['Erreechbar Ekipp', 'E verifizéierten Telefonwee fir dréngend Froen.'], ['Kontroll geplangt', 'Wann ubruecht: eng lescht Kontroll virum Fluch.']],
  journeyEyebrow: 'Fleeg virdrun, wärend an duerno', journeyTitle: 'Esou hëlleft d’Klinik, datt Är Heelung gutt verleeft.',
  journeyIntro: 'Gutt Nofleeg fänkt net eréischt un, wann e Problem entsteet. Si fänkt mat Virbereedung, kloren Uweisungen an Zäit fir Kontrollen un.',
  journeySteps: [
    { when: 'Virun der Behandlung', title: 'Zesumme virbereeden', text: 'Ären Zänndokter erkläert d’Prozedur, perséinlech Risiken, Heelung, Medikamenter, Mondhygiène, Iessen a Reesen. Virun Ärer Zoustëmmung ass Zäit fir Froen.' },
    { when: 'Schrëftlech a mëndlech', title: 'Kloer Uweisunge mathuelen', text: 'Dir kritt Äre perséinlechen Eensäiter „Déi éischt 7 Deeg“ mat Uweisungen, Warnzeechen, Kontaktwee a Kontrolltermin.' },
    { when: 'An der éischter Woch', title: 'Déi klinesch Bewäertung kënnt als éischt', text: 'En Zänndokter triagéiert onerwaart Beschwerden. Eng néideg dréngend Untersuchung oder Stabiliséierung gëtt net duerch eng nach oppe Käschtefro verspéit.' },
    { when: 'Virun der Heemrees', title: 'Lescht Kontroll', text: 'Wann et medezinesch sënnvoll ass, kontrolléiere mir Heelung, Provisorien, Bëss, Medikamenter an déi nächst Schrëtt virum Fluch.' },
    { when: 'No Ärer Heemrees', title: 'Ären Dossier reest mat', text: 'Dir kritt relevant Behandlungsdaten, Biller an Implantat- oder Materialinformatioun fir Ären Zänndokter doheem.' },
  ],
  firstWeekEyebrow: 'Roueg wëssen, wat ze maachen ass', firstWeekTitle: 'Déi éischt 7 Deeg an dräi kloren Niveauen.',
  firstWeekIntro: 'Déi meescht Heelunge verlafen wéi erwaart. Dëse Guide weist, wat normal ka sinn, wéini Dir d’Klinik urufft a wéini Dir direkt Nouthëllef braucht.',
  personalAdvice: 'Är perséinlech, prozedurspezifesch Uweisunge hunn ëmmer Virrang virun den allgemengen Informatiounen op dëser Säit.',
  normal: { tone: 'normal', label: 'Uweisunge befollegen', title: 'Wat zu der Heelung gehéiere kann', intro: 'Jee no Behandlung kënnen an den éischten Deeg optrieden:', items: ['Liicht bis mëttelméisseg, kontrolléierbar Péng oder Empfindlechkeet', 'Begrenzte Schwellung oder e bloe Fleck', 'E liicht Nobludden oder Wonnsekret', 'Zäitlech Empfindlechkeet beim Iessen, Drénken oder Beréieren'], action: 'D’Beschwerde sollten ze kontrolléiere sinn an no an no ofhuelen.' },
  call: { tone: 'call', label: 'Nach de selwechten Dag uruffen', title: 'Loosst eis séier nokucken', intro: 'Mellt Iech fréi, wann de Verlaf ofwäicht oder Dir onsécher sidd:', items: ['Péng, déi no 48–72 Stonnen däitlech zouhëlt oder net kontrolléierbar ass', 'Unhalend oder zouhuelend Schwellung, Féiwer oder Schüttelfrost', 'Eeter, schlechte Goût oder Geroch mat enger Verschlechterung', 'Taubheet oder Kribbelen, dat net besser gëtt', 'E lockert Implantat oder Deel, oder eng gebrach provisoresch Versuergung'], action: 'En Zänndokter entscheet um Telefon, wéi dréngend eng Untersuchung ass.' },
  emergency: { tone: 'emergency', label: 'A Georgien direkt 112 uruffen', title: 'E medezineschen Noutfall waart net', intro: 'Frot direkt lokal Nouthëllef bei:', items: ['Otem- oder Schluckproblemer', 'Séier ausbreedender Schwellung am Gesiicht, Mond oder Hals', 'Schwéierem Krankheetsgefill, Bewosstlosegkeet oder Verwirrung', 'Blutung, déi trotz festem Drock no Uweisung net ophält'], action: 'Rufft als éischt 112 un. Informéiert d’Klinik, soubal et sécher ass.' },
  channelNote: 'Virun der Behandlung gëtt d’Klinik eng verifizéiert Telefonsnummer an e Réckfallkontakt. WhatsApp ass nëmmen zousätzlech an ni den éischten Noutkanal; medezinesch Biller gehéieren an de sécheren Upload.',
  promise: { eyebrow: 'Eis Ofsprooch mat Iech', title: 'Eng Suerg gëtt gelauschtert a klinesch bewäert.', quote: 'Entsteet bannent siwe Kalennerdeeg en onerwaarte Problem, dee mat der Prozedur zesummenhänke kéint, bewäert en Zänndokter d’Drénglechkeet. Néideg stabiliséierend Fleeg gëtt net duerch e Bezuelungsgespréich verspéit. Korrekturen an eiser schrëftlecher Responsabilitéit ginn ouni zousätzlech Klinikskäschte gemaach.', scope: 'Extern Spidol-, Zänndokter-, Apdikt-, Labor-, Rees- an Ënnerkonftskäschte sinn net automatesch abegraff, ausser et gouf am Viraus ausdrécklech schrëftlech ausgemaach.' },
  certainty: {
    eyebrow: 'Garantie a Versécherung', title: 'Dräi Saachen, déi Dir net verwiessele musst.',
    intro: 'Déi ursprénglech Behandlung, d’Responsabilitéit vun der Klinik an eng méiglech extern Versécherung sinn dräi verschidden Ofsproochen.',
    items: [
      { label: 'Är Behandlung', title: 'Déi ursprénglech Fleeg gëtt selwer bezuelt', text: 'De Patient bezilt déi ausgemaachte Behandlung. Dës Säit versprécht keng Remboursement vun där ursprénglecher Rechnung.' },
      { label: 'Schrëftlech Klinikbedéngungen', title: 'Eng Klinikgarantie ass keng Versécherung', text: 'D’Klinik bewäert d’Beschwerden a korrigéiert, wat no de schrëftleche Komplikatiouns- a Garantiebedéngungen direkt an hir Responsabilitéit fält.' },
      { label: 'Nëmme mat engem zougeloossene Versécherer', title: 'Komplikatiounsversécherung ass separat', text: 'Nëmmen eng richteg Police vun engem lizenzéierte Versécherer kann genee definéiert extern Käschte decken. Dauer, Länner, Limiten, Beweiser an Ausname mussen dra stoen.' },
    ],
    note: 'Dëse Prototyp bitt oder versprécht de Moment keng separat Komplikatiounsversécherung. E Produkt däerf eréischt genannt ginn, wann Versécherer, Police a grenziwwerschreidend Verdeelung schrëftlech gepréift sinn.',
  },
  handoutEyebrow: 'Mathuelen a beschwätzen', handoutTitle: 'Äre perséinlechen Eensäiter.',
  handoutIntro: 'D’Klinik fëllt dëst Blat fir Är Behandlung aus, erkläert et an enger Sprooch, déi Dir verstitt, a bestätegt Empfang a Verständnis.',
  handoutDocumentTitle: 'Déi éischt 7 Deeg no menger Behandlung',
  handoutFields: ['Numm vum Patient', 'Behandlung a behandelte Beräich', 'Datum an Zäit', 'Geplangte Kontroll'],
  handoutPriority: 'Déi perséinlech Uweisunge vu mengem Zänndokter hunn ëmmer Virrang virun dësem allgemenge Resumé.',
  contactTitle: 'Mäi Kontaktwee', contactClinic: 'Verifizéiert Kliniknummer a Réckfallkontakt: virun der Behandlung vun der Klinik anzefëllen.', contactEmergency: 'Medezineschen Noutfall a Georgien: 112 uruffen.',
  confirmation: 'Meng Ënnerschrëft bestätegt nëmmen, datt ech dëst Dokument krut, datt et mëndlech erkläert gouf an datt ech Froe stelle konnt. Si ass kee Verzicht op Patientenrechter.',
  signatures: ['Patient · Ënnerschrëft an Datum', 'Behandelnden · Ënnerschrëft an Datum'],
  closing: { eyebrow: 'Kloerheet als éischt', title: 'Schwätzt iwwer d’Nofleeg, ier Dir Är Rees bucht.', text: 'Frot, wéi eng Kontrollen zu Ärem Plang passen, wéi eng Bedéngunge gëllen a wéi eng Nummer Dir wärend Ärem Openthalt benotzt.', cta: 'Eng perséinlech Berodung buchen' },
})

const ka = buildCareLocale({
  navLabel: 'შემდგომი მოვლა და დაცულობა',
  metaTitle: 'შემდგომი მოვლა და პირველი 7 დღე | Batumi Dental Clinic',
  metaDescription: 'გაიგეთ, როგორ გამზადებთ, გიწევთ მხარდაჭერას და სწრაფად აფასებს Batumi Dental Clinic მოულოდნელ ჩივილებს.',
  footerLine: 'კარგი ზრუნვა სამკურნალო სავარძელთან არ მთავრდება.',
  prototypeNote: 'კონცეფციის პროტოტიპი · გამოქვეყნებამდე წერილობით უნდა გადამოწმდეს გადაუდებელი ნომერი, ხელმისაწვდომობა, გარანტიის პირობები და შესაძლო სადაზღვევო პარტნიორი.',
  eyebrow: 'შემდგომი მოვლა · გართულებების მართვა · მკაფიო პირობები',
  heroTitle: 'მზადყოფნა და მხარდაჭერა — მკურნალობამდე და მის შემდეგ.',
  heroIntro: 'ჩვენ ეს კარგად გვესმის: სტომატოლოგიური მოვლა მკაფიო ინფორმაციასა და ხელმისაწვდომ გუნდს მოითხოვს. ბათუმში ცხოვრობთ თუ ევროპიდან ჩამოდიხართ, მკურნალობამდე აგიხსნით, რას ელოდოთ, როდის დარეკოთ და რისი გაკეთება შეუძლია კლინიკას, თუ შეხორცება სხვაგვარად მიმდინარეობს.',
  heroReassurance: 'არა თქვენი შესაშინებლად, არამედ იმისთვის, რომ თავი ინფორმირებულად, მომზადებულად და მხარდაჭერილად იგრძნოთ.',
  supportLine: 'ჩვენ თქვენს გვერდით ვართ!',
  ctaPrimary: 'მკურნალობის გეგმის განხილვა', ctaPrint: 'პირველი 7 დღის დაბეჭდვა',
  passport: { ariaLabel: 'პირველი შვიდი დღის მოვლის პასპორტი', label: 'თქვენი მოვლის პასპორტი', title: 'პირველი 7 დღე', text: 'პერსონალური ინსტრუქციები, გადამოწმებული საკონტაქტო გზა და შემოწმება გამგზავრებამდე.', stamp: 'განხილულია' },
  assuranceLabel: 'რას მიიღებთ მკურნალობამდე',
  assurances: [['წინასწარი ახსნა', 'შეხორცება, რისკები და არჩევანი მარტივ ენაზე.'], ['ხელმისაწვდომი გუნდი', 'გადამოწმებული სატელეფონო გზა გადაუდებელი კითხვებისთვის.'], ['დაგეგმილი შემოწმება', 'საჭიროებისას: ბოლო შემოწმება ფრენამდე.']],
  journeyEyebrow: 'ზრუნვა მანამდე, პროცესში და შემდეგ', journeyTitle: 'როგორ ეხმარება კლინიკა მშვიდ და სწორ აღდგენას.',
  journeyIntro: 'კარგი შემდგომი მოვლა პრობლემის გაჩენისას არ იწყება. ის იწყება მომზადებით, მკაფიო ინსტრუქციებითა და შემოწმებისთვის საკმარისი დროით.',
  journeySteps: [
    { when: 'მკურნალობამდე', title: 'ერთად ვემზადებით', text: 'სტომატოლოგი აგიხსნით პროცედურას, პირად რისკებს, შეხორცებას, მედიკამენტებს, ჰიგიენას, კვებასა და მგზავრობას. თანხმობამდე კითხვებისთვის დრო გექნებათ.' },
    { when: 'წერილობით და ზეპირად', title: 'მკაფიო ინსტრუქცია თან წაგყვებათ', text: 'მიიღებთ პერსონალურ ერთგვერდიან გზამკვლევს „პირველი 7 დღე“, ინსტრუქციებით, საყურადღებო ნიშნებით, საკონტაქტო გზითა და შემოწმების თარიღით.' },
    { when: 'პირველ კვირაში', title: 'პირველ რიგში — კლინიკური შეფასება', text: 'მოულოდნელ ჩივილს სტომატოლოგი ახარისხებს. აუცილებელი გადაუდებელი შეფასება ან სტაბილიზაცია არ გადაიდება მხოლოდ იმიტომ, რომ ხარჯები ჯერ ზუსტდება.' },
    { when: 'სახლში დაბრუნებამდე', title: 'ბოლო შემოწმება', text: 'სამედიცინო საჭიროებისას ფრენამდე ვამოწმებთ შეხორცებას, დროებით კონსტრუქციებს, დაკბენას, მედიკამენტებსა და შემდგომ ნაბიჯებს.' },
    { when: 'დაბრუნების შემდეგ', title: 'დოკუმენტაცია თან მიგაქვთ', text: 'მიიღებთ შესაბამის სამკურნალო მონაცემებს, გამოსახულებებსა და იმპლანტის ან მასალის ინფორმაციას თქვენი ადგილობრივი სტომატოლოგისთვის.' },
  ],
  firstWeekEyebrow: 'მშვიდად იცოდეთ, რა გააკეთოთ', firstWeekTitle: 'პირველი 7 დღე — სამი მკაფიო დონე.',
  firstWeekIntro: 'აღდგენის უმეტესობა მოსალოდნელად მიმდინარეობს. ეს გზამკვლევი გიჩვენებთ, რა შეიძლება იყოს ნორმალური, როდის დარეკოთ კლინიკაში და როდის მოითხოვოთ გადაუდებელი დახმარება.',
  personalAdvice: 'თქვენი პროცედურის პერსონალური გაწერის ინსტრუქციები ყოველთვის უპირატესია ამ გვერდის ზოგად ინფორმაციასთან შედარებით.',
  normal: { tone: 'normal', label: 'დაიცავით ინსტრუქციები', title: 'რა შეიძლება იყოს ნორმალური შეხორცება', intro: 'პროცედურის მიხედვით, პირველ დღეებში შეიძლება იყოს:', items: ['მსუბუქი ან ზომიერი, მართვადი ტკივილი და მგრძნობელობა', 'შეზღუდული შეშუპება ან სილურჯე', 'მცირე სისხლდენა ან ჭრილობიდან მცირე გამონადენი', 'დროებითი მგრძნობელობა ჭამის, სმის ან შეხებისას'], action: 'სიმპტომები მართვადი უნდა იყოს და, როგორც წესი, თანდათან უნდა გაუმჯობესდეს.' },
  call: { tone: 'call', label: 'იმავე დღეს დაუკავშირდით კლინიკას', title: 'სწრაფად შეგაფასებთ', intro: 'ადრე დაგვიკავშირდით, თუ მიმდინარეობა განსხვავებულია ან ეჭვი გაქვთ:', items: ['ტკივილი, რომელიც 48–72 საათის შემდეგ მკვეთრად ძლიერდება ან ვერ კონტროლდება', 'ხანგრძლივი ან მზარდი შეშუპება, ცხელება ან შემცივნება', 'ჩირქი, ცუდი გემო ან სუნი მდგომარეობის გაუარესებასთან ერთად', 'დაბუჟება ან ჩხვლეტა, რომელიც არ უმჯობესდება', 'მორყეული იმპლანტი ან ნაწილი, ან გატეხილი დროებითი კონსტრუქცია'], action: 'სტომატოლოგი ტელეფონით განსაზღვრავს, რამდენად სწრაფად არის საჭირო გამოკვლევა.' },
  emergency: { tone: 'emergency', label: 'საქართველოში დაუყოვნებლივ დარეკეთ 112-ზე', title: 'სამედიცინო გადაუდებელი შემთხვევა ვერ დაიცდის', intro: 'დაუყოვნებლივ მიმართეთ ადგილობრივ გადაუდებელ დახმარებას, თუ გაქვთ:', items: ['სუნთქვის ან ყლაპვის გაძნელება', 'სახის, პირის ან კისრის სწრაფად გავრცელებული შეშუპება', 'მძიმე ავადმყოფობა, გონების დაკარგვა ან დაბნეულობა', 'სისხლდენა, რომელიც ინსტრუქციის მიხედვით მტკიცე ზეწოლის მიუხედავად არ ჩერდება'], action: 'ჯერ დარეკეთ 112-ზე. კლინიკას აცნობეთ, როგორც კი უსაფრთხო იქნება.' },
  channelNote: 'მკურნალობამდე კლინიკა მოგცემთ გადამოწმებულ ნომერსა და სარეზერვო გზას. WhatsApp მხოლოდ დამხმარე არხია და არასოდეს არის პირველი გადაუდებელი არხი; სამედიცინო სურათები უსაფრთხო ატვირთვით იგზავნება.',
  promise: { eyebrow: 'ჩვენი შეთანხმება თქვენთან', title: 'თქვენს ჩივილს მოვუსმენთ და კლინიკურად შევაფასებთ.', quote: 'თუ შვიდი კალენდარული დღის განმავლობაში წარმოიშვა პროცედურასთან შესაძლო კავშირში მყოფი მოულოდნელი პრობლემა, სტომატოლოგი მის გადაუდებლობას შეაფასებს. აუცილებელი სტაბილიზაცია არ გადაიდება გადახდაზე საუბრის გამო. წერილობით ჩვენს პასუხისმგებლობაში შემავალი კორექცია დამატებითი კლინიკის საფასურის გარეშე ჩატარდება.', scope: 'გარე საავადმყოფოს, სტომატოლოგის, აფთიაქის, ლაბორატორიის, მგზავრობისა და საცხოვრებლის ხარჯები ავტომატურად არ შედის, თუ წინასწარ წერილობით სხვაგვარად არ შეთანხმდა.' },
  certainty: {
    eyebrow: 'გარანტია და დაზღვევა', title: 'სამი განსხვავებული შეთანხმება.',
    intro: 'პირველადი მკურნალობა, კლინიკის პასუხისმგებლობა და შესაძლო გარე დაზღვევა სამი სხვადასხვა საკითხია.',
    items: [
      { label: 'თქვენი მკურნალობა', title: 'პირველადი მკურნალობა თვითდაფინანსებულია', text: 'შეთანხმებულ მკურნალობას პაციენტი იხდის. ეს გვერდი თავდაპირველი ანგარიშის ანაზღაურებას არ გპირდებათ.' },
      { label: 'კლინიკის წერილობითი პირობები', title: 'კლინიკის გარანტია დაზღვევა არ არის', text: 'კლინიკა აფასებს ჩივილს და ასწორებს იმას, რაც წერილობითი გართულებისა და გარანტიის პირობებით უშუალოდ მის პასუხისმგებლობაში შედის.' },
      { label: 'მხოლოდ უფლებამოსილი მზღვეველით', title: 'გართულების დაზღვევა ცალკე პროდუქტია', text: 'ზუსტად განსაზღვრული გარე ხარჯები მხოლოდ ლიცენზირებული მზღვეველის ნამდვილ პოლისს შეუძლია დაფაროს. ვადა, ქვეყნები, ლიმიტები, მტკიცებულება და გამონაკლისები პოლისში უნდა ეწეროს.' },
    ],
    note: 'ეს პროტოტიპი ამჟამად ცალკე გართულების დაზღვევას არ გთავაზობთ და არ გპირდებათ. პროდუქტი მხოლოდ მზღვეველის, პოლისისა და საზღვრისპირა დისტრიბუციის წერილობითი გადამოწმების შემდეგ შეიძლება დასახელდეს.',
  },
  handoutEyebrow: 'წაიღეთ და განიხილეთ', handoutTitle: 'თქვენი პერსონალური ერთგვერდიანი გზამკვლევი.',
  handoutIntro: 'კლინიკა ამ ფურცელს თქვენი პროცედურისთვის შეავსებს, გასაგებ ენაზე აგიხსნით და მიღებასა და გაგებას დააფიქსირებს.',
  handoutDocumentTitle: 'ჩემი მკურნალობის შემდეგ პირველი 7 დღე',
  handoutFields: ['პაციენტის სახელი', 'პროცედურა და დამუშავებული არე', 'მკურნალობის თარიღი და დრო', 'დაგეგმილი შემოწმება'],
  handoutPriority: 'ჩემი სტომატოლოგის პერსონალური ინსტრუქციები ყოველთვის უპირატესია ამ ზოგად შეჯამებაზე.',
  contactTitle: 'ჩემი საკონტაქტო გზა', contactClinic: 'კლინიკის გადამოწმებული ნომერი და სარეზერვო გზა: კლინიკამ შეავსოს მკურნალობამდე.', contactEmergency: 'სამედიცინო გადაუდებელი შემთხვევა საქართველოში: დარეკეთ 112-ზე.',
  confirmation: 'ჩემი ხელმოწერა მხოლოდ ადასტურებს, რომ დოკუმენტი მივიღე, ზეპირად ამიხსნეს და კითხვების დასმა შემეძლო. ეს პაციენტის უფლებებზე უარი არ არის.',
  signatures: ['პაციენტი · ხელმოწერა და თარიღი', 'მკურნალი · ხელმოწერა და თარიღი'],
  closing: { eyebrow: 'ჯერ სიცხადე', title: 'შემდგომი მოვლა მოგზაურობის დაჯავშნამდე განიხილეთ.', text: 'იკითხეთ, რომელი შემოწმებები შეესაბამება თქვენს გეგმას, რომელი წერილობითი პირობები მოქმედებს და რომელ ნომერს გამოიყენებთ ყოფნისას.', cta: 'პერსონალური კონსულტაციის დაგეგმვა' },
})

export const aftercareContent = { nl, de, fr, lb, en, ka }
