export const diagnosticsContent = {
  nl: {
    eyebrow: 'Röntgenkamer & diagnostiek',
    title: 'Goede tandheelkunde begint met precies weten wat u ziet.',
    text: 'De röntgenkamer verdient een zichtbare plaats in de kliniek én op de website. Per kliniek tonen we alleen de werkelijk aanwezige en geverifieerde apparatuur, opnametypen en veiligheidsinformatie.',
    imageAlt: 'Tandheelkundige röntgenbeelden worden samen met een patiënt besproken',
    status: 'Apparatuur, merk, model en beschikbare opnametypen worden vóór publicatie door de kliniek bevestigd.',
    principles: [
      ['Alleen wanneer nodig', 'Een opname volgt op een klinische vraag en wordt niet automatisch gemaakt.'],
      ['Plannen met meer zekerheid', 'Beelden ondersteunen diagnose, behandelkeuze en de bespreking van risico’s.'],
      ['Samen bekijken', 'De tandarts legt uit wat zichtbaar is en wat dit voor uw behandelplan betekent.'],
    ],
    uploadEyebrow: 'Heeft u al beelden?',
    uploadText: 'Stuur recente röntgenfoto’s of scans veilig mee voor de eerste beoordeling.',
    uploadCta: 'Röntgenfoto’s veilig versturen',
  },
  de: {
    eyebrow: 'Röntgenraum & Diagnostik',
    title: 'Gute Zahnmedizin beginnt damit, genau zu wissen, was man sieht.',
    text: 'Der Röntgenraum verdient einen sichtbaren Platz in der Klinik und auf der Website. Pro Klinik zeigen wir nur tatsächlich vorhandene und verifizierte Geräte, Aufnahmearten und Sicherheitsinformationen.',
    imageAlt: 'Zahnärztliche Röntgenbilder werden gemeinsam mit einem Patienten besprochen',
    status: 'Gerät, Marke, Modell und verfügbare Aufnahmearten werden vor der Veröffentlichung von der Klinik bestätigt.',
    principles: [
      ['Nur wenn erforderlich', 'Eine Aufnahme folgt einer klinischen Fragestellung und wird nicht automatisch erstellt.'],
      ['Sicherer planen', 'Bilder unterstützen Diagnose, Behandlungswahl und die Besprechung von Risiken.'],
      ['Gemeinsam ansehen', 'Der Zahnarzt erklärt, was zu sehen ist und was es für Ihren Behandlungsplan bedeutet.'],
    ],
    uploadEyebrow: 'Sie haben bereits Aufnahmen?',
    uploadText: 'Senden Sie aktuelle Röntgenbilder oder Scans sicher für die erste Beurteilung.',
    uploadCta: 'Röntgenbilder sicher senden',
  },
  fr: {
    eyebrow: 'Salle de radiologie & diagnostic',
    title: 'Une bonne dentisterie commence par voir avec précision.',
    text: 'La salle de radiologie mérite une place visible dans la clinique comme sur le site. Pour chaque clinique, seuls les équipements, types d’examens et informations de sécurité réellement disponibles et vérifiés sont présentés.',
    imageAlt: 'Des radiographies dentaires sont expliquées à un patient',
    status: 'L’équipement, la marque, le modèle et les examens disponibles sont confirmés par la clinique avant publication.',
    principles: [
      ['Seulement si nécessaire', 'Un examen répond à une question clinique et n’est jamais réalisé automatiquement.'],
      ['Planifier avec plus de certitude', 'Les images soutiennent le diagnostic, le choix du soin et l’explication des risques.'],
      ['Regarder ensemble', 'Le dentiste explique ce qui est visible et ce que cela signifie pour votre plan.'],
    ],
    uploadEyebrow: 'Vous avez déjà des images ?',
    uploadText: 'Envoyez vos radiographies ou scanners récents de façon sécurisée pour une première évaluation.',
    uploadCta: 'Envoyer les radiographies en sécurité',
  },
  lb: {
    eyebrow: 'Röntgenraum & Diagnostik',
    title: 'Gutt Zännmedezin fänkt domat un, genee ze wëssen, wat ee gesäit.',
    text: 'De Röntgenraum verdéngt eng sichtbar Plaz an der Klinik an op der Websäit. Fir all Klinik weise mir nëmmen déi wierklech verfügbar a verifizéiert Apparater, Opnamzorten a Sécherheetsinformatiounen.',
    imageAlt: 'Zänn-Röntgenopname gi mat engem Patient zesumme gekuckt',
    status: 'Apparat, Mark, Modell an verfügbar Opnamzorte gi virun der Publikatioun vun der Klinik confirméiert.',
    principles: [
      ['Nëmme wann néideg', 'Eng Opnam beäntwert eng klinesch Fro a gëtt net automatesch gemaach.'],
      ['Méi sécher plangen', 'Biller ënnerstëtzen Diagnos, Behandlungswahl an d’Erklärung vu Risiken.'],
      ['Zesumme kucken', 'Den Zänndokter erkläert, wat ze gesinn ass a wat dat fir Äre Plang bedeit.'],
    ],
    uploadEyebrow: 'Hutt Dir scho Biller?',
    uploadText: 'Schéckt rezent Röntgenopnamen oder Scans sécher fir déi éischt Bewäertung.',
    uploadCta: 'Röntgenopname sécher schécken',
  },
  en: {
    eyebrow: 'Imaging room & diagnostics',
    title: 'Good dentistry starts with knowing exactly what you can see.',
    text: 'The imaging room deserves a visible place in the clinic and on its website. Each installation shows only the equipment, scan types and safety information that the clinic actually has and has verified.',
    imageAlt: 'Dental X-rays are reviewed together with a patient',
    status: 'Equipment, brand, model and available scan types are confirmed by the clinic before publication.',
    principles: [
      ['Only when needed', 'An image answers a clinical question and is not taken automatically.'],
      ['Plan with more certainty', 'Images support diagnosis, treatment choice and an open discussion of risk.'],
      ['Review it together', 'The dentist explains what is visible and what it means for your treatment plan.'],
    ],
    uploadEyebrow: 'Already have images?',
    uploadText: 'Send recent X-rays or scans securely for an initial review.',
    uploadCta: 'Send X-rays securely',
  },
  ka: {
    eyebrow: 'რენტგენის ოთახი და დიაგნოსტიკა',
    title: 'კარგი სტომატოლოგია იწყება იმით, რომ ზუსტად ვიცოდეთ, რას ვხედავთ.',
    text: 'რენტგენის ოთახი თვალსაჩინო უნდა იყოს როგორც კლინიკაში, ისე ვებსაიტზე. თითოეული კლინიკისთვის ვაჩვენებთ მხოლოდ რეალურად არსებულ და გადამოწმებულ აპარატურას, კვლევის ტიპებსა და უსაფრთხოების ინფორმაციას.',
    imageAlt: 'სტომატოლოგიური რენტგენის სურათები პაციენტთან ერთად განიხილება',
    status: 'აპარატურა, ბრენდი, მოდელი და ხელმისაწვდომი კვლევები გამოქვეყნებამდე კლინიკის მიერ დასტურდება.',
    principles: [
      ['მხოლოდ საჭიროებისას', 'კვლევა კონკრეტულ კლინიკურ კითხვას პასუხობს და ავტომატურად არ ტარდება.'],
      ['უფრო ზუსტი დაგეგმვა', 'სურათები ეხმარება დიაგნოზს, მკურნალობის არჩევასა და რისკების განხილვას.'],
      ['ერთად განხილვა', 'სტომატოლოგი აგიხსნით, რა ჩანს და რას ნიშნავს ეს თქვენი მკურნალობის გეგმისთვის.'],
    ],
    uploadEyebrow: 'უკვე გაქვთ სურათები?',
    uploadText: 'პირველადი შეფასებისთვის უსაფრთხოდ გამოგზავნეთ ახალი რენტგენი ან სკანი.',
    uploadCta: 'რენტგენის უსაფრთხოდ გაგზავნა',
  },
}
