export const experienceContent = {
  nl: {
    navTeam: 'Team', navPatients: 'Patiënten', navAftercare: 'Nazorg',
    motionLabel: 'Wat u van deze kliniek mag verwachten',
    startMotion: 'Beweging starten',
    pauseMotion: 'Beweging pauzeren',
    priceEyebrow: 'Prijzen zonder verrassingen',
    priceTitle: 'Een behandelplan dat ook financieel duidelijk is.',
    priceText: 'Bekijk de actuele kliniekprijzen per behandeling. Na onderzoek ontvangt u een gespecificeerd voorstel met materiaalkeuzes, inbegrepen onderdelen en het verwachte aantal bezoeken.',
    priceTemplateText: 'Bekijk hoe de eigen kliniektarieven straks per behandeling worden opgebouwd. Alleen bevestigde GEL-prijzen, materialen, inbegrepen onderdelen en controledatums worden gepubliceerd.',
    priceCta: 'Bekijk de prijslijst',
    priceNote: 'Alleen door de kliniek bevestigde prijzen worden gepubliceerd.',
  },
  de: {
    navTeam: 'Team', navPatients: 'Patienten', navAftercare: 'Nachsorge',
    motionLabel: 'Was Sie von dieser Klinik erwarten dürfen',
    startMotion: 'Bewegung starten',
    pauseMotion: 'Bewegung pausieren',
    priceEyebrow: 'Preise ohne Überraschungen',
    priceTitle: 'Ein Behandlungsplan, der auch finanziell klar ist.',
    priceText: 'Sehen Sie die aktuellen Klinikpreise je Behandlung. Nach der Untersuchung erhalten Sie einen aufgeschlüsselten Vorschlag mit Materialoptionen, enthaltenen Leistungen und der erwarteten Anzahl von Besuchen.',
    priceTemplateText: 'Sehen Sie, wie die klinikeigenen Preise künftig je Behandlung aufgebaut werden. Veröffentlicht werden nur bestätigte GEL-Preise, Materialien, Leistungen und Prüfdaten.',
    priceCta: 'Preisliste ansehen',
    priceNote: 'Veröffentlicht werden nur von der Klinik bestätigte Preise.',
  },
  fr: {
    navTeam: 'Équipe', navPatients: 'Patients', navAftercare: 'Suivi',
    motionLabel: 'Ce que vous pouvez attendre de cette clinique',
    startMotion: 'Démarrer le mouvement',
    pauseMotion: 'Mettre le mouvement en pause',
    priceEyebrow: 'Des prix sans surprise',
    priceTitle: 'Un plan de traitement également clair sur le plan financier.',
    priceText: 'Consultez les tarifs actuels de la clinique par traitement. Après l’examen, vous recevez une proposition détaillée indiquant les matériaux, les éléments inclus et le nombre de visites prévu.',
    priceTemplateText: 'Découvrez comment les tarifs propres à la clinique seront structurés par soin. Seuls les prix GEL, matériaux, inclusions et dates de contrôle confirmés seront publiés.',
    priceCta: 'Voir les tarifs',
    priceNote: 'Seuls les tarifs confirmés par la clinique sont publiés.',
  },
  lb: {
    navTeam: 'Ekipp', navPatients: 'Patienten', navAftercare: 'Nofleeg',
    motionLabel: 'Wat Dir vun dëser Klinik erwaarde kënnt',
    startMotion: 'Beweegung starten',
    pauseMotion: 'Beweegung pauséieren',
    priceEyebrow: 'Präisser ouni Iwwerraschungen',
    priceTitle: 'E Behandlungsplang, deen och finanziell kloer ass.',
    priceText: 'Kuckt déi aktuell Klinikpräisser pro Behandlung. No der Ënnersichung kritt Dir eng detailléiert Propositioun mat Materialoptiounen, abegraffene Leeschtungen an der erwaarter Zuel vu Visitten.',
    priceTemplateText: 'Kuckt, wéi déi eege Klinikpräisser pro Behandlung opgebaut ginn. Nëmme confirméiert GEL-Präisser, Materialien, Leeschtungen a Kontrolldatume gi publizéiert.',
    priceCta: 'Präislëscht kucken',
    priceNote: 'Nëmme vun der Klinik confirméiert Präisser gi publizéiert.',
  },
  en: {
    navTeam: 'Team', navPatients: 'Patients', navAftercare: 'Aftercare',
    motionLabel: 'What you may expect from this clinic',
    startMotion: 'Start motion',
    pauseMotion: 'Pause motion',
    priceEyebrow: 'Prices without surprises',
    priceTitle: 'A treatment plan that is financially clear too.',
    priceText: 'View current clinic fees by treatment. After examination, you receive an itemised proposal covering material options, inclusions and the expected number of visits.',
    priceTemplateText: 'See how this clinic’s own fees will be structured by treatment. Only confirmed GEL prices, materials, inclusions and verification dates will be published.',
    priceCta: 'View the price list',
    priceNote: 'Only prices confirmed by the clinic are published.',
  },
  ka: {
    navTeam: 'გუნდი', navPatients: 'პაციენტები', navAftercare: 'შემდგომი მოვლა',
    motionLabel: 'რას უნდა ელოდოთ ამ კლინიკისგან',
    startMotion: 'მოძრაობის ჩართვა',
    pauseMotion: 'მოძრაობის შეჩერება',
    priceEyebrow: 'ფასი მოულოდნელობების გარეშე',
    priceTitle: 'მკურნალობის გეგმა, რომელიც ფინანსურადაც გასაგებია.',
    priceText: 'იხილეთ კლინიკის მიმდინარე ფასები მკურნალობის მიხედვით. გამოკვლევის შემდეგ მიიღებთ დეტალურ შეთავაზებას მასალების ვარიანტებით, ჩართული მომსახურებებითა და ვიზიტების მოსალოდნელი რაოდენობით.',
    priceTemplateText: 'ნახეთ, როგორ დალაგდება ამ კლინიკის საკუთარი ფასები მკურნალობის მიხედვით. გამოქვეყნდება მხოლოდ დადასტურებული GEL ფასები, მასალები, ჩართული მომსახურება და შემოწმების თარიღები.',
    priceCta: 'ფასების ნახვა',
    priceNote: 'ქვეყნდება მხოლოდ კლინიკის მიერ დადასტურებული ფასები.',
  },
}
