export const interfaceContent = {
  nl: {
    audience: 'Voor lokale én internationale patiënten',
    serviceGroups: ['Dagelijkse tandzorg', 'Herstel & vervanging', 'Stand & uitstraling'], allTreatments: 'Alle behandelingen', serviceMenuIntro: 'Complete tandzorg voor iedere levensfase.',
    principlesLabel: 'Waar onze zorg voor staat', principles: ['Ruimte', 'Vertrouwen', 'Informatie', 'Openheid', 'Zorg', 'Duidelijkheid'],
    bookNow: 'Plan een afspraak', whatsappPrompt: 'Stel uw vraag via WhatsApp',
    urgent: 'Pijn of spoed? Neem direct contact op',
    localPathEyebrow: 'Batumi · Georgië', localPathTitle: 'Ik woon in Georgië', localPathText: 'Reguliere tandzorg en snelle afspraken in Batumi.', localPathCta: 'Bekijk behandelingen',
    travelPathEyebrow: 'Internationale zorg', travelPathTitle: 'Ik reis naar Batumi', travelPathText: 'Vooronderzoek vanuit huis, planning binnen uw verblijf en controle vóór vertrek.', travelPathCta: 'Bekijk uw 21 dagen',
    appointment: 'Afspraak',
    whatsapp: 'WhatsApp',
    heroMediaLabel: 'Persoonlijke uitleg vóór iedere behandeling',
    heroMediaNote: 'Conceptfotografie · vervang door echte kliniekbeelden vóór publicatie',
    careFeatureEyebrow: 'Zorg die verder kijkt',
    careFeatureTitle: 'Wij zijn er voor jou. Ook na de behandeling.',
    careFeatureText: 'Heldere instructies, een controle vóór vertrek en een concreet protocol voor de eerste zeven dagen.',
    careFeatureCta: 'Bekijk nazorg & zekerheid',
    galleryLabel: 'Een rustige, moderne behandelomgeving',
    galleryCaption: 'Diagnostiek, uitleg en behandeling in één zorgvuldig gepland traject.',
    whatsappTitle: 'Eerst even overleggen via WhatsApp?',
    whatsappText: 'Gebruik WhatsApp voor algemene vragen over een intake, planning of verblijf. Voor spoed gebruikt u het door de kliniek verstrekte noodnummer; medische beelden worden pas gedeeld nadat de beveiligde upload is aangesloten.',
    whatsappAction: 'WhatsApp-koppeling bekijken',
    whatsappStatus: 'Prototype: het officiële klinieknummer moet nog worden geverifieerd en gekoppeld.',
    uploadTitle: 'Foto’s of röntgenbeelden toevoegen',
    uploadText: 'Voeg foto’s, röntgenbeelden, PDF of DICOM toe. In deze besloten beoordelingsversie worden ze niet openbaar opgeslagen en krijgen ze een willekeurige referentie.',
    uploadChoose: 'Kies bestanden',
    uploadHelp: 'Maximaal 5 bestanden · JPG, PNG, WebP, PDF of DICOM · maximaal 10 MB per bestand en 25 MB totaal',
    uploadSelectionError: 'Een of meer bestanden zijn niet toegevoegd. Gebruik alleen de genoemde formaten, maximaal 5 bestanden, 10 MB per bestand en 25 MB totaal.',
    uploadRemove: 'Verwijderen',
    uploadConsent: 'Ik bevestig dat deze bestanden van mij zijn of dat ik ze mag delen.',
    healthConsent: 'Mijn toelichting en bestanden kunnen gezondheidsgegevens bevatten. Ik geef toestemming voor de beschreven privéverwerking.', privacyLink: 'Lees de privacyuitleg.',
    intakeSending: 'Privé opslaan…', intakeError: 'Opslaan is niet gelukt. Controleer de gegevens of probeer het later opnieuw.',
    appointmentSuccessTitle: 'Uw aanvraag is privé opgeslagen.', appointmentSuccessText: 'Bewaar de referentie hieronder. Een afspraak is pas bevestigd na persoonlijk contact met de kliniek.',
    uploadSuccessTitle: 'Uw beelden zijn privé opgeslagen.', uploadSuccessText: 'Bewaar de referentie hieronder en noem deze bij uw contact met de kliniek. Dit is nog geen diagnose of bevestigde afspraak.',
    referenceLabel: 'Uw referentie', deleteIntake: 'Verwijder mijn aanvraag en bestanden', intakeDeleting: 'Verwijderen…', intakeDeletedTitle: 'Uw gegevens zijn verwijderd.', intakeDeletedText: 'De aanvraag en eventuele bestanden zijn uit de privéopslag verwijderd.', deleteError: 'Verwijderen lukte niet. Bewaar de referentie en neem contact op met de kliniek.',
    photoAltConsultation: 'Tandarts bespreekt een behandelplan met een patiënt in een moderne behandelkamer',
    photoAltCare: 'Tandheelkundig team behandelt een patiënt in een heldere klinische ruimte',
    photoAltClinic: 'Moderne tandartsstoel en apparatuur in een rustige behandelkamer',
    photoAltPlanning: 'Bespreking van tandheelkundige röntgenbeelden op een beeldscherm',
  },
  de: {
    audience: 'Für lokale und internationale Patienten', appointment: 'Termin', whatsapp: 'WhatsApp',
    serviceGroups: ['Allgemeine Zahnmedizin', 'Wiederherstellung & Zahnersatz', 'Zahnstellung & Ästhetik'], allTreatments: 'Alle Behandlungen', serviceMenuIntro: 'Umfassende Zahnmedizin für jede Lebensphase.',
    principlesLabel: 'Wofür unsere Versorgung steht', principles: ['Raum', 'Vertrauen', 'Information', 'Offenheit', 'Fürsorge', 'Klarheit'],
    bookNow: 'Termin vereinbaren', whatsappPrompt: 'Frage über WhatsApp stellen',
    urgent: 'Schmerzen oder Notfall? Direkt Kontakt aufnehmen',
    localPathEyebrow: 'Batumi · Georgien', localPathTitle: 'Ich lebe in Georgien', localPathText: 'Regelmäßige Zahnmedizin und zeitnahe Termine in Batumi.', localPathCta: 'Behandlungen ansehen',
    travelPathEyebrow: 'Internationale Versorgung', travelPathTitle: 'Ich reise nach Batumi', travelPathText: 'Vorprüfung von zu Hause, Planung während Ihres Aufenthalts und Kontrolle vor der Abreise.', travelPathCta: 'Ihre 21 Tage ansehen',
    heroMediaLabel: 'Persönliche Erklärung vor jeder Behandlung', heroMediaNote: 'Konzeptfotografie · vor Veröffentlichung durch echte Klinikbilder ersetzen',
    careFeatureEyebrow: 'Versorgung, die weiterdenkt', careFeatureTitle: 'Wir sind für Sie da. Auch nach der Behandlung.', careFeatureText: 'Klare Anweisungen, eine Kontrolle vor der Abreise und ein konkretes Protokoll für die ersten sieben Tage.', careFeatureCta: 'Nachsorge & Sicherheit ansehen',
    galleryLabel: 'Eine ruhige, moderne Behandlungsumgebung', galleryCaption: 'Diagnostik, Erklärung und Behandlung in einem sorgfältig geplanten Ablauf.',
    whatsappTitle: 'Erst kurz über WhatsApp sprechen?', whatsappText: 'WhatsApp ist für allgemeine Fragen zu Erstgespräch, Planung oder Aufenthalt. Im Notfall nutzen Sie die von der Klinik angegebene Notfallnummer; medizinische Bilder werden erst nach Aktivierung des sicheren Uploads geteilt.', whatsappAction: 'WhatsApp-Verbindung ansehen', whatsappStatus: 'Prototyp: Die offizielle Kliniknummer muss noch geprüft und verknüpft werden.',
    uploadTitle: 'Fotos oder Röntgenbilder hinzufügen', uploadText: 'Fügen Sie Fotos, Röntgenbilder, PDF oder DICOM hinzu. In dieser geschlossenen Prüfversion werden sie nicht öffentlich gespeichert und erhalten eine zufällige Referenz.', uploadChoose: 'Dateien auswählen', uploadHelp: 'Maximal 5 Dateien · JPG, PNG, WebP, PDF oder DICOM · maximal 10 MB je Datei und 25 MB insgesamt', uploadSelectionError: 'Eine oder mehrere Dateien wurden nicht hinzugefügt. Verwenden Sie nur die genannten Formate, höchstens 5 Dateien, 10 MB je Datei und 25 MB insgesamt.', uploadRemove: 'Entfernen',
    uploadConsent: 'Ich bestätige, dass diese Dateien mir gehören oder dass ich sie teilen darf.',
    healthConsent: 'Meine Erläuterung und Dateien können Gesundheitsdaten enthalten. Ich stimme der beschriebenen privaten Verarbeitung zu.', privacyLink: 'Datenschutzhinweis lesen.',
    intakeSending: 'Privat speichern…', intakeError: 'Speichern fehlgeschlagen. Prüfen Sie die Angaben oder versuchen Sie es später erneut.',
    appointmentSuccessTitle: 'Ihre Anfrage wurde privat gespeichert.', appointmentSuccessText: 'Bewahren Sie die Referenz unten auf. Ein Termin ist erst nach persönlicher Bestätigung durch die Klinik verbindlich.',
    uploadSuccessTitle: 'Ihre Bilder wurden privat gespeichert.', uploadSuccessText: 'Bewahren Sie die Referenz auf und nennen Sie sie beim Kontakt mit der Klinik. Dies ist noch keine Diagnose oder Terminbestätigung.',
    referenceLabel: 'Ihre Referenz', deleteIntake: 'Anfrage und Dateien löschen', intakeDeleting: 'Wird gelöscht…', intakeDeletedTitle: 'Ihre Daten wurden gelöscht.', intakeDeletedText: 'Die Anfrage und alle Dateien wurden aus dem privaten Speicher entfernt.', deleteError: 'Löschen fehlgeschlagen. Bewahren Sie die Referenz auf und kontaktieren Sie die Klinik.',
    photoAltConsultation: 'Zahnarzt bespricht in einem modernen Behandlungsraum einen Behandlungsplan mit einem Patienten', photoAltCare: 'Zahnärztliches Team behandelt einen Patienten in einer hellen Klinik', photoAltClinic: 'Moderner Behandlungsstuhl und Ausstattung in einem ruhigen Behandlungsraum', photoAltPlanning: 'Besprechung zahnärztlicher Röntgenbilder auf einem Bildschirm',
  },
  fr: {
    audience: 'Pour les patients locaux et internationaux', appointment: 'Rendez-vous', whatsapp: 'WhatsApp',
    serviceGroups: ['Soins dentaires courants', 'Restauration & remplacement', 'Alignement & esthétique'], allTreatments: 'Tous les traitements', serviceMenuIntro: 'Des soins dentaires complets à chaque âge.',
    principlesLabel: 'Ce qui guide nos soins', principles: ['Espace', 'Confiance', 'Information', 'Transparence', 'Attention', 'Clarté'],
    bookNow: 'Prendre rendez-vous', whatsappPrompt: 'Poser une question sur WhatsApp',
    urgent: 'Douleur ou urgence ? Contactez-nous directement',
    localPathEyebrow: 'Batoumi · Géorgie', localPathTitle: 'Je vis en Géorgie', localPathText: 'Soins dentaires courants et rendez-vous rapides à Batoumi.', localPathCta: 'Voir les traitements',
    travelPathEyebrow: 'Soins internationaux', travelPathTitle: 'Je viens à Batoumi', travelPathText: 'Pré-évaluation à distance, soins organisés pendant le séjour et contrôle avant le départ.', travelPathCta: 'Voir vos 21 jours',
    heroMediaLabel: 'Une explication personnelle avant chaque traitement', heroMediaNote: 'Photographie de concept · à remplacer par de vraies images de la clinique avant publication',
    careFeatureEyebrow: 'Des soins qui vont plus loin', careFeatureTitle: 'Nous sommes là pour vous. Aussi après le traitement.', careFeatureText: 'Des consignes claires, un contrôle avant le départ et un protocole concret pour les sept premiers jours.', careFeatureCta: 'Voir le suivi & la sécurité',
    galleryLabel: 'Un environnement de soins calme et moderne', galleryCaption: 'Diagnostic, explications et traitement dans un parcours soigneusement planifié.',
    whatsappTitle: 'Échanger d’abord sur WhatsApp ?', whatsappText: 'Utilisez WhatsApp pour les questions générales sur la consultation, le planning ou le séjour. En urgence, utilisez le numéro fourni par la clinique; les images médicales ne seront partagées qu’après activation de l’envoi sécurisé.', whatsappAction: 'Voir la connexion WhatsApp', whatsappStatus: 'Prototype : le numéro officiel de la clinique doit encore être vérifié et connecté.',
    uploadTitle: 'Ajouter des photos ou radiographies', uploadText: 'Ajoutez des photos, radiographies, PDF ou DICOM. Dans cette version d’évaluation privée, ils ne sont pas stockés publiquement et reçoivent une référence aléatoire.', uploadChoose: 'Choisir des fichiers', uploadHelp: '5 fichiers maximum · JPG, PNG, WebP, PDF ou DICOM · 10 Mo par fichier et 25 Mo au total', uploadSelectionError: 'Un ou plusieurs fichiers n’ont pas été ajoutés. Utilisez uniquement les formats indiqués, avec un maximum de 5 fichiers, 10 Mo par fichier et 25 Mo au total.', uploadRemove: 'Supprimer',
    uploadConsent: 'Je confirme que ces fichiers m’appartiennent ou que je suis autorisé à les partager.',
    healthConsent: 'Mon explication et mes fichiers peuvent contenir des données de santé. J’accepte le traitement privé décrit.', privacyLink: 'Lire l’information confidentialité.',
    intakeSending: 'Enregistrement privé…', intakeError: 'L’enregistrement a échoué. Vérifiez les informations ou réessayez plus tard.',
    appointmentSuccessTitle: 'Votre demande a été enregistrée en privé.', appointmentSuccessText: 'Conservez la référence ci-dessous. Le rendez-vous ne sera confirmé qu’après un contact personnel avec la clinique.',
    uploadSuccessTitle: 'Vos images ont été enregistrées en privé.', uploadSuccessText: 'Conservez la référence et indiquez-la lors de votre contact avec la clinique. Ceci ne constitue ni diagnostic ni rendez-vous confirmé.',
    referenceLabel: 'Votre référence', deleteIntake: 'Supprimer ma demande et mes fichiers', intakeDeleting: 'Suppression…', intakeDeletedTitle: 'Vos données ont été supprimées.', intakeDeletedText: 'La demande et les fichiers éventuels ont été retirés du stockage privé.', deleteError: 'La suppression a échoué. Conservez la référence et contactez la clinique.',
    photoAltConsultation: 'Dentiste expliquant un plan de traitement à un patient dans une salle moderne', photoAltCare: 'Équipe dentaire soignant un patient dans un espace clinique lumineux', photoAltClinic: 'Fauteuil et équipement dentaires modernes dans une salle de soins calme', photoAltPlanning: 'Discussion de radiographies dentaires sur un écran',
  },
  lb: {
    audience: 'Fir lokal an international Patienten', appointment: 'Rendez-vous', whatsapp: 'WhatsApp',
    serviceGroups: ['Alldeeglech Zännfleeg', 'Restauratioun & Ersatz', 'Zännstellung & Ästhetik'], allTreatments: 'All Behandlungen', serviceMenuIntro: 'Komplett Zännfleeg fir all Liewensphas.',
    principlesLabel: 'Dofir steet eis Fleeg', principles: ['Raum', 'Vertrauen', 'Informatioun', 'Oppenheet', 'Fleeg', 'Kloerheet'],
    bookNow: 'Rendez-vous ufroen', whatsappPrompt: 'Fro iwwer WhatsApp stellen',
    urgent: 'Péng oder Noutfall? Direkt Kontakt ophuelen',
    localPathEyebrow: 'Batumi · Georgien', localPathTitle: 'Ech wunnen a Georgien', localPathText: 'Regelméisseg Zännfleeg a séier Rendez-vousen zu Batumi.', localPathCta: 'Behandlungen ukucken',
    travelPathEyebrow: 'International Zännfleeg', travelPathTitle: 'Ech reesen op Batumi', travelPathText: 'Virbewäertung vun doheem, Planung wärend Ärem Openthalt a Kontroll virum Depart.', travelPathCta: 'Är 21 Deeg ukucken',
    heroMediaLabel: 'Perséinlech Erklärung virun all Behandlung', heroMediaNote: 'Konzeptfotoen · virun der Publikatioun duerch richteg Klinikbiller ersetzen',
    careFeatureEyebrow: 'Fleeg, déi méi wäit denkt', careFeatureTitle: 'Mir si fir Iech do. Och no der Behandlung.', careFeatureText: 'Kloer Uweisungen, eng Kontroll virum Depart an e konkrete Protokoll fir déi éischt siwen Deeg.', careFeatureCta: 'Nofleeg & Sécherheet kucken',
    galleryLabel: 'Eng roueg, modern Behandlungsëmgebung', galleryCaption: 'Diagnostik, Erklärung a Behandlung an engem suergfälteg geplangten Oflaf.',
    whatsappTitle: 'Als éischt kuerz iwwer WhatsApp schwätzen?', whatsappText: 'WhatsApp ass fir allgemeng Froen iwwer Intake, Planung oder Openthalt. Am Noutfall benotzt Dir d’Nummer vun der Klinik; medezinesch Biller ginn eréischt nom Aktivéiere vum sécheren Upload gedeelt.', whatsappAction: 'WhatsApp-Verbindung kucken', whatsappStatus: 'Prototyp: Déi offiziell Kliniknummer muss nach verifizéiert a verbonne ginn.',
    uploadTitle: 'Fotoen oder Röntgebiller bäifügen', uploadText: 'Füügt Fotoen, Röntgebiller, PDF oder DICOM bäi. An dëser zouener Testversioun gi se net ëffentlech gespäichert a kréien eng zoufälleg Referenz.', uploadChoose: 'Dateien auswielen', uploadHelp: 'Maximal 5 Dateien · JPG, PNG, WebP, PDF oder DICOM · maximal 10 MB pro Datei a 25 MB am Ganzen', uploadSelectionError: 'Eng oder méi Dateie goufen net bäigefüügt. Benotzt nëmmen déi genannte Formater, maximal 5 Dateien, 10 MB pro Datei a 25 MB am Ganzen.', uploadRemove: 'Ewechhuelen',
    uploadConsent: 'Ech confirméieren, datt dës Dateien mir gehéieren oder datt ech se deele däerf.',
    healthConsent: 'Meng Erklärung an Dateie kënne Gesondheetsdonnéeën enthalen. Ech stëmmen der beschriwwener privater Veraarbechtung zou.', privacyLink: 'Dateschutzerklärung liesen.',
    intakeSending: 'Privat späicheren…', intakeError: 'D’Späichere war net méiglech. Kontrolléiert d’Donnéeën oder probéiert et méi spéit nach eng Kéier.',
    appointmentSuccessTitle: 'Är Ufro gouf privat gespäichert.', appointmentSuccessText: 'Haalt d’Referenz hei ënnen. De Rendez-vous ass eréischt nom perséinleche Kontakt mat der Klinik confirméiert.',
    uploadSuccessTitle: 'Är Biller goufen privat gespäichert.', uploadSuccessText: 'Haalt d’Referenz a nennt se beim Kontakt mat der Klinik. Dëst ass nach keng Diagnos oder confirméiert Rendez-vous.',
    referenceLabel: 'Är Referenz', deleteIntake: 'Meng Ufro an Dateien läschen', intakeDeleting: 'Gëtt geläscht…', intakeDeletedTitle: 'Är Donnéeë goufe geläscht.', intakeDeletedText: 'D’Ufro an eventuell Dateie goufen aus dem private Späicher geläscht.', deleteError: 'D’Läsche war net méiglech. Haalt d’Referenz a kontaktéiert d’Klinik.',
    photoAltConsultation: 'Zänndokter erkläert engem Patient e Behandlungsplang an engem moderne Raum', photoAltCare: 'Zännteam behandelt e Patient an enger heller Klinik', photoAltClinic: 'Moderne Behandlungsstull an Ausrüstung an engem rouege Raum', photoAltPlanning: 'Bespriechung vun Zännröntgebiller op engem Ecran',
  },
  en: {
    audience: 'For local and international patients', appointment: 'Appointment', whatsapp: 'WhatsApp',
    serviceGroups: ['Everyday dental care', 'Restore & replace', 'Alignment & aesthetics'], allTreatments: 'All treatments', serviceMenuIntro: 'Complete dental care at every stage of life.',
    principlesLabel: 'What guides our care', principles: ['Space', 'Trust', 'Information', 'Openness', 'Care', 'Clarity'],
    bookNow: 'Book an appointment', whatsappPrompt: 'Ask us on WhatsApp',
    urgent: 'Pain or urgent problem? Contact us directly',
    localPathEyebrow: 'Batumi · Georgia', localPathTitle: 'I live in Georgia', localPathText: 'Everyday dental care and timely appointments in Batumi.', localPathCta: 'View treatments',
    travelPathEyebrow: 'International care', travelPathTitle: 'I am travelling to Batumi', travelPathText: 'Assessment from home, treatment planned around your stay and a check before departure.', travelPathCta: 'View your 21 days',
    heroMediaLabel: 'A personal explanation before every treatment', heroMediaNote: 'Concept photography · replace with real clinic images before publication',
    careFeatureEyebrow: 'Care that looks further', careFeatureTitle: 'We are here for you. After treatment too.', careFeatureText: 'Clear instructions, a check before departure and a concrete protocol for the first seven days.', careFeatureCta: 'View aftercare & assurance',
    galleryLabel: 'A calm, modern treatment environment', galleryCaption: 'Diagnostics, explanation and treatment in one carefully planned pathway.',
    whatsappTitle: 'Prefer to talk on WhatsApp first?', whatsappText: 'Use WhatsApp for general questions about intake, planning or your stay. In an emergency, use the number provided by the clinic; medical images are shared only after the secure upload is activated.', whatsappAction: 'View WhatsApp connection', whatsappStatus: 'Prototype: the clinic’s official number still needs to be verified and connected.',
    uploadTitle: 'Add photos or X-rays', uploadText: 'Add photos, X-rays, PDF or DICOM. In this private review version they are stored non-publicly and receive a random reference.', uploadChoose: 'Choose files', uploadHelp: 'Maximum 5 files · JPG, PNG, WebP, PDF or DICOM · maximum 10 MB per file and 25 MB total', uploadSelectionError: 'One or more files were not added. Use only the listed formats, with a maximum of 5 files, 10 MB per file and 25 MB total.', uploadRemove: 'Remove',
    uploadConsent: 'I confirm that these files belong to me or that I am allowed to share them.',
    healthConsent: 'My explanation and files may contain health data. I consent to the private processing described.', privacyLink: 'Read the privacy information.',
    intakeSending: 'Saving privately…', intakeError: 'Saving failed. Check the details or try again later.',
    appointmentSuccessTitle: 'Your request was stored privately.', appointmentSuccessText: 'Keep the reference below. An appointment is confirmed only after personal contact with the clinic.',
    uploadSuccessTitle: 'Your images were stored privately.', uploadSuccessText: 'Keep the reference and quote it when contacting the clinic. This is not yet a diagnosis or confirmed appointment.',
    referenceLabel: 'Your reference', deleteIntake: 'Delete my request and files', intakeDeleting: 'Deleting…', intakeDeletedTitle: 'Your data was deleted.', intakeDeletedText: 'The request and any files were removed from private storage.', deleteError: 'Deletion failed. Keep the reference and contact the clinic.',
    photoAltConsultation: 'Dentist discussing a treatment plan with a patient in a modern treatment room', photoAltCare: 'Dental team treating a patient in a bright clinical room', photoAltClinic: 'Modern dental chair and equipment in a calm treatment room', photoAltPlanning: 'Discussion of dental X-rays on a screen',
  },
  ka: {
    audience: 'ადგილობრივი და საერთაშორისო პაციენტებისთვის', appointment: 'ვიზიტი', whatsapp: 'WhatsApp',
    serviceGroups: ['ყოველდღიური მოვლა', 'აღდგენა და ჩანაცვლება', 'თანკბილვა და ესთეტიკა'], allTreatments: 'ყველა მკურნალობა', serviceMenuIntro: 'სრული სტომატოლოგიური მოვლა ცხოვრების ყველა ეტაპზე.',
    principlesLabel: 'რას ეფუძნება ჩვენი ზრუნვა', principles: ['სივრცე', 'ნდობა', 'ინფორმაცია', 'ღიაობა', 'ზრუნვა', 'სიცხადე'],
    bookNow: 'ვიზიტის დაჯავშნა', whatsappPrompt: 'მოგვწერეთ WhatsApp-ზე',
    urgent: 'ტკივილი ან გადაუდებელი პრობლემა? დაგვიკავშირდით',
    localPathEyebrow: 'ბათუმი · საქართველო', localPathTitle: 'მე საქართველოში ვცხოვრობ', localPathText: 'ყოველდღიური სტომატოლოგიური საჭიროებები და ვიზიტების დაგეგმვა ბათუმში.', localPathCta: 'იხილეთ მკურნალობები',
    travelPathEyebrow: 'საერთაშორისო მომსახურება', travelPathTitle: 'მე ბათუმში მოვემგზავრები', travelPathText: 'წინასწარი შეფასება სახლიდან, ყოფნაზე მორგებული მკურნალობა და გამგზავრებამდე კონტროლი.', travelPathCta: 'იხილეთ თქვენი 21 დღე',
    heroMediaLabel: 'პერსონალური განმარტება ყოველი მკურნალობის წინ', heroMediaNote: 'კონცეფციის ფოტოები · გამოქვეყნებამდე ჩანაცვლდეს კლინიკის რეალური ფოტოებით',
    careFeatureEyebrow: 'ზრუნვა, რომელიც მკურნალობის შემდეგაც გრძელდება', careFeatureTitle: 'ჩვენ თქვენ გვერდით ვართ. მკურნალობის შემდეგაც.', careFeatureText: 'მკაფიო ინსტრუქციები, შეთანხმებული საკონტაქტო გზა და პირველი შვიდი დღის კონკრეტული პროტოკოლი — ადგილობრივი და ჩამოსული პაციენტებისთვის.', careFeatureCta: 'იხილეთ შემდგომი მოვლა და უსაფრთხოება',
    galleryLabel: 'მშვიდი და თანამედროვე სამკურნალო გარემო', galleryCaption: 'დიაგნოსტიკა, განმარტება და მკურნალობა ერთ საგულდაგულოდ დაგეგმილ გზაში.',
    whatsappTitle: 'გსურთ ჯერ WhatsApp-ით მოგვწეროთ?', whatsappText: 'WhatsApp გამოიყენეთ პირველადი შეფასების, დაგეგმვის ან ყოფნის შესახებ ზოგადი კითხვებისთვის. გადაუდებელ შემთხვევაში გამოიყენეთ კლინიკის მიერ მოწოდებული ნომერი; სამედიცინო სურათები მხოლოდ უსაფრთხო ატვირთვის გააქტიურების შემდეგ გაზიარდება.', whatsappAction: 'WhatsApp კავშირის ნახვა', whatsappStatus: 'პროტოტიპი: კლინიკის ოფიციალური ნომერი ჯერ უნდა გადამოწმდეს და დაერთოს.',
    uploadTitle: 'დაამატეთ ფოტოები ან რენტგენოგრამები', uploadText: 'დაამატეთ ფოტოები, რენტგენოგრამები, PDF ან DICOM. ამ დახურულ საცდელ ვერსიაში ისინი საჯაროდ არ ინახება და შემთხვევით კოდს იღებს.', uploadChoose: 'ფაილების არჩევა', uploadHelp: 'მაქსიმუმ 5 ფაილი · JPG, PNG, WebP, PDF ან DICOM · თითო ფაილი 10 მბ და ჯამში 25 მბ', uploadSelectionError: 'ერთი ან მეტი ფაილი არ დამატებულა. გამოიყენეთ მხოლოდ მითითებული ფორმატები: მაქსიმუმ 5 ფაილი, თითოეული 10 მბ და ჯამში 25 მბ.', uploadRemove: 'წაშლა',
    uploadConsent: 'ვადასტურებ, რომ ეს ფაილები ჩემია ან მათი გაზიარების უფლება მაქვს.',
    healthConsent: 'ჩემი აღწერა და ფაილები შეიძლება ჯანმრთელობის მონაცემებს შეიცავდეს. ვეთანხმები აღწერილ კერძო დამუშავებას.', privacyLink: 'წაიკითხეთ კონფიდენციალურობის ინფორმაცია.',
    intakeSending: 'კერძოდ ინახება…', intakeError: 'შენახვა ვერ მოხერხდა. შეამოწმეთ მონაცემები ან მოგვიანებით სცადეთ.',
    appointmentSuccessTitle: 'თქვენი მოთხოვნა კერძოდ შეინახა.', appointmentSuccessText: 'შეინახეთ ქვემოთ მოცემული კოდი. ვიზიტი მხოლოდ კლინიკასთან პირადი კონტაქტის შემდეგ დასტურდება.',
    uploadSuccessTitle: 'თქვენი სურათები კერძოდ შეინახა.', uploadSuccessText: 'შეინახეთ კოდი და კლინიკასთან დაკავშირებისას მიუთითეთ. ეს ჯერ არ არის დიაგნოზი ან დადასტურებული ვიზიტი.',
    referenceLabel: 'თქვენი კოდი', deleteIntake: 'მოთხოვნისა და ფაილების წაშლა', intakeDeleting: 'იშლება…', intakeDeletedTitle: 'თქვენი მონაცემები წაიშალა.', intakeDeletedText: 'მოთხოვნა და ფაილები კერძო საცავიდან წაიშალა.', deleteError: 'წაშლა ვერ მოხერხდა. შეინახეთ კოდი და დაუკავშირდით კლინიკას.',
    photoAltConsultation: 'სტომატოლოგი თანამედროვე ოთახში პაციენტს მკურნალობის გეგმას უხსნის', photoAltCare: 'სტომატოლოგიური გუნდი ნათელ კლინიკურ სივრცეში პაციენტს მკურნალობს', photoAltClinic: 'თანამედროვე სტომატოლოგიური სავარძელი და მოწყობილობა მშვიდ სამკურნალო ოთახში', photoAltPlanning: 'სტომატოლოგიური რენტგენოგრამების განხილვა ეკრანზე',
  },
}
