export const materialsContent = {
  nl: {
    eyebrow: 'Materialen & producten',
    title: 'Kwaliteit begint met een keuze die we kunnen uitleggen.',
    intro: 'Er is niet één materiaal dat voor elke situatie het beste is. De passende keuze hangt af van de diagnose, de plaats in de mond, uw beet, het behandeldoel en het onderhoud.',
    categories: [
      { id: 'crowns', title: 'Kronen & brugwerk', text: 'Materiaal en uitvoering worden gekozen op basis van de tand of kies, de beschikbare ruimte, uw beet en de gewenste uitstraling. Pasvorm en beetcontacten worden vóór definitieve plaatsing gecontroleerd.' },
      { id: 'fillings', title: 'Vullingen', text: 'Bij directe restauraties worden materiaal en kleur gekozen op basis van het defect, de plaats en de klinische omstandigheden. De tandarts legt uit wanneer een vulling wel of niet passend is.' },
      { id: 'implantComponents', title: 'Implantaatonderdelen', text: 'De onderdelen moeten passen bij het geplande implantaatsysteem en het prothetische ontwerp. Relevante productgegevens worden in het behandeldossier vastgelegd.' },
      { id: 'temporaryWork', title: 'Tijdelijke voorzieningen', text: 'Tijdelijke kronen, bruggen of restauraties overbruggen de periode tot de volgende behandelfase. We leggen het doel, de beperkingen en de verwachte gebruiksduur uit.' },
    ],
    transparencyTitle: 'U moet weten wat er wordt gebruikt.',
    transparencyNote: 'Vóór de behandeling leggen we uit welke opties beschikbaar zijn, welke afwegingen daarbij horen en wat ze kosten. Waar van toepassing leggen we de fabrikant en het lot- of batchnummer vast in uw behandeldossier.',
    verifiedOnly: 'Specifieke merk- en productgegevens verschijnen hier alleen nadat de kliniek ze schriftelijk heeft bevestigd.',
    factLabels: { brand: 'Merk', manufacturer: 'Fabrikant', system: 'Systeem', material: 'Materiaal', origin: 'Herkomst', warranty: 'Garantie', traceability: 'Traceerbaarheid', documentation: 'Productdocumentatie' },
    traceabilityValue: 'Batch- of lotregistratie bevestigd',
    viewDocument: 'Bekijk productdocument',
    viewWarranty: 'Bekijk garantievoorwaarden',
    monthOne: 'maand', monthOther: 'maanden',
  },
  de: {
    eyebrow: 'Materialien & Produkte',
    title: 'Qualität beginnt mit einer Wahl, die wir erklären können.',
    intro: 'Kein Material ist für jede Situation die beste Wahl. Die passende Auswahl hängt von Diagnose, Position im Mund, Biss, Behandlungsziel und Pflege ab.',
    categories: [
      { id: 'crowns', title: 'Kronen & Brücken', text: 'Material und Ausführung werden passend zum betroffenen Zahn, zum verfügbaren Platz, zum Biss und zum gewünschten Erscheinungsbild gewählt. Passform und Bisskontakte werden vor dem endgültigen Einsetzen geprüft.' },
      { id: 'fillings', title: 'Füllungen', text: 'Bei direkten Restaurationen werden Material und Farbe nach Defekt, Position und klinischen Bedingungen gewählt. Der Zahnarzt erklärt, wann eine Füllung geeignet ist – und wann nicht.' },
      { id: 'implantComponents', title: 'Implantatkomponenten', text: 'Die Komponenten müssen zum geplanten Implantatsystem und zum prothetischen Konzept passen. Relevante Produktangaben werden in der Behandlungsakte dokumentiert.' },
      { id: 'temporaryWork', title: 'Provisorische Versorgungen', text: 'Provisorische Kronen, Brücken oder Restaurationen überbrücken die Zeit bis zum nächsten Behandlungsschritt. Zweck, Grenzen und vorgesehene Tragedauer werden erklärt.' },
    ],
    transparencyTitle: 'Sie sollen wissen, was verwendet wird.',
    transparencyNote: 'Vor der Behandlung erläutern wir die verfügbaren Optionen, die relevanten Vor- und Nachteile sowie die Kosten. Soweit zutreffend, dokumentieren wir Hersteller und Chargen- oder Losnummer in Ihrer Behandlungsakte.',
    verifiedOnly: 'Konkrete Marken- und Produktangaben erscheinen hier erst nach schriftlicher Bestätigung durch die Klinik.',
    factLabels: { brand: 'Marke', manufacturer: 'Hersteller', system: 'System', material: 'Material', origin: 'Herkunft', warranty: 'Garantie', traceability: 'Rückverfolgbarkeit', documentation: 'Produktdokumentation' },
    traceabilityValue: 'Chargen- oder Loserfassung bestätigt',
    viewDocument: 'Produktdokument ansehen',
    viewWarranty: 'Garantiebedingungen ansehen',
    monthOne: 'Monat', monthOther: 'Monate',
  },
  fr: {
    eyebrow: 'Matériaux & produits',
    title: 'La qualité commence par un choix que nous pouvons expliquer.',
    intro: 'Aucun matériau n’est le meilleur dans toutes les situations. Le choix approprié dépend du diagnostic, de la position en bouche, de l’occlusion, de l’objectif du traitement et de l’entretien.',
    categories: [
      { id: 'crowns', title: 'Couronnes & bridges', text: 'Le matériau et la conception sont choisis selon la dent concernée, l’espace disponible, l’occlusion et le résultat recherché. L’ajustement et les contacts occlusaux sont vérifiés avant la pose définitive.' },
      { id: 'fillings', title: 'Obturations', text: 'Pour les restaurations directes, le matériau et la teinte sont choisis selon la zone à restaurer, sa position et les conditions cliniques. Le dentiste explique quand une obturation est indiquée — et quand elle ne l’est pas.' },
      { id: 'implantComponents', title: 'Composants implantaires', text: 'Les composants doivent correspondre au système implantaire planifié et au projet prothétique. Les références utiles sont consignées dans le dossier de soins.' },
      { id: 'temporaryWork', title: 'Éléments provisoires', text: 'Les couronnes, bridges ou restaurations provisoires couvrent la période jusqu’à l’étape suivante. Leur rôle, leurs limites et leur durée d’utilisation prévue sont expliqués.' },
    ],
    transparencyTitle: 'Vous devez savoir ce qui est utilisé.',
    transparencyNote: 'Avant le traitement, nous expliquons les options disponibles, leurs différences pertinentes, leurs limites et leurs coûts. Lorsque cela s’applique, le fabricant et le numéro de lot sont consignés dans votre dossier.',
    verifiedOnly: 'Les marques et références précises ne sont affichées ici qu’après confirmation écrite de la clinique.',
    factLabels: { brand: 'Marque', manufacturer: 'Fabricant', system: 'Système', material: 'Matériau', origin: 'Origine', warranty: 'Garantie', traceability: 'Traçabilité', documentation: 'Documentation produit' },
    traceabilityValue: 'Enregistrement du lot confirmé',
    viewDocument: 'Voir le document produit',
    viewWarranty: 'Voir les conditions de garantie',
    monthOne: 'mois', monthOther: 'mois',
  },
  lb: {
    eyebrow: 'Materialien & Produkter',
    title: 'Qualitéit fänkt mat enger Wiel un, déi mir erkläre kënnen.',
    intro: 'Kee Material ass fir all Situatioun déi bescht Wiel. Déi passend Wiel hänkt vun der Diagnos, der Positioun am Mond, dem Bëss, dem Behandlungszil an der Fleeg of.',
    categories: [
      { id: 'crowns', title: 'Krounen & Brécken', text: 'Material an Ausféierung ginn dem betraffenen Zant, dem verfügbare Raum, dem Bëss an dem gewënschten Ausgesinn ugepasst. Passform a Bësskontakter gi virum definitive Asetzen kontrolléiert.' },
      { id: 'fillings', title: 'Fëllungen', text: 'Bei direkte Restauratioune gi Material a Faarf jee no Defekt, Positioun a klinesche Bedéngunge gewielt. Den Zänndokter erkläert, wéini eng Fëllung passend ass – a wéini net.' },
      { id: 'implantComponents', title: 'Implantatkomponenten', text: 'D’Komponente mussen zum geplangten Implantatsystem an zum prothetesche Konzept passen. Relevant Produktinformatioune ginn am Behandlungsdossier dokumentéiert.' },
      { id: 'temporaryWork', title: 'Provisoresch Versuergungen', text: 'Provisoresch Krounen, Brécken oder Restauratiounen iwwerbrécken d’Zäit bis zum nächste Behandlungsschrëtt. Mir erklären hiren Zweck, hir Grenzen a wéi laang se virgesi sinn.' },
    ],
    transparencyTitle: 'Dir sollt wëssen, wat benotzt gëtt.',
    transparencyNote: 'Virun der Behandlung erkläre mir déi verfügbar Optiounen, déi wichteg Ënnerscheeder a Begrenzungen an d’Käschten. Wann et zoutrëfft, dokumentéiere mir den Hiersteller an d’Chargen- oder Lotnummer am Behandlungsdossier.',
    verifiedOnly: 'Konkret Marken- a Produktdetailer ginn hei eréischt no der schrëftlecher Bestätegung vun der Klinik gewisen.',
    factLabels: { brand: 'Mark', manufacturer: 'Hiersteller', system: 'System', material: 'Material', origin: 'Hierkonft', warranty: 'Garantie', traceability: 'Réckverfolgbarkeet', documentation: 'Produktdokumentatioun' },
    traceabilityValue: 'Chargen- oder Lotregistréierung confirméiert',
    viewDocument: 'Produktdokument kucken',
    viewWarranty: 'Garantiebedéngunge kucken',
    monthOne: 'Mount', monthOther: 'Méint',
  },
  en: {
    eyebrow: 'Materials & products',
    title: 'Quality starts with a choice we can explain.',
    intro: 'No single material is best for every situation. The appropriate choice depends on the diagnosis, position in the mouth, bite, treatment goal and maintenance.',
    categories: [
      { id: 'crowns', title: 'Crowns & bridgework', text: 'Material and construction are selected to suit the tooth, available space, bite and intended appearance. Fit and bite contacts are checked before definitive placement.' },
      { id: 'fillings', title: 'Fillings', text: 'For direct restorations, material and shade are chosen according to the area being restored, its location and the clinical conditions. The dentist explains when a filling is—and is not—a suitable option.' },
      { id: 'implantComponents', title: 'Implant components', text: 'Components must match the planned implant system and prosthetic design. Relevant product details are recorded in the treatment record.' },
      { id: 'temporaryWork', title: 'Temporary work', text: 'Temporary crowns, bridges or restorations cover the period until the next treatment stage. Their purpose, limitations and expected duration are explained.' },
    ],
    transparencyTitle: 'You should know what is being used.',
    transparencyNote: 'Before treatment, we explain the available options, the relevant trade-offs and the costs. Where applicable, the manufacturer and batch or lot number are recorded in your treatment file.',
    verifiedOnly: 'Specific brands and product details appear here only after written verification by the clinic.',
    factLabels: { brand: 'Brand', manufacturer: 'Manufacturer', system: 'System', material: 'Material', origin: 'Origin', warranty: 'Warranty', traceability: 'Traceability', documentation: 'Product documentation' },
    traceabilityValue: 'Batch or lot recording confirmed',
    viewDocument: 'View product document',
    viewWarranty: 'View warranty terms',
    monthOne: 'month', monthOther: 'months',
  },
  ka: {
    eyebrow: 'მასალები და პროდუქტები',
    title: 'ხარისხი იწყება არჩევანით, რომლის ახსნაც შეგვიძლია.',
    intro: 'არც ერთი მასალა არ არის საუკეთესო ყველა სიტუაციაში. შესაფერისი არჩევანი დამოკიდებულია დიაგნოზზე, პირის ღრუში მდებარეობაზე, თანკბილვაზე, მკურნალობის მიზანსა და მოვლაზე.',
    categories: [
      { id: 'crowns', title: 'გვირგვინები და ხიდები', text: 'მასალა და კონსტრუქცია შეირჩევა კონკრეტული კბილის, არსებული სივრცის, თანკბილვისა და სასურველი იერსახის მიხედვით. საბოლოო მოთავსებამდე მოწმდება მორგება და თანკბილვითი კონტაქტები.' },
      { id: 'fillings', title: 'ბჟენები', text: 'პირდაპირი რესტავრაციისას მასალა და ფერი შეირჩევა აღსადგენი უბნის, მისი მდებარეობისა და კლინიკური პირობების მიხედვით. სტომატოლოგი აგიხსნით, როდის არის ბჟენი შესაფერისი არჩევანი და როდის — არა.' },
      { id: 'implantComponents', title: 'იმპლანტის კომპონენტები', text: 'კომპონენტები უნდა შეესაბამებოდეს დაგეგმილ იმპლანტის სისტემასა და პროთეზულ კონსტრუქციას. შესაბამისი პროდუქტის მონაცემები მკურნალობის დოკუმენტაციაში აღირიცხება.' },
      { id: 'temporaryWork', title: 'დროებითი კონსტრუქციები', text: 'დროებითი გვირგვინები, ხიდები ან რესტავრაციები გამოიყენება მკურნალობის მომდევნო ეტაპამდე. აგიხსნით მათ დანიშნულებას, შეზღუდვებსა და გამოყენების მოსალოდნელ ხანგრძლივობას.' },
    ],
    transparencyTitle: 'თქვენ უნდა იცოდეთ, რას ვიყენებთ.',
    transparencyNote: 'მკურნალობამდე განვიხილავთ ხელმისაწვდომ ვარიანტებს, მათ მნიშვნელოვან განსხვავებებს, შეზღუდვებსა და ხარჯებს. საჭიროების შემთხვევაში მწარმოებელი და პარტიის ან ლოტის ნომერი მკურნალობის დოკუმენტაციაში აღირიცხება.',
    verifiedOnly: 'კონკრეტული ბრენდი და პროდუქტის მონაცემები აქ მხოლოდ კლინიკის წერილობითი დადასტურების შემდეგ გამოჩნდება.',
    factLabels: { brand: 'ბრენდი', manufacturer: 'მწარმოებელი', system: 'სისტემა', material: 'მასალა', origin: 'წარმოშობა', warranty: 'გარანტია', traceability: 'მიკვლევადობა', documentation: 'პროდუქტის დოკუმენტაცია' },
    traceabilityValue: 'პარტიის ან ლოტის აღრიცხვა დადასტურებულია',
    viewDocument: 'პროდუქტის დოკუმენტის ნახვა',
    viewWarranty: 'გარანტიის პირობების ნახვა',
    monthOne: 'თვე', monthOther: 'თვე',
  },
}

