const sharedCategoryIds = {
  diagnostics: 'Diagnostics & planning',
  prevention: 'Prevention & hygiene',
  restorative: 'Restorative dentistry',
  endodontics: 'Root canal treatment',
  surgery: 'Oral surgery',
  prosthetics: 'Crowns & prosthetics',
  implants: 'Implant dentistry',
  aesthetic: 'Aesthetic dentistry',
  orthodontics: 'Orthodontics',
  children: 'Children’s dentistry',
}

const sharedServiceIds = {
  consultation: 'Dental consultation',
  smallXray: 'Small dental X-ray',
  panoramicXray: 'Panoramic X-ray',
  cbctScan: '3D CBCT scan',
  treatmentPlan: 'Written treatment plan',
  hygiene: 'Professional hygiene treatment',
  deepCleaning: 'Deep periodontal cleaning',
  fluoride: 'Fluoride treatment',
  compositeFilling: 'Composite filling',
  inlayOnlay: 'Ceramic inlay or onlay',
  toothBuildUp: 'Tooth build-up',
  rootCanalFront: 'Root canal · front tooth',
  rootCanalPremolar: 'Root canal · premolar',
  rootCanalMolar: 'Root canal · molar',
  retreatment: 'Root canal retreatment',
  simpleExtraction: 'Simple extraction',
  surgicalExtraction: 'Surgical extraction',
  wisdomTooth: 'Wisdom tooth removal',
  boneGraft: 'Bone augmentation',
  ceramicCrown: 'All-ceramic crown',
  zirconiaCrown: 'Zirconia crown',
  implantCrown: 'Crown on implant',
  bridgeUnit: 'Bridge · per unit',
  partialDenture: 'Partial denture',
  fullDenture: 'Full denture',
  implantPlacement: 'Implant placement',
  healingAbutment: 'Healing abutment',
  implantBundle: 'Implant, abutment and crown',
  allOnFour: 'Full-arch restoration on four implants',
  whitening: 'Professional whitening',
  ceramicVeneer: 'Ceramic veneer',
  compositeVeneer: 'Composite veneer',
  gumContouring: 'Gum contouring',
  orthodonticConsultation: 'Orthodontic consultation',
  fixedBraces: 'Fixed braces',
  clearAligners: 'Clear aligner treatment',
  retainer: 'Retainer',
  childConsultation: 'Child dental consultation',
  childFilling: 'Filling for a primary tooth',
  fissureSealant: 'Fissure sealant',
  milkToothExtraction: 'Primary tooth extraction',
}

const nlServices = {
  consultation: 'Tandartsconsult', smallXray: 'Kleine tandfoto', panoramicXray: 'Panoramaröntgenfoto', cbctScan: '3D-CBCT-scan', treatmentPlan: 'Schriftelijk behandelplan',
  hygiene: 'Professionele gebitsreiniging', deepCleaning: 'Diepe parodontale reiniging', fluoride: 'Fluoridebehandeling',
  compositeFilling: 'Composietvulling', inlayOnlay: 'Keramische inlay of onlay', toothBuildUp: 'Tandopbouw',
  rootCanalFront: 'Wortelkanaal · voortand', rootCanalPremolar: 'Wortelkanaal · premolaar', rootCanalMolar: 'Wortelkanaal · molaar', retreatment: 'Herbehandeling wortelkanaal',
  simpleExtraction: 'Eenvoudige extractie', surgicalExtraction: 'Chirurgische extractie', wisdomTooth: 'Verwijderen verstandskies', boneGraft: 'Botopbouw',
  ceramicCrown: 'Volkeramische kroon', zirconiaCrown: 'Zirkoniumkroon', implantCrown: 'Kroon op implantaat', bridgeUnit: 'Brug · per element', partialDenture: 'Gedeeltelijke prothese', fullDenture: 'Volledige prothese',
  implantPlacement: 'Plaatsing implantaat', healingAbutment: 'Healing abutment', implantBundle: 'Implantaat, abutment en kroon', allOnFour: 'Volledige tandboog op vier implantaten',
  whitening: 'Professioneel bleken', ceramicVeneer: 'Keramische facing', compositeVeneer: 'Composiet facing', gumContouring: 'Tandvleescontourering',
  orthodonticConsultation: 'Orthodontisch consult', fixedBraces: 'Vaste beugel', clearAligners: 'Behandeling met transparante aligners', retainer: 'Retainer',
  childConsultation: 'Tandartsconsult voor kinderen', childFilling: 'Vulling in een melktand', fissureSealant: 'Fissuursealant', milkToothExtraction: 'Extractie melktand',
}

const deServices = {
  consultation: 'Zahnärztliche Beratung', smallXray: 'Kleine Zahnaufnahme', panoramicXray: 'Panoramaröntgen', cbctScan: '3D-DVT-Aufnahme', treatmentPlan: 'Schriftlicher Behandlungsplan',
  hygiene: 'Professionelle Zahnreinigung', deepCleaning: 'Parodontale Tiefenreinigung', fluoride: 'Fluoridierung',
  compositeFilling: 'Kompositfüllung', inlayOnlay: 'Keramikinlay oder -onlay', toothBuildUp: 'Zahnaufbau',
  rootCanalFront: 'Wurzelkanal · Frontzahn', rootCanalPremolar: 'Wurzelkanal · Prämolar', rootCanalMolar: 'Wurzelkanal · Molar', retreatment: 'Wurzelkanalrevision',
  simpleExtraction: 'Einfache Extraktion', surgicalExtraction: 'Chirurgische Extraktion', wisdomTooth: 'Weisheitszahnentfernung', boneGraft: 'Knochenaufbau',
  ceramicCrown: 'Vollkeramikkrone', zirconiaCrown: 'Zirkonkrone', implantCrown: 'Krone auf Implantat', bridgeUnit: 'Brücke · je Einheit', partialDenture: 'Teilprothese', fullDenture: 'Vollprothese',
  implantPlacement: 'Implantatinsertion', healingAbutment: 'Gingivaformer', implantBundle: 'Implantat, Abutment und Krone', allOnFour: 'Vollbogenversorgung auf vier Implantaten',
  whitening: 'Professionelles Bleaching', ceramicVeneer: 'Keramikveneer', compositeVeneer: 'Kompositveneer', gumContouring: 'Zahnfleischkonturierung',
  orthodonticConsultation: 'Kieferorthopädische Beratung', fixedBraces: 'Feste Zahnspange', clearAligners: 'Behandlung mit transparenten Alignern', retainer: 'Retainer',
  childConsultation: 'Kinderzahnärztliche Beratung', childFilling: 'Füllung am Milchzahn', fissureSealant: 'Fissurenversiegelung', milkToothExtraction: 'Milchzahnextraktion',
}

const frServices = {
  consultation: 'Consultation dentaire', smallXray: 'Petite radiographie dentaire', panoramicXray: 'Radiographie panoramique', cbctScan: 'Scanner CBCT 3D', treatmentPlan: 'Plan de traitement écrit',
  hygiene: 'Nettoyage dentaire professionnel', deepCleaning: 'Surfaçage parodontal profond', fluoride: 'Fluoration',
  compositeFilling: 'Obturation composite', inlayOnlay: 'Inlay ou onlay céramique', toothBuildUp: 'Reconstitution dentaire',
  rootCanalFront: 'Endodontie · dent antérieure', rootCanalPremolar: 'Endodontie · prémolaire', rootCanalMolar: 'Endodontie · molaire', retreatment: 'Retraitement endodontique',
  simpleExtraction: 'Extraction simple', surgicalExtraction: 'Extraction chirurgicale', wisdomTooth: 'Extraction de dent de sagesse', boneGraft: 'Augmentation osseuse',
  ceramicCrown: 'Couronne tout céramique', zirconiaCrown: 'Couronne en zircone', implantCrown: 'Couronne sur implant', bridgeUnit: 'Bridge · par élément', partialDenture: 'Prothèse partielle', fullDenture: 'Prothèse complète',
  implantPlacement: 'Pose d’implant', healingAbutment: 'Pilier de cicatrisation', implantBundle: 'Implant, pilier et couronne', allOnFour: 'Arcade complète sur quatre implants',
  whitening: 'Blanchiment professionnel', ceramicVeneer: 'Facette céramique', compositeVeneer: 'Facette composite', gumContouring: 'Contourage gingival',
  orthodonticConsultation: 'Consultation orthodontique', fixedBraces: 'Appareil fixe', clearAligners: 'Traitement par aligneurs transparents', retainer: 'Contention',
  childConsultation: 'Consultation dentaire pédiatrique', childFilling: 'Obturation d’une dent temporaire', fissureSealant: 'Scellement de sillons', milkToothExtraction: 'Extraction d’une dent temporaire',
}

const lbServices = {
  consultation: 'Zännärztlech Consultatioun', smallXray: 'Kleng Zänn-Röntgenopnam', panoramicXray: 'Panorama-Röntgen', cbctScan: '3D-CBCT-Scan', treatmentPlan: 'Schrëftleche Behandlungsplang',
  hygiene: 'Professionell Zännreinigung', deepCleaning: 'Déif parodontal Reinigung', fluoride: 'Fluoridbehandlung',
  compositeFilling: 'Kompositfëllung', inlayOnlay: 'Kerameschen Inlay oder Onlay', toothBuildUp: 'Zännopbau',
  rootCanalFront: 'Wuerzelkanal · viischten Zant', rootCanalPremolar: 'Wuerzelkanal · Premolar', rootCanalMolar: 'Wuerzelkanal · Molar', retreatment: 'Wuerzelkanal-Nobehandlung',
  simpleExtraction: 'Einfach Extraktioun', surgicalExtraction: 'Chirurgesch Extraktioun', wisdomTooth: 'Wäisheetszant ewechhuelen', boneGraft: 'Schankenopbau',
  ceramicCrown: 'Vollkeramesch Kroun', zirconiaCrown: 'Zirkonkroun', implantCrown: 'Kroun op Implantat', bridgeUnit: 'Bréck · pro Eenheet', partialDenture: 'Deelprothees', fullDenture: 'Vollprothees',
  implantPlacement: 'Implantat asetzen', healingAbutment: 'Heelungsabutment', implantBundle: 'Implantat, Abutment a Kroun', allOnFour: 'Komplette Zantbou op véier Implantater',
  whitening: 'Professionellt Bleaching', ceramicVeneer: 'Keramesche Veneer', compositeVeneer: 'Kompositveneer', gumContouring: 'Zännfleesch konturéieren',
  orthodonticConsultation: 'Kieferorthopedesch Consultatioun', fixedBraces: 'Fest Zännspang', clearAligners: 'Behandlung mat transparenten Aligneren', retainer: 'Retainer',
  childConsultation: 'Zännconsultatioun fir Kanner', childFilling: 'Fëllung vun engem Mëllechzant', fissureSealant: 'Fissureversigelung', milkToothExtraction: 'Mëllechzant-Extraktioun',
}

const kaServices = {
  consultation: 'სტომატოლოგის კონსულტაცია', smallXray: 'მცირე დენტალური რენტგენი', panoramicXray: 'პანორამული რენტგენი', cbctScan: '3D CBCT კვლევა', treatmentPlan: 'წერილობითი მკურნალობის გეგმა',
  hygiene: 'პროფესიული წმენდა', deepCleaning: 'ღრმა პაროდონტული წმენდა', fluoride: 'ფტორირება',
  compositeFilling: 'კომპოზიტური ბჟენი', inlayOnlay: 'კერამიკული ინლეი ან ონლეი', toothBuildUp: 'კბილის აღდგენა',
  rootCanalFront: 'ფესვის არხი · წინა კბილი', rootCanalPremolar: 'ფესვის არხი · პრემოლარი', rootCanalMolar: 'ფესვის არხი · მოლარი', retreatment: 'ფესვის არხის განმეორებითი მკურნალობა',
  simpleExtraction: 'მარტივი ექსტრაქცია', surgicalExtraction: 'ქირურგიული ექსტრაქცია', wisdomTooth: 'სიბრძნის კბილის ამოღება', boneGraft: 'ძვლის აუგმენტაცია',
  ceramicCrown: 'მთლიანად კერამიკული გვირგვინი', zirconiaCrown: 'ცირკონიის გვირგვინი', implantCrown: 'გვირგვინი იმპლანტზე', bridgeUnit: 'ხიდი · ერთეულზე', partialDenture: 'ნაწილობრივი პროთეზი', fullDenture: 'სრული პროთეზი',
  implantPlacement: 'იმპლანტის მოთავსება', healingAbutment: 'შეხორცების აბატმენტი', implantBundle: 'იმპლანტი, აბატმენტი და გვირგვინი', allOnFour: 'სრული რკალი ოთხ იმპლანტზე',
  whitening: 'პროფესიული გათეთრება', ceramicVeneer: 'კერამიკული ვინირი', compositeVeneer: 'კომპოზიტური ვინირი', gumContouring: 'ღრძილის კონტურირება',
  orthodonticConsultation: 'ორთოდონტიული კონსულტაცია', fixedBraces: 'ფიქსირებული ბრეკეტები', clearAligners: 'გამჭვირვალე კაპებით მკურნალობა', retainer: 'რეტეინერი',
  childConsultation: 'ბავშვთა სტომატოლოგის კონსულტაცია', childFilling: 'სარძევე კბილის ბჟენი', fissureSealant: 'ფისურის ჰერმეტიზაცია', milkToothExtraction: 'სარძევე კბილის ამოღება',
}

const en = {
  navLabel: 'Fees',
  metaTitle: 'Dental fees in Batumi | Batumi Dental Clinic',
  metaDescription: 'A transparent dental fee list in Georgian lari, with inclusions, materials and treatment stages stated per procedure.',
  templateMetaDescription: 'A preview of a transparent dental fee structure in Georgian lari, ready for this clinic’s verified rates, materials and inclusions.',
  hero: {
    eyebrow: 'Fees · scope · clarity',
    title: 'A price only means something when you know what it includes.',
    lead: 'We publish clinic-approved fees in Georgian lari. For each treatment, the page can show the material or system, included diagnostics, expected visits and important exclusions.',
    emptyLead: 'This preview shows how clinic-approved fees will be presented in Georgian lari, including material, diagnostics, expected visits and important exclusions once verified.',
    primary: 'Request a personal estimate',
    secondary: 'Ask on WhatsApp',
    note: 'The final plan and fee follow a clinical examination. Nothing is added without discussion.',
  },
  principlesLabel: 'How to read this list',
  principles: [
    ['GEL first', 'The clinic’s official fee is always shown in Georgian lari.'],
    ['Scope beside price', 'Inclusions and exclusions stay close to the amount.'],
    ['Plan before consent', 'You receive an itemised plan before treatment begins.'],
  ],
  list: {
    eyebrow: 'Clinic-approved fee list',
    title: 'Clear fees, organised by care.',
    intro: 'Only treatments and amounts confirmed by the clinic appear here.',
    verified: 'Last checked',
    emptyEyebrow: 'Ready for this clinic’s fee schedule',
    emptyTitle: 'The structure is complete. The clinic’s own rates come next.',
    emptyText: 'This sellable website template never borrows another practice’s prices. During clinic onboarding, the approved GEL rates, materials, inclusions and verification date are added in one central file.',
    emptyAction: 'Discuss your treatment and receive an itemised estimate in the meantime.',
  },
  labels: {
    from: 'From {price}',
    onRequest: 'After assessment',
    includes: 'Included',
    excludes: 'Not included',
    materialSystem: 'Material / system',
    visits: 'Expected visits',
    duration: 'Expected duration',
    diagnostics: 'Diagnostics',
    note: 'Important',
    oneVisit: '1 visit',
    exactVisits: '{count} visits',
    multipleVisits: '{min}–{max} visits',
    unit: { treatment: 'treatment', tooth: 'tooth', unit: 'unit', jaw: 'jaw', arch: 'arch', session: 'session' },
  },
  transparency: {
    eyebrow: 'No headline price without context',
    title: 'What a good clinic records beside every fee.',
    intro: 'Each installation is adapted to the clinic’s own care, lab partners and protocols.',
    steps: [
      ['01', 'Exact scope', 'What is included, and which diagnostics, temporary work or laboratory costs are separate.'],
      ['02', 'Material and system', 'The crown material, implant system or filling material relevant to the plan.'],
      ['03', 'Treatment rhythm', 'Likely visits, healing phases and whether a second stay may be needed.'],
      ['04', 'Verification date', 'A visible date so patients know when the clinic last approved the information.'],
    ],
  },
  closing: {
    eyebrow: 'Your mouth is not a menu',
    title: 'Start with the right diagnosis, then compare the complete plan.',
    text: 'Send recent images securely if you have them. The clinic can prepare a preliminary outline before confirming it in person.',
    primary: 'Plan a consultation',
    secondary: 'Send images securely',
  },
  categories: sharedCategoryIds,
  services: sharedServiceIds,
}

const nl = {
  ...en,
  navLabel: 'Prijslijst',
  metaTitle: 'Tandartstarieven in Batumi | Batumi Dental Clinic',
  metaDescription: 'Een transparante tandartsprijslijst in Georgische lari, met inclusies, materialen en behandelstappen per behandeling.',
  templateMetaDescription: 'Een voorvertoning van een transparante tandartsprijslijst in Georgische lari, klaar voor de geverifieerde tarieven en materialen van deze kliniek.',
  hero: { eyebrow: 'Prijzen · inhoud · duidelijkheid', title: 'Een prijs zegt pas iets als u weet wat erin zit.', lead: 'Wij publiceren door de kliniek goedgekeurde tarieven in Georgische lari. Per behandeling kunnen materiaal of systeem, diagnostiek, verwachte bezoeken en belangrijke uitsluitingen worden getoond.', emptyLead: 'Deze voorvertoning laat zien hoe door de kliniek goedgekeurde GEL-tarieven straks worden gepubliceerd, met materiaal, diagnostiek, verwachte bezoeken en belangrijke uitsluitingen.', primary: 'Vraag een persoonlijke begroting', secondary: 'Vraag het via WhatsApp', note: 'Het definitieve plan en tarief volgen na klinisch onderzoek. Niets wordt toegevoegd zonder overleg.' },
  principlesLabel: 'Zo leest u deze lijst',
  principles: [['GEL als basis', 'Het officiële kliniektarief staat altijd in Georgische lari.'], ['Inhoud naast prijs', 'Inclusies en uitsluitingen staan direct bij het bedrag.'], ['Plan vóór toestemming', 'U ontvangt een gespecificeerd plan voordat de behandeling begint.']],
  list: { eyebrow: 'Door de kliniek goedgekeurde prijslijst', title: 'Heldere tarieven, geordend per zorggebied.', intro: 'Alleen door de kliniek bevestigde behandelingen en bedragen verschijnen hier.', verified: 'Laatst gecontroleerd', emptyEyebrow: 'Klaar voor de tarieven van deze kliniek', emptyTitle: 'De structuur staat. Nu volgen de eigen kliniektarieven.', emptyText: 'Dit verkoopbare websitesjabloon neemt nooit prijzen van een andere praktijk over. Tijdens de onboarding worden goedgekeurde GEL-tarieven, materialen, inclusies en verificatiedatum in één centraal bestand ingevuld.', emptyAction: 'Bespreek intussen uw behandeling en ontvang een gespecificeerde begroting.' },
  labels: { from: 'Vanaf {price}', onRequest: 'Na beoordeling', includes: 'Inbegrepen', excludes: 'Niet inbegrepen', materialSystem: 'Materiaal / systeem', visits: 'Verwachte bezoeken', duration: 'Verwachte duur', diagnostics: 'Diagnostiek', note: 'Belangrijk', oneVisit: '1 bezoek', exactVisits: '{count} bezoeken', multipleVisits: '{min}–{max} bezoeken', unit: { treatment: 'behandeling', tooth: 'tand', unit: 'element', jaw: 'kaak', arch: 'tandboog', session: 'sessie' } },
  transparency: { eyebrow: 'Geen lokprijs zonder context', title: 'Wat een goede kliniek bij ieder tarief vastlegt.', intro: 'Elke installatie wordt afgestemd op de eigen zorg, laboratoriumpartners en protocollen van de kliniek.', steps: [['01', 'Exacte inhoud', 'Wat inbegrepen is en welke diagnostiek, tijdelijke voorzieningen of laboratoriumkosten apart zijn.'], ['02', 'Materiaal en systeem', 'Het kroonmateriaal, implantaatsysteem of vulmateriaal dat bij het plan hoort.'], ['03', 'Behandelritme', 'Waarschijnlijke bezoeken, genezingsfasen en of een tweede verblijf nodig kan zijn.'], ['04', 'Verificatiedatum', 'Een zichtbare datum zodat patiënten weten wanneer de kliniek de informatie heeft goedgekeurd.']] },
  closing: { eyebrow: 'Uw gebit is geen menukaart', title: 'Begin met de juiste diagnose en vergelijk daarna het volledige plan.', text: 'Stuur recente beelden veilig op als u die heeft. De kliniek kan vooraf een voorlopige opzet maken en die persoonlijk bevestigen.', primary: 'Plan een consult', secondary: 'Beelden veilig versturen' },
  categories: { diagnostics: 'Diagnostiek & planning', prevention: 'Preventie & mondhygiëne', restorative: 'Restauratieve tandheelkunde', endodontics: 'Wortelkanaalbehandeling', surgery: 'Kaakchirurgie', prosthetics: 'Kronen & prothetiek', implants: 'Implantologie', aesthetic: 'Esthetische tandheelkunde', orthodontics: 'Orthodontie', children: 'Kindertandheelkunde' },
  services: nlServices,
}

const de = {
  ...en,
  navLabel: 'Preise',
  metaTitle: 'Zahnarztpreise in Batumi | Batumi Dental Clinic',
  metaDescription: 'Eine transparente Preisliste in georgischen Lari mit Leistungen, Materialien und Behandlungsphasen.',
  templateMetaDescription: 'Vorschau einer transparenten Preisliste in georgischen Lari, bereit für die geprüften Preise, Materialien und Leistungen dieser Klinik.',
  hero: { eyebrow: 'Preise · Umfang · Klarheit', title: 'Ein Preis ist nur aussagekräftig, wenn klar ist, was er enthält.', lead: 'Wir veröffentlichen von der Klinik bestätigte Preise in georgischen Lari. Zu jeder Behandlung können Material oder System, Diagnostik, voraussichtliche Termine und wichtige Ausschlüsse stehen.', emptyLead: 'Diese Vorschau zeigt, wie bestätigte GEL-Preise mit Material, Diagnostik, voraussichtlichen Terminen und wichtigen Ausschlüssen veröffentlicht werden.', primary: 'Persönlichen Kostenvoranschlag anfragen', secondary: 'Per WhatsApp fragen', note: 'Der endgültige Plan und Preis folgen nach der klinischen Untersuchung. Nichts wird ohne Rücksprache ergänzt.' },
  principlesLabel: 'So lesen Sie diese Liste',
  principles: [['GEL als Grundlage', 'Der offizielle Klinikpreis wird immer in georgischen Lari angegeben.'], ['Umfang direkt am Preis', 'Inklusiv- und Exklusivleistungen stehen unmittelbar beim Betrag.'], ['Plan vor Zustimmung', 'Vor Behandlungsbeginn erhalten Sie einen aufgeschlüsselten Plan.']],
  list: { eyebrow: 'Von der Klinik bestätigte Preisliste', title: 'Klare Preise, nach Versorgung geordnet.', intro: 'Nur von der Klinik bestätigte Behandlungen und Beträge erscheinen hier.', verified: 'Zuletzt geprüft', emptyEyebrow: 'Bereit für die Preise dieser Klinik', emptyTitle: 'Die Struktur steht. Jetzt folgen die klinikeigenen Preise.', emptyText: 'Diese verkäufliche Website-Vorlage übernimmt niemals Preise einer anderen Praxis. Beim Onboarding werden bestätigte GEL-Preise, Materialien, Leistungen und das Prüfdatum zentral eingetragen.', emptyAction: 'Besprechen Sie bis dahin Ihre Behandlung und erhalten Sie einen aufgeschlüsselten Kostenvoranschlag.' },
  labels: { from: 'Ab {price}', onRequest: 'Nach Untersuchung', includes: 'Enthalten', excludes: 'Nicht enthalten', materialSystem: 'Material / System', visits: 'Voraussichtliche Termine', duration: 'Voraussichtliche Dauer', diagnostics: 'Diagnostik', note: 'Wichtig', oneVisit: '1 Termin', exactVisits: '{count} Termine', multipleVisits: '{min}–{max} Termine', unit: { treatment: 'Behandlung', tooth: 'Zahn', unit: 'Einheit', jaw: 'Kiefer', arch: 'Zahnbogen', session: 'Sitzung' } },
  transparency: { eyebrow: 'Kein Lockpreis ohne Kontext', title: 'Was eine gute Klinik zu jedem Preis dokumentiert.', intro: 'Jede Installation wird an Versorgung, Laborpartner und Protokolle der jeweiligen Klinik angepasst.', steps: [['01', 'Genauer Umfang', 'Was enthalten ist und welche Diagnostik, Provisorien oder Laborkosten separat anfallen.'], ['02', 'Material und System', 'Kronenmaterial, Implantatsystem oder Füllungsmaterial des Plans.'], ['03', 'Behandlungsrhythmus', 'Voraussichtliche Termine, Heilungsphasen und ob ein zweiter Aufenthalt nötig sein kann.'], ['04', 'Prüfdatum', 'Ein sichtbares Datum zeigt, wann die Klinik die Angaben zuletzt bestätigt hat.']] },
  closing: { eyebrow: 'Ihr Mund ist keine Speisekarte', title: 'Beginnen Sie mit der richtigen Diagnose und vergleichen Sie dann den vollständigen Plan.', text: 'Senden Sie aktuelle Aufnahmen sicher, falls vorhanden. Die Klinik kann vorab eine vorläufige Einschätzung erstellen und vor Ort bestätigen.', primary: 'Beratung planen', secondary: 'Bilder sicher senden' },
  categories: { diagnostics: 'Diagnostik & Planung', prevention: 'Vorsorge & Mundhygiene', restorative: 'Zahnerhalt', endodontics: 'Wurzelkanalbehandlung', surgery: 'Oralchirurgie', prosthetics: 'Kronen & Zahnersatz', implants: 'Implantologie', aesthetic: 'Ästhetische Zahnmedizin', orthodontics: 'Kieferorthopädie', children: 'Kinderzahnmedizin' },
  services: deServices,
}

const fr = {
  ...en,
  navLabel: 'Tarifs',
  metaTitle: 'Tarifs dentaires à Batoumi | Batumi Dental Clinic',
  metaDescription: 'Une liste transparente en laris géorgiens avec inclusions, matériaux et étapes de traitement.',
  templateMetaDescription: 'Aperçu d’une liste transparente en laris géorgiens, prête pour les tarifs, matériaux et inclusions vérifiés de cette clinique.',
  hero: { eyebrow: 'Tarifs · contenu · clarté', title: 'Un prix n’a de sens que si l’on sait ce qu’il comprend.', lead: 'Nous publions les tarifs approuvés par la clinique en laris géorgiens. Pour chaque soin, la page peut préciser le matériau ou le système, les examens, le nombre de visites et les exclusions importantes.', emptyLead: 'Cet aperçu montre comment les tarifs GEL approuvés seront présentés avec les matériaux, les examens, le nombre de visites et les exclusions importantes.', primary: 'Demander un devis personnalisé', secondary: 'Poser une question sur WhatsApp', note: 'Le plan et le tarif définitifs suivent l’examen clinique. Rien n’est ajouté sans discussion.' },
  principlesLabel: 'Comment lire cette liste',
  principles: [['Le GEL d’abord', 'Le tarif officiel de la clinique est toujours indiqué en laris géorgiens.'], ['Le contenu près du prix', 'Les inclusions et exclusions restent à côté du montant.'], ['Un plan avant l’accord', 'Vous recevez un plan détaillé avant le début du traitement.']],
  list: { eyebrow: 'Tarifs approuvés par la clinique', title: 'Des tarifs clairs, classés par type de soins.', intro: 'Seuls les soins et montants confirmés par la clinique apparaissent ici.', verified: 'Dernière vérification', emptyEyebrow: 'Prêt pour les tarifs de cette clinique', emptyTitle: 'La structure est prête. Les tarifs propres à la clinique viennent ensuite.', emptyText: 'Ce modèle de site commercialisable ne reprend jamais les prix d’un autre cabinet. Lors de l’intégration, les tarifs GEL approuvés, les matériaux, les inclusions et la date de vérification sont ajoutés dans un seul fichier central.', emptyAction: 'En attendant, discutez de votre traitement et recevez un devis détaillé.' },
  labels: { from: 'À partir de {price}', onRequest: 'Après évaluation', includes: 'Inclus', excludes: 'Non inclus', materialSystem: 'Matériau / système', visits: 'Visites prévues', duration: 'Durée prévue', diagnostics: 'Examens', note: 'Important', oneVisit: '1 visite', exactVisits: '{count} visites', multipleVisits: '{min}–{max} visites', unit: { treatment: 'traitement', tooth: 'dent', unit: 'élément', jaw: 'mâchoire', arch: 'arcade', session: 'séance' } },
  transparency: { eyebrow: 'Pas de prix d’appel sans contexte', title: 'Ce qu’une bonne clinique précise avec chaque tarif.', intro: 'Chaque installation est adaptée aux soins, laboratoires partenaires et protocoles propres à la clinique.', steps: [['01', 'Contenu exact', 'Ce qui est inclus et les examens, provisoires ou frais de laboratoire facturés séparément.'], ['02', 'Matériau et système', 'Le matériau de la couronne, le système implantaire ou le composite prévu.'], ['03', 'Rythme du traitement', 'Les visites probables, les phases de cicatrisation et la possibilité d’un second séjour.'], ['04', 'Date de vérification', 'Une date visible indique quand la clinique a approuvé les informations.']] },
  closing: { eyebrow: 'Votre bouche n’est pas un menu', title: 'Commencez par le bon diagnostic, puis comparez le plan complet.', text: 'Envoyez vos images récentes de façon sécurisée si vous en avez. La clinique peut préparer une première estimation à confirmer sur place.', primary: 'Planifier une consultation', secondary: 'Envoyer des images en sécurité' },
  categories: { diagnostics: 'Diagnostic & planification', prevention: 'Prévention & hygiène', restorative: 'Dentisterie restauratrice', endodontics: 'Traitement endodontique', surgery: 'Chirurgie orale', prosthetics: 'Couronnes & prothèses', implants: 'Implantologie', aesthetic: 'Dentisterie esthétique', orthodontics: 'Orthodontie', children: 'Dentisterie pédiatrique' },
  services: frServices,
}

const lb = {
  ...en,
  navLabel: 'Präisser',
  metaTitle: 'Zännpräisser zu Batumi | Batumi Dental Clinic',
  metaDescription: 'Eng transparent Präislëscht a georgesche Lari mat Leeschtungen, Material an Behandlungsphasen.',
  templateMetaDescription: 'Virschau vun enger transparenter Präislëscht a georgesche Lari, prett fir déi gepréift Präisser, Materialien a Leeschtunge vun dëser Klinik.',
  hero: { eyebrow: 'Präisser · Ëmfang · Kloerheet', title: 'E Präis seet eréischt eppes, wann Dir wësst, wat dobäi ass.', lead: 'Mir publizéieren vun der Klinik guttgeheescht Präisser a georgesche Lari. Bei all Behandlung kënne Material oder System, Diagnostik, erwaart Visitten a wichteg Ausnamen stoen.', emptyLead: 'Dës Virschau weist, wéi confirméiert GEL-Präisser mat Material, Diagnostik, erwaarte Visitten a wichtegen Ausname publizéiert ginn.', primary: 'Perséinleche Käschteplang ufroen', secondary: 'Iwwer WhatsApp froen', note: 'Den definitive Plang a Präis ginn no der klinescher Ënnersichung festgeluecht. Näischt gëtt ouni Gespréich derbäigesat.' },
  principlesLabel: 'Esou liest Dir dës Lëscht',
  principles: [['GEL als Basis', 'Den offizielle Klinikpräis steet ëmmer a georgesche Lari.'], ['Ëmfang nieft dem Präis', 'Wat abegraff an net abegraff ass, steet direkt beim Montant.'], ['Plang virum Accord', 'Virun der Behandlung kritt Dir en detailléierte Plang.']],
  list: { eyebrow: 'Vun der Klinik guttgeheescht Präislëscht', title: 'Kloer Präisser, no Fleeg organiséiert.', intro: 'Nëmme vun der Klinik confirméiert Behandlungen a Montante stinn hei.', verified: 'Lescht kontrolléiert', emptyEyebrow: 'Prett fir d’Präisser vun dëser Klinik', emptyTitle: 'D’Struktur steet. Elo kommen déi eege Klinikpräisser.', emptyText: 'Dës verkaaftbar Websäit-Virlag iwwerhëlt ni Präisser vun enger anerer Praxis. Beim Onboarding ginn déi guttgeheescht GEL-Präisser, Materialien, Leeschtungen an de Kontroll-Datum zentral aginn.', emptyAction: 'Besprécht bis dohinner Är Behandlung a kritt en detailléierte Käschteplang.' },
  labels: { from: 'Vun {price} un', onRequest: 'No Ënnersichung', includes: 'Abegraff', excludes: 'Net abegraff', materialSystem: 'Material / System', visits: 'Erwaart Visitten', duration: 'Erwaart Dauer', diagnostics: 'Diagnostik', note: 'Wichteg', oneVisit: '1 Visitt', exactVisits: '{count} Visitten', multipleVisits: '{min}–{max} Visitten', unit: { treatment: 'Behandlung', tooth: 'Zant', unit: 'Eenheet', jaw: 'Kifer', arch: 'Zantbou', session: 'Sëtzung' } },
  transparency: { eyebrow: 'Kee Lockpräis ouni Kontext', title: 'Wat eng gutt Klinik bei all Präis festhält.', intro: 'All Installatioun gëtt un d’Fleeg, d’Laborpartner an d’Protokoller vun der Klinik ugepasst.', steps: [['01', 'Genee Leeschtung', 'Wat abegraff ass a wéi eng Diagnostik, provisoresch Aarbecht oder Laborkäschte separat sinn.'], ['02', 'Material a System', 'D’Krounmaterial, d’Implantatsystem oder d’Fëllmaterial vum Plang.'], ['03', 'Behandlungsrhythmus', 'Erwaart Visitten, Heelungsphasen an ob en zweeten Openthalt néideg ka sinn.'], ['04', 'Kontroll-Datum', 'E sichtbaren Datum weist, wéini d’Klinik d’Informatioun confirméiert huet.']] },
  closing: { eyebrow: 'Äre Mond ass kee Menü', title: 'Fänkt mat der richteger Diagnos un a vergläicht dann de ganze Plang.', text: 'Schéckt rezent Biller sécher, wann Dir der hutt. D’Klinik kann am Viraus eng éischt Aschätzung maachen an se op der Plaz confirméieren.', primary: 'Consultatioun plangen', secondary: 'Biller sécher schécken' },
  categories: { diagnostics: 'Diagnostik & Planung', prevention: 'Preventioun & Mondhygiène', restorative: 'Restaurativ Zännmedezin', endodontics: 'Wuerzelkanalbehandlung', surgery: 'Oralchirurgie', prosthetics: 'Krounen & Prothetik', implants: 'Implantologie', aesthetic: 'Ästhetesch Zännmedezin', orthodontics: 'Kieferorthopedie', children: 'Kannerzännmedezin' },
  services: lbServices,
}

const ka = {
  ...en,
  navLabel: 'ფასები',
  metaTitle: 'სტომატოლოგიური ფასები ბათუმში | Batumi Dental Clinic',
  metaDescription: 'გამჭვირვალე ფასების სია ქართულ ლარში, მომსახურების მოცულობით, მასალებითა და მკურნალობის ეტაპებით.',
  templateMetaDescription: 'გამჭვირვალე GEL ფასების სიის წინასწარი ვერსია, მზად ამ კლინიკის დადასტურებული ფასების, მასალებისა და მომსახურებისთვის.',
  hero: { eyebrow: 'ფასი · მოცულობა · სიცხადე', title: 'ფასი მხოლოდ მაშინ არის გასაგები, როცა იცით, რას მოიცავს.', lead: 'ვაქვეყნებთ კლინიკის მიერ დამტკიცებულ ფასებს ქართულ ლარში. თითოეულ მკურნალობასთან შეიძლება ეწეროს მასალა ან სისტემა, დიაგნოსტიკა, მოსალოდნელი ვიზიტები და მნიშვნელოვანი გამონაკლისები.', emptyLead: 'ეს წინასწარი ვერსია აჩვენებს, როგორ გამოქვეყნდება დადასტურებული GEL ფასები მასალასთან, დიაგნოსტიკასთან, მოსალოდნელ ვიზიტებთან და მნიშვნელოვან გამონაკლისებთან ერთად.', primary: 'პერსონალური ხარჯთაღრიცხვის მოთხოვნა', secondary: 'WhatsApp-ზე კითხვა', note: 'საბოლოო გეგმა და ფასი კლინიკური გამოკვლევის შემდეგ დგინდება. შეთანხმების გარეშე არაფერი ემატება.' },
  principlesLabel: 'როგორ წავიკითხოთ სია',
  principles: [['ფასი GEL-ში', 'კლინიკის ოფიციალური ფასი ყოველთვის ქართულ ლარშია მითითებული.'], ['მოცულობა ფასთან ერთად', 'ჩართული და გამორიცხული მომსახურება თანხასთან ახლოს ჩანს.'], ['გეგმა თანხმობამდე', 'მკურნალობის დაწყებამდე მიიღებთ დეტალურ გეგმას.']],
  list: { eyebrow: 'კლინიკის მიერ დამტკიცებული ფასების სია', title: 'მკაფიო ფასები, მოვლის მიმართულებებით.', intro: 'აქ მხოლოდ კლინიკის მიერ დადასტურებული მკურნალობა და თანხები ჩნდება.', verified: 'ბოლოს შემოწმდა', emptyEyebrow: 'მზად არის ამ კლინიკის ფასებისთვის', emptyTitle: 'სტრუქტურა დასრულებულია. შემდეგ ემატება კლინიკის საკუთარი ფასები.', emptyText: 'ეს გასაყიდი ვებსაიტის შაბლონი არასოდეს იღებს სხვა პრაქტიკის ფასებს. კლინიკის ჩართვისას ერთ ცენტრალურ ფაილში ემატება დამტკიცებული GEL ფასები, მასალები, ჩართული მომსახურება და შემოწმების თარიღი.', emptyAction: 'მანამდე განიხილეთ მკურნალობა და მიიღეთ დეტალური ხარჯთაღრიცხვა.' },
  labels: { from: '{price}-დან', onRequest: 'შეფასების შემდეგ', includes: 'შედის', excludes: 'არ შედის', materialSystem: 'მასალა / სისტემა', visits: 'მოსალოდნელი ვიზიტები', duration: 'მოსალოდნელი ხანგრძლივობა', diagnostics: 'დიაგნოსტიკა', note: 'მნიშვნელოვანი', oneVisit: '1 ვიზიტი', exactVisits: '{count} ვიზიტი', multipleVisits: '{min}–{max} ვიზიტი', unit: { treatment: 'მკურნალობა', tooth: 'კბილი', unit: 'ერთეული', jaw: 'ყბა', arch: 'რკალი', session: 'სესია' } },
  transparency: { eyebrow: 'ფასდაკლება კონტექსტის გარეშე — არა', title: 'რას უთითებს კარგი კლინიკა თითოეულ ფასთან.', intro: 'ამ ვებსაიტის თითოეული ვერსია ერგება კლინიკის საკუთარ მომსახურებას, ლაბორატორიულ პარტნიორებსა და პროტოკოლებს.', steps: [['01', 'ზუსტი მოცულობა', 'რა შედის ფასში და რომელი დიაგნოსტიკა, დროებითი კონსტრუქცია ან ლაბორატორიული ხარჯია ცალკე.'], ['02', 'მასალა და სისტემა', 'გეგმაში გამოყენებული გვირგვინის მასალა, იმპლანტის სისტემა ან საბჟენი მასალა.'], ['03', 'მკურნალობის რიტმი', 'სავარაუდო ვიზიტები, შეხორცების ეტაპები და შეიძლება თუ არა მეორე ვიზიტი გახდეს საჭირო.'], ['04', 'შემოწმების თარიღი', 'ხილული თარიღი აჩვენებს, როდის დაამტკიცა კლინიკამ ინფორმაცია.']] },
  closing: { eyebrow: 'პირი მენიუ არ არის', title: 'დაიწყეთ სწორი დიაგნოზით და შემდეგ შეადარეთ სრული გეგმა.', text: 'თუ გაქვთ, უსაფრთხოდ გამოგზავნეთ ახალი სურათები. კლინიკას შეუძლია წინასწარი მონახაზი მოამზადოს და ადგილზე დაადასტუროს.', primary: 'კონსულტაციის დაგეგმვა', secondary: 'სურათების უსაფრთხოდ გაგზავნა' },
  categories: { diagnostics: 'დიაგნოსტიკა და დაგეგმვა', prevention: 'პრევენცია და ჰიგიენა', restorative: 'რესტავრაციული სტომატოლოგია', endodontics: 'ფესვის არხის მკურნალობა', surgery: 'ქირურგიული სტომატოლოგია', prosthetics: 'გვირგვინები და პროთეზირება', implants: 'იმპლანტოლოგია', aesthetic: 'ესთეტიკური სტომატოლოგია', orthodontics: 'ორთოდონტია', children: 'ბავშვთა სტომატოლოგია' },
  services: kaServices,
}

export const pricesContent = { nl, de, fr, lb, en, ka }
