export const teamSectionContent = {
  nl: {
    eyebrow: 'Uw klinische team',
    title: 'Weet wie uw dossier beoordeelt.',
    intro: 'Voordat u beslist, hoort duidelijk te zijn wie uw dossier bekijkt en met wie u het behandelvoorstel bespreekt. Namen, foto’s en professionele registraties publiceren we daarom pas nadat de kliniek ze schriftelijk heeft geverifieerd.',
    imageNote: 'Conceptbeeld · geen medewerkers van de kliniek',
    verification: 'Dit zijn nog geen medewerkersprofielen. We nemen geen namen, titels, specialismen of registraties aan.',
    profiles: [
      { number: '01', role: 'Behandelend tandarts', status: 'Profiel volgt na verificatie', text: 'Hier verschijnt de geverifieerde tandarts die uw onderzoek, diagnose en behandelvoorstel met u bespreekt.' },
      { number: '02', role: 'Klinische ondersteuning', status: 'Profiel volgt na verificatie', text: 'Hier verschijnt de geverifieerde persoon die de behandeling praktisch en klinisch ondersteunt.' },
      { number: '03', role: 'Patiëntcoördinatie', status: 'Profiel volgt na verificatie', text: 'Hier verschijnt het geverifieerde contact voor planning, taalvoorkeur en praktische vragen rond uw afspraak of verblijf.' },
    ],
    cta: 'Vraag om een kennismaking',
  },
  de: {
    eyebrow: 'Ihr klinisches Team',
    title: 'Wissen Sie, wer Ihren Fall prüft.',
    intro: 'Bevor Sie entscheiden, sollte klar sein, wer Ihren Fall prüft und mit wem Sie den Behandlungsvorschlag besprechen. Namen, Fotos und berufliche Registrierungen veröffentlichen wir deshalb erst nach schriftlicher Bestätigung durch die Klinik.',
    imageNote: 'Konzeptbild · keine Mitarbeitenden der Klinik',
    verification: 'Dies sind noch keine Mitarbeiterprofile. Namen, Titel, Fachgebiete oder Registrierungen werden nicht vorausgesetzt.',
    profiles: [
      { number: '01', role: 'Behandelnde Zahnärztin oder behandelnder Zahnarzt', status: 'Profil nach Verifizierung', text: 'Hier erscheint die verifizierte Person, die Untersuchung, Diagnose und Behandlungsvorschlag mit Ihnen bespricht.' },
      { number: '02', role: 'Klinische Unterstützung', status: 'Profil nach Verifizierung', text: 'Hier erscheint die verifizierte Person, die Ihre Behandlung praktisch und klinisch unterstützt.' },
      { number: '03', role: 'Patientenkoordination', status: 'Profil nach Verifizierung', text: 'Hier erscheint der verifizierte Kontakt für Planung, Sprachwunsch und praktische Fragen zu Termin oder Aufenthalt.' },
    ],
    cta: 'Ein Kennenlernen anfragen',
  },
  fr: {
    eyebrow: 'Votre équipe clinique',
    title: 'Sachez qui étudie votre dossier.',
    intro: 'Avant de décider, vous devez savoir clairement qui étudie votre dossier et avec qui vous discuterez de la proposition de traitement. Les noms, photos et inscriptions professionnelles ne seront donc publiés qu’après vérification écrite par la clinique.',
    imageNote: 'Image conceptuelle · il ne s’agit pas de l’équipe de la clinique',
    verification: 'Ces emplacements ne constituent pas encore des profils de membres de l’équipe. Aucun nom, titre, domaine d’expertise ou numéro d’inscription n’est présumé.',
    profiles: [
      { number: '01', role: 'Dentiste en charge du traitement', status: 'Profil après vérification', text: 'La personne vérifiée qui discutera avec vous de l’examen, du diagnostic et de la proposition de traitement apparaîtra ici.' },
      { number: '02', role: 'Assistance clinique', status: 'Profil après vérification', text: 'La personne vérifiée qui apportera un soutien pratique et clinique au traitement apparaîtra ici.' },
      { number: '03', role: 'Coordination des patients', status: 'Profil après vérification', text: 'Le contact vérifié pour le planning, la langue souhaitée et les questions pratiques liées au rendez-vous ou au séjour apparaîtra ici.' },
    ],
    cta: 'Demander une présentation',
  },
  lb: {
    eyebrow: 'Äert klinescht Team',
    title: 'Wësst, wien Ären Dossier iwwerpréift.',
    intro: 'Éier Dir entscheet, soll kloer sinn, wien Ären Dossier kuckt a mat wiem Dir d’Behandlungspropositioun beschwätzt. Nimm, Fotoen a berufflech Registréierungen gi réischt no der schrëftlecher Verifizéierung duerch d’Klinik publizéiert.',
    imageNote: 'Konzeptbild · keng Mataarbechter vun der Klinik',
    verification: 'Dës Plaze sinn nach keng Mataarbechterprofiler. Mir huelen keng Nimm, Titelen, Spezialisatiounen oder Registréierungen un.',
    profiles: [
      { number: '01', role: 'Behandelnd Zänndoktesch oder behandelnden Zänndokter', status: 'Profil no der Verifizéierung', text: 'Hei kënnt déi verifizéiert Persoun, déi Är Ënnersichung, Diagnos a Behandlungspropositioun mat Iech beschwätzt.' },
      { number: '02', role: 'Klinesch Ënnerstëtzung', status: 'Profil no der Verifizéierung', text: 'Hei kënnt déi verifizéiert Persoun, déi Är Behandlung praktesch a klinesch ënnerstëtzt.' },
      { number: '03', role: 'Patientekoordinatioun', status: 'Profil no der Verifizéierung', text: 'Hei kënnt de verifizéierte Kontakt fir Planung, Sproochpreferenz a praktesch Froen zu Ärem Rendez-vous oder Openthalt.' },
    ],
    cta: 'E Kenneléiere ufroen',
  },
  en: {
    eyebrow: 'Your clinical team',
    title: 'Know who reviews your case.',
    intro: 'Before you decide, it should be clear who reviews your case and who will discuss the treatment proposal with you. Names, photographs and professional registrations will therefore be published only after written verification by the clinic.',
    imageNote: 'Concept image · not the clinic’s staff',
    verification: 'These are not staff profiles yet. No names, titles, specialties or registrations are being assumed.',
    profiles: [
      { number: '01', role: 'Treating dentist', status: 'Profile pending verification', text: 'The verified dentist who discusses your examination, diagnosis and treatment proposal with you will appear here.' },
      { number: '02', role: 'Clinical support', status: 'Profile pending verification', text: 'The verified person providing practical and clinical support during treatment will appear here.' },
      { number: '03', role: 'Patient coordination', status: 'Profile pending verification', text: 'The verified contact for scheduling, language preferences and practical questions about your appointment or stay will appear here.' },
    ],
    cta: 'Request an introduction',
  },
  ka: {
    eyebrow: 'თქვენი კლინიკური გუნდი',
    title: 'იცოდეთ, ვინ განიხილავს თქვენს შემთხვევას.',
    intro: 'გადაწყვეტილების მიღებამდე მკაფიოდ უნდა იცოდეთ, ვინ განიხილავს თქვენს დოკუმენტაციას და ვისთან განიხილავთ მკურნალობის შეთავაზებას. ამიტომ სახელები, ფოტოები და პროფესიული რეგისტრაციის მონაცემები მხოლოდ კლინიკის წერილობითი გადამოწმების შემდეგ გამოქვეყნდება.',
    imageNote: 'კონცეფციის სურათი · არა კლინიკის თანამშრომლები',
    verification: 'ეს ადგილები ჯერ თანამშრომელთა პროფილები არ არის. არც სახელი, არც წოდება, არც სპეციალიზაცია და არც რეგისტრაცია წინასწარ არ იგულისხმება.',
    profiles: [
      { number: '01', role: 'მკურნალი სტომატოლოგი', status: 'პროფილი გამოქვეყნდება გადამოწმების შემდეგ', text: 'აქ გამოჩნდება გადამოწმებული სტომატოლოგი, რომელიც თქვენთან ერთად განიხილავს გამოკვლევას, დიაგნოზსა და მკურნალობის შეთავაზებას.' },
      { number: '02', role: 'კლინიკური მხარდაჭერა', status: 'პროფილი გამოქვეყნდება გადამოწმების შემდეგ', text: 'აქ გამოჩნდება გადამოწმებული პირი, რომელიც მკურნალობას პრაქტიკულად და კლინიკურად დაეხმარება.' },
      { number: '03', role: 'პაციენტის კოორდინაცია', status: 'პროფილი გამოქვეყნდება გადამოწმების შემდეგ', text: 'აქ გამოჩნდება გადამოწმებული საკონტაქტო პირი ვიზიტის ან ყოფნის დაგეგმვის, სასურველი ენისა და პრაქტიკული კითხვებისთვის.' },
    ],
    cta: 'მოითხოვეთ გაცნობა გადამოწმებულ გუნდთან',
  },
}
