const treatmentData = {
  nl: [
    { number: '01', name: 'Controle & preventie', desc: 'Periodieke controle en persoonlijk preventieadvies, met aanvullende diagnostiek alleen wanneer die klinisch nodig is.', tags: ['Onderzoek', 'Preventieadvies', 'Controle op maat'] },
    { number: '02', name: 'Mondhygiëne & tandvleeszorg', desc: 'Professionele reiniging en beoordeling van het tandvlees, afgestemd op tandplak, tandsteen en ontstekingsrisico.', tags: ['Gebitsreiniging', 'Tandvleescontrole', 'Thuisadvies'] },
    { number: '03', name: 'Vullingen & tandherstel', desc: 'Herstel van cariës, slijtage of kleine beschadigingen met behoud van zoveel mogelijk gezond tandweefsel.', tags: ['Cariësbehandeling', 'Composiet', 'Functieherstel'] },
    { number: '04', name: 'Wortelkanaalbehandeling', desc: 'Behandeling van ontstoken of beschadigd tandzenuwweefsel om infectie te beheersen en de tand waar mogelijk te behouden.', tags: ['Diagnostiek', 'Kanaalreiniging', 'Nacontrole'] },
    { number: '05', name: 'Kronen, bruggen & kunstgebitten', desc: 'Vaste of uitneembare voorzieningen voor beschadigde of ontbrekende tanden, afgestemd op beet, pasvorm en onderhoud.', tags: ['Kronen & bruggen', 'Protheses', 'Pasvormcontrole'] },
    { number: '06', name: 'Implantaten & kaakchirurgie', desc: 'Implantaten en passende chirurgische ingrepen na medische en radiologische beoordeling; genezing kan meerdere fasen vereisen.', tags: ['3D-diagnostiek', 'Chirurgische planning', 'Gefaseerde nazorg'] },
    { number: '07', name: 'Orthodontie & aligners', desc: 'Correctie van tandstand en beet met vaste apparatuur of transparante aligners, na orthodontische beoordeling.', tags: ['Beetanalyse', 'Vaste beugel', 'Aligners'] },
    { number: '08', name: 'Esthetische tandheelkunde', desc: 'Behandelingen voor kleur, vorm en verhoudingen, met aandacht voor mondgezondheid en behoud van tandweefsel.', tags: ['Facings', 'Bleken', 'Glimlachplanning'] },
    { number: '09', name: 'Kindertandheelkunde', desc: 'Leeftijdsgerichte controle, preventie en behandeling met aandacht voor comfort, vertrouwen en samenwerking.', tags: ['Gewenning', 'Preventie', 'Ouderadvies'] },
    { number: '10', name: 'Pijn- & spoedzorg', desc: 'Beoordeling van acute tandpijn, zwelling, trauma of beschadigd tandwerk, waarbij triage en onderzoek de vervolgstap bepalen.', tags: ['Triage', 'Pijnanalyse', 'Vervolgplan'] },
  ],
  de: [
    { number: '01', name: 'Kontrolle & Vorsorge', desc: 'Regelmäßige Kontrolle und individuelle Vorsorgeberatung; weitere Diagnostik nur bei klinischer Indikation.', tags: ['Untersuchung', 'Vorsorgeberatung', 'Individueller Recall'] },
    { number: '02', name: 'Mundhygiene & Zahnfleischpflege', desc: 'Professionelle Reinigung und Beurteilung des Zahnfleischs, abgestimmt auf Beläge, Zahnstein und Entzündungsrisiko.', tags: ['Zahnreinigung', 'Zahnfleischkontrolle', 'Häusliche Pflege'] },
    { number: '03', name: 'Füllungen & Zahnerhalt', desc: 'Versorgung von Karies, Verschleiß oder kleineren Schäden unter möglichst weitgehendem Erhalt gesunder Zahnsubstanz.', tags: ['Kariesbehandlung', 'Komposit', 'Funktionserhalt'] },
    { number: '04', name: 'Wurzelkanalbehandlung', desc: 'Behandlung entzündeten oder geschädigten Nervengewebes, um die Infektion zu kontrollieren und den Zahn möglichst zu erhalten.', tags: ['Diagnostik', 'Kanalaufbereitung', 'Nachkontrolle'] },
    { number: '05', name: 'Kronen, Brücken & Zahnersatz', desc: 'Festsitzende oder herausnehmbare Versorgungen für beschädigte oder fehlende Zähne, abgestimmt auf Biss, Passform und Pflege.', tags: ['Kronen & Brücken', 'Prothesen', 'Passformkontrolle'] },
    { number: '06', name: 'Implantate & Oralchirurgie', desc: 'Implantate und geeignete chirurgische Eingriffe nach medizinischer und radiologischer Beurteilung; die Heilung kann mehrere Phasen erfordern.', tags: ['3D-Diagnostik', 'Chirurgische Planung', 'Stufenweise Nachsorge'] },
    { number: '07', name: 'Kieferorthopädie & Aligner', desc: 'Korrektur von Zahnstellung und Biss mit fester Apparatur oder transparenten Alignern nach kieferorthopädischer Beurteilung.', tags: ['Bissanalyse', 'Feste Zahnspange', 'Aligner'] },
    { number: '08', name: 'Ästhetische Zahnmedizin', desc: 'Behandlungen von Farbe, Form und Proportionen unter Berücksichtigung der Mundgesundheit und des Erhalts der Zahnsubstanz.', tags: ['Veneers', 'Bleaching', 'Lächelnplanung'] },
    { number: '09', name: 'Kinderzahnheilkunde', desc: 'Altersgerechte Kontrolle, Vorsorge und Behandlung mit besonderem Augenmerk auf Komfort, Vertrauen und Mitarbeit.', tags: ['Eingewöhnung', 'Vorsorge', 'Elternberatung'] },
    { number: '10', name: 'Schmerz- & Akutversorgung', desc: 'Abklärung akuter Zahnschmerzen, Schwellungen, Verletzungen oder beschädigter Versorgungen; Triage und Untersuchung bestimmen das weitere Vorgehen.', tags: ['Triage', 'Schmerzdiagnostik', 'Folgeplan'] },
  ],
  fr: [
    { number: '01', name: 'Contrôle & prévention', desc: 'Contrôle périodique et conseils préventifs personnalisés, avec examens complémentaires uniquement s’ils sont cliniquement indiqués.', tags: ['Examen', 'Conseils préventifs', 'Suivi adapté'] },
    { number: '02', name: 'Hygiène bucco-dentaire & soins des gencives', desc: 'Nettoyage professionnel et évaluation des gencives selon la plaque, le tartre et le risque inflammatoire.', tags: ['Nettoyage dentaire', 'Contrôle gingival', 'Conseils à domicile'] },
    { number: '03', name: 'Obturations & restauration dentaire', desc: 'Traitement des caries, de l’usure ou de petites lésions en préservant autant que possible les tissus dentaires sains.', tags: ['Traitement des caries', 'Composite', 'Restauration fonctionnelle'] },
    { number: '04', name: 'Traitement de canal', desc: 'Traitement de la pulpe inflammée ou lésée afin de maîtriser l’infection et de conserver la dent lorsque cela est possible.', tags: ['Diagnostic', 'Nettoyage canalaire', 'Contrôle de suivi'] },
    { number: '05', name: 'Couronnes, bridges & prothèses', desc: 'Solutions fixes ou amovibles pour les dents abîmées ou absentes, adaptées à l’occlusion, à l’ajustement et à l’entretien.', tags: ['Couronnes & bridges', 'Prothèses', 'Contrôle d’ajustement'] },
    { number: '06', name: 'Implants & chirurgie orale', desc: 'Implants et interventions chirurgicales adaptées après évaluation médicale et radiologique; la cicatrisation peut nécessiter plusieurs étapes.', tags: ['Diagnostic 3D', 'Planification chirurgicale', 'Suivi par étapes'] },
    { number: '07', name: 'Orthodontie & aligneurs', desc: 'Correction de la position des dents et de l’occlusion par appareil fixe ou aligneurs transparents, après bilan orthodontique.', tags: ['Analyse occlusale', 'Appareil fixe', 'Aligneurs'] },
    { number: '08', name: 'Dentisterie esthétique', desc: 'Traitements portant sur la couleur, la forme et les proportions, dans le respect de la santé bucco-dentaire et des tissus dentaires.', tags: ['Facettes', 'Blanchiment', 'Planification du sourire'] },
    { number: '09', name: 'Dentisterie pédiatrique', desc: 'Contrôle, prévention et traitement adaptés à l’âge, avec une attention particulière au confort, à la confiance et à la coopération.', tags: ['Mise en confiance', 'Prévention', 'Conseils aux parents'] },
    { number: '10', name: 'Douleur & soins dentaires urgents', desc: 'Évaluation d’une douleur aiguë, d’un gonflement, d’un traumatisme ou d’une restauration endommagée; le triage et l’examen déterminent la suite.', tags: ['Triage', 'Évaluation de la douleur', 'Plan de suivi'] },
  ],
  lb: [
    { number: '01', name: 'Kontroll & Preventioun', desc: 'Reegelméisseg Kontroll a perséinlech Preventiounsberodung; weider Diagnostik nëmmen, wann si klinesch ubruecht ass.', tags: ['Ënnersichung', 'Preventiounsberodung', 'Kontroll op Mooss'] },
    { number: '02', name: 'Mondhygiène & Zännfleeschfleeg', desc: 'Professionell Zännreinigung an Evaluatioun vum Zännfleesch, ugepasst un Zännplack, Zännsteen an Entzündungsrisiko.', tags: ['Zännreinigung', 'Zännfleeschkontroll', 'Fleeg doheem'] },
    { number: '03', name: 'Fëllungen & Zännrestauratioun', desc: 'Behandlung vu Karies, Ofnotzung oder klenge Schied, mat Erhale vu sou vill gesonder Zännsubstanz wéi méiglech.', tags: ['Kariesbehandlung', 'Komposit', 'Funktiounserhalt'] },
    { number: '04', name: 'Wuerzelkanalbehandlung', desc: 'Behandlung vum entzündeten oder beschiedegten Zännnervegewebe, fir d’Infektioun ze kontrolléieren an den Zänn wa méiglech ze erhalen.', tags: ['Diagnostik', 'Kanäl botzen', 'Nokontroll'] },
    { number: '05', name: 'Krounen, Brécken & Protheesen', desc: 'Fest oder eraushuelbar Versuergunge fir beschiedegt oder feelend Zänn, ugepasst un de Bëss, d’Passform an d’Fleeg.', tags: ['Krounen & Brécken', 'Protheesen', 'Passformkontroll'] },
    { number: '06', name: 'Implantater & Oralchirurgie', desc: 'Implantater a passend chirurgesch Agrëffer no medezinescher a radiologescher Bewäertung; d’Heelung kann e puer Phase verlaangen.', tags: ['3D-Diagnostik', 'Chirurgesch Planung', 'Nofleeg a Phasen'] },
    { number: '07', name: 'Kieferorthopädie & Aligner', desc: 'Korrektur vun der Zännstellung an dem Bëss mat fester Apparatur oder transparenten Aligneren, no enger orthodontescher Bewäertung.', tags: ['Bëssanalys', 'Fest Apparatur', 'Aligner'] },
    { number: '08', name: 'Ästhetesch Zännmedezin', desc: 'Behandlunge vu Faarf, Form a Proportiounen, mat Respekt fir d’Mondgesondheet an den Erhalt vun der Zännsubstanz.', tags: ['Veneers', 'Bleechung', 'Laachplanung'] },
    { number: '09', name: 'Kannerzännmedezin', desc: 'Altersgerecht Kontroll, Preventioun a Behandlung mat Opmierksamkeet fir Komfort, Vertrauen a Mataarbecht.', tags: ['Gewinnung', 'Preventioun', 'Eltereberodung'] },
    { number: '10', name: 'Péng & dréngend Zännfleeg', desc: 'Bewäertung vun akuter Zännpéng, Schwellung, Verletzung oder enger beschiedegter Versuergung; Triage an Ënnersichung bestëmmen de nächste Schrëtt.', tags: ['Triage', 'Péngbewäertung', 'Weiderplang'] },
  ],
  en: [
    { number: '01', name: 'Check-ups & prevention', desc: 'Routine examinations and personal prevention advice, with additional diagnostics only when clinically indicated.', tags: ['Examination', 'Prevention advice', 'Tailored recall'] },
    { number: '02', name: 'Dental hygiene & gum care', desc: 'Professional cleaning and gum assessment tailored to plaque, tartar and the risk of inflammation.', tags: ['Professional cleaning', 'Gum assessment', 'Home-care advice'] },
    { number: '03', name: 'Fillings & tooth restoration', desc: 'Treatment of decay, wear or minor damage while preserving as much healthy tooth structure as possible.', tags: ['Decay treatment', 'Composite', 'Function restoration'] },
    { number: '04', name: 'Root canal treatment', desc: 'Treatment of inflamed or damaged dental pulp to control infection and retain the tooth where possible.', tags: ['Diagnostics', 'Canal cleaning', 'Follow-up review'] },
    { number: '05', name: 'Crowns, bridges & dentures', desc: 'Fixed or removable solutions for damaged or missing teeth, planned around bite, fit and maintenance.', tags: ['Crowns & bridges', 'Dentures', 'Fit review'] },
    { number: '06', name: 'Implants & oral surgery', desc: 'Implants and suitable surgical procedures following medical and radiographic assessment; healing may require several stages.', tags: ['3D diagnostics', 'Surgical planning', 'Phased aftercare'] },
    { number: '07', name: 'Orthodontics & aligners', desc: 'Correction of tooth position and bite with fixed appliances or clear aligners following orthodontic assessment.', tags: ['Bite analysis', 'Fixed braces', 'Clear aligners'] },
    { number: '08', name: 'Aesthetic dentistry', desc: 'Treatments addressing colour, shape and proportion while considering oral health and preserving tooth structure.', tags: ['Veneers', 'Whitening', 'Smile planning'] },
    { number: '09', name: 'Children’s dentistry', desc: 'Age-appropriate examination, prevention and treatment with attention to comfort, trust and cooperation.', tags: ['Familiarisation', 'Prevention', 'Parent guidance'] },
    { number: '10', name: 'Pain & urgent dental care', desc: 'Assessment of acute dental pain, swelling, trauma or damaged dental work, with triage and examination determining the next step.', tags: ['Triage', 'Pain assessment', 'Next-step plan'] },
  ],
  ka: [
    { number: '01', name: 'კონტროლი და პრევენცია', desc: 'პერიოდული შემოწმება და ინდივიდუალური პრევენციული რეკომენდაციები; დამატებითი დიაგნოსტიკა მხოლოდ კლინიკური ჩვენების შემთხვევაში.', tags: ['გამოკვლევა', 'პრევენციული რჩევა', 'ინდივიდუალური კონტროლი'] },
    { number: '02', name: 'პირის ღრუს ჰიგიენა და ღრძილების მოვლა', desc: 'პროფესიული წმენდა და ღრძილების შეფასება ნადების, კბილის ქვისა და ანთების რისკის გათვალისწინებით.', tags: ['პროფესიული წმენდა', 'ღრძილების შეფასება', 'სახლში მოვლის რჩევა'] },
    { number: '03', name: 'ბჟენები და კბილის აღდგენა', desc: 'კარიესის, ცვეთის ან მცირე დაზიანების აღდგენა ჯანსაღი კბილის ქსოვილის მაქსიმალურად შენარჩუნებით.', tags: ['კარიესის მკურნალობა', 'კომპოზიტი', 'ფუნქციის აღდგენა'] },
    { number: '04', name: 'ფესვის არხის მკურნალობა', desc: 'ანთებული ან დაზიანებული კბილის პულპის მკურნალობა ინფექციის კონტროლისა და, შესაძლებლობის შემთხვევაში, კბილის შენარჩუნებისთვის.', tags: ['დიაგნოსტიკა', 'არხების დამუშავება', 'შემდგომი კონტროლი'] },
    { number: '05', name: 'გვირგვინები, ხიდები და პროთეზები', desc: 'ფიქსირებული ან მოსახსნელი კონსტრუქციები დაზიანებული ან დაკარგული კბილებისთვის, თანკბილვის, მორგებისა და მოვლის გათვალისწინებით.', tags: ['გვირგვინები და ხიდები', 'პროთეზები', 'მორგების კონტროლი'] },
    { number: '06', name: 'იმპლანტები და პირის ღრუს ქირურგია', desc: 'იმპლანტები და შესაბამისი ქირურგიული პროცედურები სამედიცინო და რენტგენოლოგიური შეფასების შემდეგ; შეხორცებას შეიძლება რამდენიმე ეტაპი დასჭირდეს.', tags: ['3D დიაგნოსტიკა', 'ქირურგიული დაგეგმვა', 'ეტაპობრივი შემდგომი მოვლა'] },
    { number: '07', name: 'ორთოდონტია და გამჭვირვალე კაპები', desc: 'კბილების პოზიციისა და თანკბილვის კორექცია ბრეკეტებით ან გამჭვირვალე კაპებით, ორთოდონტიული შეფასების შემდეგ.', tags: ['თანკბილვის ანალიზი', 'ბრეკეტები', 'გამჭვირვალე კაპები'] },
    { number: '08', name: 'ესთეტიკური სტომატოლოგია', desc: 'კბილის ფერის, ფორმისა და პროპორციების შეცვლაზე მიმართული მკურნალობა პირის ღრუს ჯანმრთელობისა და ქსოვილის შენარჩუნების გათვალისწინებით.', tags: ['ვინირები', 'გათეთრება', 'ღიმილის დაგეგმვა'] },
    { number: '09', name: 'ბავშვთა სტომატოლოგია', desc: 'ასაკზე მორგებული შემოწმება, პრევენცია და მკურნალობა კომფორტის, ნდობისა და თანამშრომლობის გათვალისწინებით.', tags: ['ადაპტაცია', 'პრევენცია', 'მშობლისთვის რჩევა'] },
    { number: '10', name: 'ტკივილი და გადაუდებელი სტომატოლოგიური დახმარება', desc: 'მწვავე კბილის ტკივილის, შეშუპების, ტრავმის ან დაზიანებული კონსტრუქციის შეფასება, სადაც შემდეგ ნაბიჯს ტრიაჟი და გამოკვლევა განსაზღვრავს.', tags: ['ტრიაჟი', 'ტკივილის შეფასება', 'შემდგომი გეგმა'] },
  ],
}

const treatmentTimes = {
  nl: ['Meestal 1 afspraak', 'Meestal 1 afspraak', 'Na onderzoek', 'Soms meerdere afspraken', 'Persoonlijk gepland', 'Vaak meerdere fasen', 'Langduriger traject', 'Na esthetische beoordeling', 'Leeftijdsgericht', 'Prioriteit na triage'],
  de: ['Meist 1 Termin', 'Meist 1 Termin', 'Nach Untersuchung', 'Mitunter mehrere Termine', 'Individuell geplant', 'Oft mehrere Phasen', 'Längerer Behandlungsweg', 'Nach ästhetischer Beurteilung', 'Altersgerecht', 'Priorität nach Triage'],
  fr: ['Le plus souvent, 1 rendez-vous', 'Le plus souvent, 1 rendez-vous', 'Après examen', 'Parfois plusieurs rendez-vous', 'Planification individuelle', 'Souvent en plusieurs étapes', 'Parcours plus long', 'Après bilan esthétique', 'Adapté à l’âge', 'Priorité selon le triage'],
  lb: ['Meeschtens 1 Rendez-vous', 'Meeschtens 1 Rendez-vous', 'No der Ënnersichung', 'Heiansdo e puer Rendez-vousen', 'Individuell geplangt', 'Dacks a méi Phase', 'Méi laangen Oflaf', 'No ästhetescher Bewäertung', 'Altersgerecht', 'Prioritéit nom Triage'],
  en: ['Usually 1 appointment', 'Usually 1 appointment', 'After examination', 'Sometimes several appointments', 'Individually planned', 'Often several stages', 'Longer care plan', 'After aesthetic assessment', 'Age-appropriate', 'Priority after triage'],
  ka: ['ჩვეულებრივ 1 ვიზიტი', 'ჩვეულებრივ 1 ვიზიტი', 'გამოკვლევის შემდეგ', 'ზოგჯერ რამდენიმე ვიზიტი', 'ინდივიდუალური დაგეგმვა', 'ხშირად რამდენიმე ეტაპი', 'ხანგრძლივი გეგმა', 'ესთეტიკური შეფასების შემდეგ', 'ასაკზე მორგებული', 'პრიორიტეტი ტრიაჟის მიხედვით'],
}

export const treatmentContent = Object.fromEntries(
  Object.entries(treatmentData).map(([locale, treatments]) => [
    locale,
    treatments.map((treatment, index) => ({ ...treatment, time: treatmentTimes[locale][index] })),
  ]),
)
