export const trustContent = {
  nl: {
    team: {
      eyebrow: 'De mensen achter uw behandeling',
      title: 'Vertrouwen begint met weten wie er voor u staat.',
      intro: 'Elke kliniek is uniek. Hier krijgt iedere tandarts daarom ruimte voor een echt profiel: ervaring, behandelgebieden, talen en controleerbare kwalificaties — zonder anonieme stockportretten of algemene claims.',
      emptyTitle: 'Uw team wordt het gezicht van deze website.',
      emptyText: 'Deze verkoopdemo toont bewust nog geen verzonnen medewerkers. Voeg de geverifieerde profielen van de kliniek toe en deze ruimte verandert in een persoonlijke kennismaking.',
      emptyLabel: 'Klaar voor echte kliniekgegevens',
      emptyMonogram: 'TEAM',
      emptySlots: [
        ['01', 'Tandartsprofiel', 'Naam, portret, rol en persoonlijke visie'],
        ['02', 'Professionele kwalificaties', 'Opleiding, registratie en relevante nascholing'],
        ['03', 'Talen & behandelgebieden', 'Duidelijkheid voor lokale en internationale patiënten'],
      ],
      qualifications: 'Kwalificaties',
      registration: 'Professionele registratie',
      languages: 'Talen',
      treatments: 'Behandelgebieden',
      verify: 'Controleer bron',
      contact: 'Maak kennis met het team',
    },
    credentials: {
      eyebrow: 'Kwaliteit die controleerbaar is',
      title: 'Persoonlijke kwalificaties en kliniekcertificaten zijn niet hetzelfde.',
      intro: 'Diploma’s en registraties horen bij de behandelaar. Vergunningen, sterilisatieprotocollen en kwaliteitscertificaten horen bij de kliniek. Wij presenteren ze apart, met uitgevende instantie en geldigheidsgegevens.',
      dentistTitle: 'Bij iedere tandarts',
      dentistText: 'Opleiding, professionele registratie, relevante nascholing en een controlelink wanneer die beschikbaar is.',
      clinicTitle: 'Bij de kliniek',
      clinicText: 'Vergunningen, kwaliteitscertificaten en aantoonbare protocollen met uitgever, nummer, datum en geldigheid.',
      emptyLabel: 'Invulstructuur',
      emptyNote: 'Alleen schriftelijk geverifieerde documenten worden als bewijs gepubliceerd.',
      issuedBy: 'Uitgegeven door',
      issuedOn: 'Uitgegeven op',
      validUntil: 'Geldig tot',
      identifier: 'Referentie',
      view: 'Bekijk verificatie',
    },
    reviews: {
      eyebrow: 'Ervaringen met een herkomst',
      title: 'Echte woorden. Altijd terug te leiden naar de bron.',
      intro: 'Een beoordeling wordt alleen gepubliceerd met toestemming, naamweergave en een werkende bronlink. Geen verzonnen sterren, geen oncontroleerbare aantallen.',
      emptyTitle: 'Ruimte voor echte patiëntervaringen.',
      emptyText: 'Na aansluiting van de officiële reviewbron verschijnen hier geselecteerde, toestemming-gedragen ervaringen. De pagina blijft rustig en geloofwaardig — ook zonder reviewdata.',
      source: 'Lees bij de bron',
    },
    socials: {
      title: 'Volg de kliniek',
      text: 'Bekijk het dagelijkse werk, het team en nieuws via de officiële kanalen.',
      facebook: 'Facebook',
      instagram: 'Instagram',
      pending: 'Officiële link volgt na verificatie',
    },
  },
  de: {
    team: {
      eyebrow: 'Die Menschen hinter Ihrer Behandlung',
      title: 'Vertrauen beginnt damit, zu wissen, wer für Sie da ist.',
      intro: 'Jede Klinik ist einzigartig. Deshalb erhält jede Zahnärztin und jeder Zahnarzt ein echtes Profil mit Erfahrung, Behandlungsschwerpunkten, Sprachen und überprüfbaren Qualifikationen — ohne anonyme Stockporträts oder pauschale Behauptungen.',
      emptyTitle: 'Ihr Team wird zum Gesicht dieser Website.',
      emptyText: 'Diese Verkaufsdemo zeigt bewusst keine erfundenen Mitarbeitenden. Ergänzen Sie die verifizierten Klinikprofile und dieser Bereich wird zu einer persönlichen Vorstellung.',
      emptyLabel: 'Bereit für echte Klinikdaten',
      emptyMonogram: 'TEAM',
      emptySlots: [
        ['01', 'Zahnarztprofil', 'Name, Porträt, Funktion und persönliche Haltung'],
        ['02', 'Berufliche Qualifikationen', 'Ausbildung, Registrierung und relevante Fortbildung'],
        ['03', 'Sprachen & Schwerpunkte', 'Klarheit für lokale und internationale Patienten'],
      ],
      qualifications: 'Qualifikationen',
      registration: 'Berufliche Registrierung',
      languages: 'Sprachen',
      treatments: 'Behandlungsschwerpunkte',
      verify: 'Quelle prüfen',
      contact: 'Das Team kennenlernen',
    },
    credentials: {
      eyebrow: 'Überprüfbare Qualität',
      title: 'Persönliche Qualifikationen und Klinikzertifikate sind nicht dasselbe.',
      intro: 'Abschlüsse und Registrierungen gehören zur behandelnden Person. Zulassungen, Sterilisationsprotokolle und Qualitätszertifikate gehören zur Klinik. Wir zeigen beides getrennt, jeweils mit Aussteller und Gültigkeit.',
      dentistTitle: 'Bei jeder behandelnden Person',
      dentistText: 'Ausbildung, berufliche Registrierung, relevante Fortbildung und ein Prüflink, sofern verfügbar.',
      clinicTitle: 'Bei der Klinik',
      clinicText: 'Zulassungen, Qualitätszertifikate und belegbare Protokolle mit Aussteller, Nummer, Datum und Gültigkeit.',
      emptyLabel: 'Vorbereitete Struktur',
      emptyNote: 'Nur schriftlich verifizierte Dokumente werden als Nachweis veröffentlicht.',
      issuedBy: 'Ausgestellt von',
      issuedOn: 'Ausgestellt am',
      validUntil: 'Gültig bis',
      identifier: 'Referenz',
      view: 'Verifizierung ansehen',
    },
    reviews: {
      eyebrow: 'Erfahrungen mit Herkunft',
      title: 'Echte Worte. Immer bis zur Quelle nachvollziehbar.',
      intro: 'Eine Bewertung erscheint nur mit Einwilligung, Namensangabe und funktionierendem Quellenlink. Keine erfundenen Sterne und keine unprüfbaren Zahlen.',
      emptyTitle: 'Raum für echte Patientenerfahrungen.',
      emptyText: 'Nach Anbindung der offiziellen Bewertungsquelle erscheinen hier ausgewählte, freigegebene Erfahrungen. Die Seite bleibt auch ohne Bewertungsdaten ruhig und glaubwürdig.',
      source: 'Bei der Quelle lesen',
    },
    socials: {
      title: 'Der Klinik folgen',
      text: 'Sehen Sie den Klinikalltag, das Team und Neuigkeiten über die offiziellen Kanäle.',
      facebook: 'Facebook',
      instagram: 'Instagram',
      pending: 'Offizieller Link folgt nach Verifizierung',
    },
  },
  fr: {
    team: {
      eyebrow: 'Les personnes derrière vos soins',
      title: 'La confiance commence par savoir qui prend soin de vous.',
      intro: 'Chaque clinique est unique. Chaque dentiste dispose donc d’un véritable profil : expérience, domaines de traitement, langues et qualifications vérifiables — sans portrait anonyme de photothèque ni affirmation générale.',
      emptyTitle: 'Votre équipe deviendra le visage de ce site.',
      emptyText: 'Cette démonstration commerciale ne présente volontairement aucun membre fictif. Ajoutez les profils vérifiés de la clinique et cet espace deviendra une rencontre personnelle.',
      emptyLabel: 'Prêt pour les données réelles de la clinique',
      emptyMonogram: 'ÉQUIPE',
      emptySlots: [
        ['01', 'Profil du dentiste', 'Nom, portrait, fonction et vision personnelle'],
        ['02', 'Qualifications professionnelles', 'Formation, inscription et perfectionnement pertinent'],
        ['03', 'Langues & domaines de soins', 'Clarté pour les patients locaux et internationaux'],
      ],
      qualifications: 'Qualifications',
      registration: 'Inscription professionnelle',
      languages: 'Langues',
      treatments: 'Domaines de traitement',
      verify: 'Vérifier la source',
      contact: 'Rencontrer l’équipe',
    },
    credentials: {
      eyebrow: 'Une qualité vérifiable',
      title: 'Les qualifications personnelles et les certificats de la clinique sont distincts.',
      intro: 'Les diplômes et inscriptions appartiennent au praticien. Les autorisations, protocoles de stérilisation et certificats qualité appartiennent à la clinique. Nous les présentons séparément avec l’organisme émetteur et la validité.',
      dentistTitle: 'Pour chaque dentiste',
      dentistText: 'Formation, inscription professionnelle, perfectionnement pertinent et lien de vérification lorsqu’il existe.',
      clinicTitle: 'Pour la clinique',
      clinicText: 'Autorisations, certificats qualité et protocoles démontrables avec émetteur, numéro, date et validité.',
      emptyLabel: 'Structure prête à compléter',
      emptyNote: 'Seuls les documents vérifiés par écrit sont publiés comme preuve.',
      issuedBy: 'Émis par',
      issuedOn: 'Émis le',
      validUntil: 'Valable jusqu’au',
      identifier: 'Référence',
      view: 'Voir la vérification',
    },
    reviews: {
      eyebrow: 'Des expériences sourcées',
      title: 'Des mots authentiques. Toujours reliés à leur source.',
      intro: 'Un avis n’est publié qu’avec consentement, nom affiché et lien source fonctionnel. Aucune étoile inventée, aucun volume invérifiable.',
      emptyTitle: 'Un espace pour de véritables expériences patients.',
      emptyText: 'Après connexion à la source officielle, des témoignages sélectionnés et autorisés apparaîtront ici. La page reste sereine et crédible, même sans données d’avis.',
      source: 'Lire à la source',
    },
    socials: {
      title: 'Suivre la clinique',
      text: 'Découvrez le quotidien, l’équipe et les actualités via les canaux officiels.',
      facebook: 'Facebook',
      instagram: 'Instagram',
      pending: 'Lien officiel après vérification',
    },
  },
  lb: {
    team: {
      eyebrow: 'D’Mënschen hannert Ärer Behandlung',
      title: 'Vertrauen fänkt domat un, ze wëssen, wien fir Iech do ass.',
      intro: 'All Klinik ass eenzegaarteg. Dofir kritt all Zänndoktesch an Zänndokter en eegene Profil mat Erfarung, Behandlungsberäicher, Sproochen a kontrolléierbare Qualifikatiounen — ouni anonym Stockportraite oder allgemeng Behaaptungen.',
      emptyTitle: 'Äert Team gëtt d’Gesiicht vun dëser Website.',
      emptyText: 'Dës Verkafsdemonstratioun weist bewosst keng erfonnt Mataarbechter. Füügt déi verifizéiert Klinikprofiller bäi an dëse Raum gëtt zu enger perséinlecher Virstellung.',
      emptyLabel: 'Bereet fir echt Klinikdaten',
      emptyMonogram: 'EKIPP',
      emptySlots: [
        ['01', 'Profil vum Zänndokter', 'Numm, Portrait, Roll a perséinlech Approche'],
        ['02', 'Berufflech Qualifikatiounen', 'Ausbildung, Registréierung a relevant Weiderbildung'],
        ['03', 'Sproochen & Behandlungsberäicher', 'Kloerheet fir lokal an international Patienten'],
      ],
      qualifications: 'Qualifikatiounen',
      registration: 'Berufflech Registréierung',
      languages: 'Sproochen',
      treatments: 'Behandlungsberäicher',
      verify: 'Quell kontrolléieren',
      contact: 'D’Ekipp kenneléieren',
    },
    credentials: {
      eyebrow: 'Kontrolléierbar Qualitéit',
      title: 'Perséinlech Qualifikatiounen a Klinikzertifikater sinn net datselwecht.',
      intro: 'Diplomer a Registréierunge gehéieren zur behandelnder Persoun. Geneemegungen, Sterilisatiounsprotokoller a Qualitéitszertifikater gehéieren zur Klinik. Mir weisen se getrennt mat Aussteller a Gültegkeet.',
      dentistTitle: 'Bei all Zänndokter',
      dentistText: 'Ausbildung, berufflech Registréierung, relevant Weiderbildung an e Kontrolllink, wann en disponibel ass.',
      clinicTitle: 'Bei der Klinik',
      clinicText: 'Geneemegungen, Qualitéitszertifikater a noweisbar Protokoller mat Aussteller, Nummer, Datum a Gültegkeet.',
      emptyLabel: 'Virbereet Struktur',
      emptyNote: 'Nëmme schrëftlech verifizéiert Dokumenter ginn als Beweis publizéiert.',
      issuedBy: 'Ausgestallt vun',
      issuedOn: 'Ausgestallt den',
      validUntil: 'Gülteg bis',
      identifier: 'Referenz',
      view: 'Verifizéierung kucken',
    },
    reviews: {
      eyebrow: 'Erfarunge mat enger Quell',
      title: 'Echt Wierder. Ëmmer bis bei d’Quell zeréckzeféieren.',
      intro: 'Eng Bewäertung gëtt nëmme mat Zoustëmmung, Nummduerstëllung an engem funktionéierende Quelllink publizéiert. Keng erfonnt Stären a keng onkontrolléierbar Zuelen.',
      emptyTitle: 'Raum fir echt Patientenerfarungen.',
      emptyText: 'No der Verbindung mat der offizieller Bewäertungsquell erschéngen hei ausgewielten an autoriséiert Erfarungen. D’Säit bleift och ouni Bewäertungsdaten roueg a glafwierdeg.',
      source: 'Bei der Quell liesen',
    },
    socials: {
      title: 'Der Klinik suivéieren',
      text: 'Entdeckt den Alldag, d’Ekipp an Neiegkeeten iwwer déi offiziell Kanäl.',
      facebook: 'Facebook',
      instagram: 'Instagram',
      pending: 'Offizielle Link no der Verifizéierung',
    },
  },
  en: {
    team: {
      eyebrow: 'The people behind your care',
      title: 'Trust starts with knowing who will care for you.',
      intro: 'Every clinic is unique. Each dentist therefore receives a real profile with experience, treatment focus, languages and verifiable qualifications — never anonymous stock portraits or generic claims.',
      emptyTitle: 'Your team will become the face of this website.',
      emptyText: 'This sales demo deliberately shows no fictional staff. Add the clinic’s verified profiles and this space becomes a personal introduction.',
      emptyLabel: 'Ready for real clinic data',
      emptyMonogram: 'TEAM',
      emptySlots: [
        ['01', 'Dentist profile', 'Name, portrait, role and personal approach'],
        ['02', 'Professional qualifications', 'Education, registration and relevant continuing training'],
        ['03', 'Languages & treatment focus', 'Clarity for local and international patients'],
      ],
      qualifications: 'Qualifications',
      registration: 'Professional registration',
      languages: 'Languages',
      treatments: 'Treatment focus',
      verify: 'Verify source',
      contact: 'Meet the team',
    },
    credentials: {
      eyebrow: 'Quality you can verify',
      title: 'Personal qualifications and clinic certificates are not the same.',
      intro: 'Degrees and registrations belong to the clinician. Licences, sterilisation protocols and quality certificates belong to the clinic. We present them separately, with issuer and validity details.',
      dentistTitle: 'For every dentist',
      dentistText: 'Education, professional registration, relevant continuing training and a verification link where one is available.',
      clinicTitle: 'For the clinic',
      clinicText: 'Licences, quality certificates and evidenced protocols with issuer, number, date and validity.',
      emptyLabel: 'Ready-to-fill structure',
      emptyNote: 'Only documents verified in writing are published as evidence.',
      issuedBy: 'Issued by',
      issuedOn: 'Issued on',
      validUntil: 'Valid until',
      identifier: 'Reference',
      view: 'View verification',
    },
    reviews: {
      eyebrow: 'Experiences with a source',
      title: 'Real words. Always traceable to their source.',
      intro: 'A review is published only with consent, a display name and a working source link. No invented stars and no unverifiable totals.',
      emptyTitle: 'Space for real patient experiences.',
      emptyText: 'Once the official review source is connected, selected and consented experiences will appear here. The page remains calm and credible even without review data.',
      source: 'Read at source',
    },
    socials: {
      title: 'Follow the clinic',
      text: 'See the daily work, the team and clinic news through the official channels.',
      facebook: 'Facebook',
      instagram: 'Instagram',
      pending: 'Official link pending verification',
    },
  },
  ka: {
    team: {
      eyebrow: 'თქვენს მკურნალობაზე პასუხისმგებელი ადამიანები',
      title: 'ნდობა იწყება იმით, რომ იცოდეთ, ვინ იზრუნებს თქვენზე.',
      intro: 'ყველა კლინიკა უნიკალურია. ამიტომ თითოეულ სტომატოლოგს ეკუთვნის რეალური პროფილი გამოცდილებით, მკურნალობის მიმართულებებით, ენებითა და გადამოწმებადი კვალიფიკაციებით — ანონიმური ფოტოებისა და ზოგადი განცხადებების გარეშე.',
      emptyTitle: 'თქვენი გუნდი ამ ვებსაიტის სახე გახდება.',
      emptyText: 'ეს გასაყიდი დემო განზრახ არ აჩვენებს გამოგონილ თანამშრომლებს. დაამატეთ კლინიკის გადამოწმებული პროფილები და ეს სივრცე პირად გაცნობად გადაიქცევა.',
      emptyLabel: 'მზადაა კლინიკის რეალური მონაცემებისთვის',
      emptyMonogram: 'გუნდი',
      emptySlots: [
        ['01', 'სტომატოლოგის პროფილი', 'სახელი, პორტრეტი, როლი და პირადი მიდგომა'],
        ['02', 'პროფესიული კვალიფიკაციები', 'განათლება, რეგისტრაცია და შესაბამისი შემდგომი სწავლება'],
        ['03', 'ენები და მკურნალობის მიმართულებები', 'სიცხადე ადგილობრივი და საერთაშორისო პაციენტებისთვის'],
      ],
      qualifications: 'კვალიფიკაციები',
      registration: 'პროფესიული რეგისტრაცია',
      languages: 'ენები',
      treatments: 'მკურნალობის მიმართულებები',
      verify: 'წყაროს გადამოწმება',
      contact: 'გაიცანით გუნდი',
    },
    credentials: {
      eyebrow: 'ხარისხი, რომლის გადამოწმებაც შეგიძლიათ',
      title: 'პირადი კვალიფიკაციები და კლინიკის სერტიფიკატები ერთი და იგივე არ არის.',
      intro: 'დიპლომები და რეგისტრაციები სპეციალისტს ეკუთვნის. ლიცენზიები, სტერილიზაციის პროტოკოლები და ხარისხის სერტიფიკატები — კლინიკას. მათ ცალ-ცალკე, გამცემისა და მოქმედების ვადის მითითებით წარმოვადგენთ.',
      dentistTitle: 'თითოეულ სტომატოლოგთან',
      dentistText: 'განათლება, პროფესიული რეგისტრაცია, შესაბამისი შემდგომი სწავლება და გადამოწმების ბმული, თუ ის ხელმისაწვდომია.',
      clinicTitle: 'კლინიკასთან',
      clinicText: 'ლიცენზიები, ხარისხის სერტიფიკატები და დადასტურებული პროტოკოლები გამცემის, ნომრის, თარიღისა და მოქმედების ვადის მითითებით.',
      emptyLabel: 'შესავსებად მზად სტრუქტურა',
      emptyNote: 'მტკიცებულებად მხოლოდ წერილობით გადამოწმებული დოკუმენტები ქვეყნდება.',
      issuedBy: 'გამცემი',
      issuedOn: 'გაცემის თარიღი',
      validUntil: 'მოქმედებს',
      identifier: 'მითითება',
      view: 'გადამოწმების ნახვა',
    },
    reviews: {
      eyebrow: 'გამოცდილებები წყაროთი',
      title: 'რეალური სიტყვები. ყოველთვის მიკვლევადი წყარომდე.',
      intro: 'შეფასება ქვეყნდება მხოლოდ თანხმობით, გამოსაჩენი სახელითა და მოქმედი წყაროს ბმულით. გამოგონილი ვარსკვლავებისა და დაუდასტურებელი რაოდენობების გარეშე.',
      emptyTitle: 'სივრცე პაციენტების რეალური გამოცდილებისთვის.',
      emptyText: 'ოფიციალური შეფასებების წყაროს დაკავშირების შემდეგ აქ გამოჩნდება შერჩეული და თანხმობით გამოქვეყნებული გამოცდილებები. გვერდი მშვიდი და სანდო რჩება შეფასებების გარეშეც.',
      source: 'წაიკითხეთ წყაროზე',
    },
    socials: {
      title: 'გამოიწერეთ კლინიკა',
      text: 'იხილეთ ყოველდღიური სამუშაო, გუნდი და კლინიკის სიახლეები ოფიციალურ არხებზე.',
      facebook: 'Facebook',
      instagram: 'Instagram',
      pending: 'ოფიციალური ბმული გამოჩნდება გადამოწმების შემდეგ',
    },
  },
}
